const words = [
  ['daily', 'ежедневный'],
  ['courage', 'смелость'],
  ['affair', 'связь'],
  ['to involve', 'вовлекать'],
  ['to hold with', 'быть согласным с чем-то, поддерживать какую-то идею'],
  ['to expect', 'ожидать'],
  ['hardly', 'почти, едва, на "h"'],
  ['although', 'хотя, однако, на "a"'],
  ['nearly', 'почти, на "n"'],
  ['to crane', 'вытягивать шею'],
  ['fence', 'забор'],
  ['to bear', 'выносить (плохую новость)'],
  ['to find out', 'выяснять, на "fin"'],
  ['to shudder to think', 'содрагаться от мысли'],
  ['to keep away', 'держаться подальше, на "k"'],
  ['dull', 'скучный, унылый'],
  ['to suggest', 'предлагать'],
  ['to hum', 'урчать, напевать'],
  ['to pick up', 'подобрать, подвезти'],
  ['to wrestle', 'бороться'],
  ['to notice', 'замечать (на "n")'],
  ['tawn', 'загорелый'],
  ['tawny', 'коричневатый'],
  ['to flutter', 'трепетать'],
  ['to peck', 'клевать'],
  ['briefcase', 'портфель'],
  ['tantrum', 'истерика'],
  ['to chortle', 'усмехнуться, на "c"'],
  ['to back out', 'покидать, отступать'],
  ['sign', 'знак'],
  ['peculiar', 'специфичный, своеобразный'],
  ['to jerk', 'дернуть'],
  ['tabby', 'полосатый'],
  ['trick', 'уловка, трюк, на "t"'],
  ['toward', 'в направлении'],
  ['edge', 'край чего-то'],
  ['traffic jam', 'дорожная пробка'],
  ['cloak', 'плащ'],
  ['get-ups', 'прически'],
  ['to suppose', 'предполагать, на "s"'],
  ['steering wheel', 'руль машины'],
  ['huddle', 'кучка, на "h"'],
  ['weirdos', 'чудаки'],
  ['to enrage', 'приводить в ярость'],
  ['struck', 'пораженный'],
  ['stunt', 'трюк, фокус, на "s"'],
  ['obviously', 'очевидно (вводное слово)'],
  ['to swoop', 'налетать'],
  ['in broad daylight', 'средь бела дня'],
  ['to gaze', 'пристально глядеть'],
  ['to speed overhead', 'проноситься над головой'],
  ['however', 'однако'],
  ['bun', 'булочка, пучок'],
  ['to stretch legs', 'размять ноги'],
  ['uneasy', 'беспокойный'],
  ['tin', 'олово, жестяная банка, на "t"'],
  ['to stop dead', 'остановиться как вкопанный'],
  ['to flood', 'наводнить, затопить'],
  ['to clutch', 'хватать, на "c"'],
  ['to dash', 'ринуться, броситься, на "d"'],
  ['to snap', 'щелкнуть, огрызнуться'],
  ['to seize', 'схватить, на "se"'],
  ['almost', 'почти, на "a"'],
  ['to dial', 'набирать номер'],
  ['receiver', 'приемник (емкость)'],
  ['to stroke', 'поглаживать'],
  ['to blame', 'винить, на "b"'],
  ['to walk straight into', 'идти прямо в...'],
  ['to grunt', 'хрюкать'],
  ['to stumble', 'спотыкаться, на "s"'],
  ['to knock on the ground', 'повалить на землю'],
  ['on the contrary', 'с другой стороны'],
  ['wide', 'широкий'],
  ['squeaky', 'визгливый'],
  ['passers by', 'прохожие'],
  ['to rejoice', 'ликовать'],
  ['rattle', 'грохот, хрип, на "ra"'],
  ['to spot', 'замечать (на "s")'],
  ['stern', 'суровый, на "st"'],
  ['to wonder', 'задаваться вопросом'],
  ['to let into', 'впустить в...'],
  ['to determine', 'определять'],
  ['unable', 'не в состоянии'],
  ['pattern', 'шаблон, образец'],
  ['to grin', 'скалить зубы'],
  ['oddly', 'странно'],
  ['downpour', 'ливень'],
  ['until', 'до того момента'],
  ['folks', 'ребята'],
  ['all over the place', 'повсюду'],
  ['throat', 'горло'],
  ['lately', 'недавно'],
  ['sharp', 'острый'],
  ['sharply', 'резко'],
  ['to mumble', 'бормотать (на "mum")'],
  ['to purse', 'поджимать, морщить, на "p"'],
  ['to dare', 'oсмеливаться, посметь'],
  ['stiffly', 'чопорно'],
  ['common', 'распространенный, общий'],
  ['heart sinking', 'сердце замирает'],
  ['to creep', 'ползать'],
  ['to peer', 'всматриваться'],
  ['to relate', 'относиться'],
  ['to yawn', 'завать'],
  ['to affect', 'влиять'],
  ['to slam', 'захлопывать'],
  ['neither, nor', 'ни, ни'],
  ['to twitch', 'дергаться, дрогнуть, на "t"'],
  ['to narrow', 'сужаться'],
  ['judging by', 'судя по...'],
  ['to tuck', 'подгибать, заправлять'],
  ['robe', 'халат'],
  ['to sweep', 'подметать'],
  ['high-heeled', 'на высоком каблуке'],
  ['buckle', 'пряжка, застежка'],
  ['as though', 'как будто'],
  ['spectacles', 'очки'],
  ['crook', 'согнутый, на "c"'],
  ['to rummage', 'рыться'],
  ['for some reason', 'по какой-то причине'],
  ['to chuckle', 'посмеиваться'],
  ['to mutter', 'бормотать, на "mut"'],
  ['it seem to be', 'кажется, это...'],
  ['to flick', 'щелкнуть, на "f"'],
  ['heady', 'опрометчивый, безрассудный'],
  ['pavement', 'тротуар'],
  ['to slip', 'скользить (4 буквы)'],
  ['to set off', 'отправляться'],
  ['fancy', 'причудливый, фантазия'],
  ['rather', 'скорее (вводное слово)'],
  ['severe', 'суровый, на "se"'],
  ['to ruffle', 'взъерошить'],
  ['distinctly', 'отчетливо, внятно'],
  ['dozen', 'дюжина'],
  ['to sniff', 'нюхать'],
  ['impatiently', 'нетерпеливо'],
  ['to be bound to', 'обязательно (словосочетание)'],
  ['bound', 'связанный'],
  ['i will bet', 'могу поспорить...'],
  ['precious', 'бесценный. драгоценный'],
  ['to swap', 'обмениваться'],
  ['downright', 'явно'],
  ['careless', 'беспечный, неосторожный'],
  ['sideway glance', 'косой взгляд (словосочетание)'],
  ['very day', 'тот самый день (словосочетание)'],
  ['surely', 'конечно'],
  ['to persuade', 'убеждать, на "p"'],
  ['proper', 'правильный'],
  ['nonsense', 'чепуха, на "n"'],
  ['to flinch', 'вздрагивать, на "f"'],
  ['exasperate', 'раздраженный'],
  ['to admire', 'восхищаться, на "a"'],
  ['to flatter', 'льстить'],
  ['noble', 'благородный'],
  ['to blush', 'краснеть'],
  ['earmuffs', 'наушники'],
  ['anxious', 'тревожный, озадаченный'],
  ['to pierce', 'прокалывать'],
  ['piercing stare', 'пронзительный взгляд'],
  ['plain', 'простой'],
  ['however', 'однако'],
  ['drop', 'леденец, капля'],
  ['to turn up', 'оказаться'],
  ['to bow', 'кланяться'],
  ['bow', 'лук (оружие)'],
  ['to gasp', 'дышать с трудом (одно слово)'],
  ['to pat on', 'похлопать по..., на "p"'],
  ['to reach out', 'дотянуться'],
  ['to tremble', 'дрожать, на "t"'],
  ['somehow', 'как-то'],
  ['to nod', 'кивать'],
  ['glum', 'угрюмый'],
  ['to falter', 'запинаться'],
  ['to astound', 'поражать (astonish)'],
  ['in the name of heaven', 'во имя небес'],
  ['handkerchief', 'носовой платок'],
  ['lace', 'кружево'],
  ['to pull out', 'вытаскивать'],
  ['to dab', 'вытирать, на "d"'],
  ['beneath', 'под'],
  ['to examine', 'исследовать, изучать'],
  ['though', 'хотя, на "t"'],
  ['firm', 'твердый'],
['firmly', 'твердо'],
['be able to', 'быть способным сделать что-то'],
['faint', 'слабый'],
['faintly', 'слабо'],
['to swallow', 'глотать'],
['wise', 'мудрый'],
['to trust with', 'доверить что-либо (словосочетание)'],
['gringingly', 'неохотно'],
['tend to', 'склонный к...'],
['rumble', 'грохот, на "ru"'],
['steadly', 'непрерывно'],
['headlight', 'фара'],
['roar', 'рев'],
['to swell', 'набухать, возрастать'],
['astride', 'верхом'],
['to allow', 'позволять'],
['tangle', 'клубок, спутанный клубок'],
['dustbin', 'мусорный ящик'],
['lid', 'крышка'],
['bushy', 'густой'],
['vast', 'крупный, обширный'],
['bundle', 'сверток, пакет'],
['blanket', 'одеяло'],
['to relieve', 'облегчать, освобождать'],
['to borrow', 'одалживать (получать)'],
['to lend', 'одалживать (отдавать)'],
['to swarm', 'кишеть, толпиться'],
['to bend', 'сгибаться, на "b"'],
['fast asleep', 'крепко уснуть'],
['tuft', 'пучок (не прическа)'],
['jet-black', 'угольно-черный'],
['forehead', 'лоб'],
['curiously', 'любопытно'],
['to get over with', 'покончить с...'],
['scratchy', 'колючий'],
['whiskery', 'усатый'],
['to hawl', 'выть'],
['to wound', 'ранить'],
['to hiss', 'шипеть'],
['to sob', 'всхлипывать'],
['to get a grip', 'собраться, взять себя в руки'],
['grip', 'захват'],
['gingerly', 'осторожно'],
['to twinkle', 'мерцать'],
['to muffle', 'глушить, заглушить'],
['stream', 'течение, поток'],
['to wipe', 'вытирать (на "w")'],
['engine', 'двигатель'],
['to blow nose', 'высморкаться'],
['to make out', 'разобрать, различить'],
['to slink', 'красться, проскальзывать, на "s"'],
['to murmur', 'ворчать, шептать'],
['heel', 'каблук'],
['swish', 'шелест'],
['neat', 'аккуратный'],
['ink', 'чернила'],
['to prod', 'пинать, толкать (на "p")'],
['to pinch', 'зажимать, щипать'],
['hush', 'тишина, молчание'],
['to vanish', 'исчезать'],
['brass', 'латунь, латунный'],
['mantelpiece', 'каминная полка'],
['to bobble', 'бурлить'],
['on a roundabout at the fair', 'на карусели на ярмарке'],
['not for long', 'ненадолго'],
['shrill', 'пронзительный'],
['to rap on', 'стучать в... (на "r")'],
['to screech', 'визжать'],
['cooker', 'кухонная плита'],
['pan', 'кастрюля'],
['frying pan', 'сковорода'],
['to demand', 'требовать'],
['to groan', 'стонать'],
['cupboard', 'буфет, чулан'],
['beneath', 'под (на "b")'],
['as though', 'как будто'],
['punch bag', 'боксерская груша'],
['knobbly', 'бугристый, на "k"'],
['sellotape', 'скотч'],
['by the way of', 'посредством (словосочетание)'],
['to comb', 'причесываться'],
['put together', 'вместе взятые'],
['rest of', 'остальная часть'],
['thick', 'толстый'],
['smooth', 'гладкий'],
['wig', 'парик'],
['in case', 'в случае'],
['to scent', 'чуять'],
['to grab', 'захватывать, хватать (на "g")'],
['parcel', 'посылка, сверток'],
['tyke', 'дворняжка, грубиян'],
['to unwrap', 'разворачивать'],
['to rip', 'рвать'],
['to leap', 'скакать, вскочить'],
['ought', 'должен'],
['slug', 'слизень'],
['for a change', 'для разнообразия'],
['to snarl', 'рычать, на "s"'],
['to blow up', 'взрываться'],
['to screw up face', 'скривить лицо'],
['to wail', 'вопить, на "w"'],
['to spoil', 'портить'],
['to fling', 'бросать, кидать (на "f")'],
['gap', 'пробел'],
['frantically', 'неистово, отчаянно'],
['scrowny', 'тощий'],
['at once', 'сразу же'],
['aside', 'в сторону'],
['fringe', 'челка'],
['baggy', 'мешковатый'],
['however', 'однако'],
['to shear', 'срезать, стричь'],
['to force', 'заставлять'],
['to revolt', 'бунтовать, восставать'],
['puppet', 'марионетка'],
['revolting', 'отвратительный'],
['glove puppet', 'кукла, которая надевается на руку'],
['to shrink', 'сокращаться, уменьшаться'],
['relief', 'облегчение'],
['to punish', 'наказывать'],
['to chase', 'преследовать'],
['chimney', 'дымоход'],
['headmistress', 'директриса'],
['bin', 'мусорное ведро'],
['to complain', 'жаловаться'],
['to overtake', 'обогнать'],
['hoodlums', 'хулиганы'],
['beetroot', 'свекла'],
['to snig', 'хихикать (на "s")'],
['van', 'фургон'],
['remarkably', 'в высшей степени'],
['either', 'тоже'],
['to scratch', 'царапать'],
['afterwards', 'в последствии'],
['lit', 'освещенный'],
['to slither', 'скользить (7 букв)'],
['to wrap', 'заворачивать, оборачивать'],
['glistening', 'блестящий'],
['to whin', 'скулить'],
['to budge', 'сдвинуться с места'],
['to tap', 'постучаться, на "t"'],
['to order', 'приказывать, заказывать'],
['knuckle', 'сустав пальца'],
['smartly', 'ловко (придумать, найти решение)'],
['to snooze', 'дремать'],
['to shuffle', 'шаркать'],
['tank', 'резервуар'],
['boredom', 'скука'],
['hummer', 'молоток'],
['at least', 'по крайней мере, в конце концов'],
['beady', 'как бусинки'],
['to wink', 'подмигивать'],
['ceiling', 'потолок'],
['vigorously', 'решительно'],
['to jab', 'тыкать (на "j")'],
['to breed', 'разводить'],
['deafening', 'оглушительный'],
['to waddle', 'ковылять'],
['concrete', 'бетон'],
['cought by surprise', 'застанный врасплох'],
['to constrict', 'сжимать на "co"'],
['to uncoil', 'размотать'],
['throughout', 'повсюду (на "t")'],
['to slide', 'сколькзить (5 букв)'],
['swift', 'быстрый'],
['to gibber', 'невнятно бормотать'],
['to squeeze', 'сжимать, на "s"'],
['managed to', 'суметь что-то, на "m"'],
['to collapse', 'разрушиться'],
['to strain', 'напрягать'],
['to forbid', 'запретить'],
['to rush out', 'выбежать (словосочетание)'],
['to wave', 'махать'],
['merrily', 'радостно'],
['boa', 'удав (на "b")'],
['constrictor', 'удав (на "c")'],
['crutches', 'костыли'],
['to wander', 'бродить'],
['ray', 'луч'],
['comprehensive', 'всесторонний'],
['to stuff', 'засовывать, на "stu"'],
['to trip', 'споткнуться (на "t")'],
['to fond', 'любить'],
['to smelt', 'плавить, выплавлять'],
['maroon', 'темно-бордовый'],
['tailcoat', 'фрак'],
['knickerbockers', 'бриджи'],
['flat', 'плоский'],
['straw', 'солома'],
['boater', 'лодочник'],
['gruff', 'грубо'],
['to burst', 'взрываться (5 букв)'],
['to burst into tears', 'разразиться слезами'],
['tub', 'ванная, бадья'],
['rag', 'тряпка'],
['bowl', 'чаша'],
['to dye', 'красить'],
['to argue', 'спорить'],
['to wrinkle', 'морщить, на "w"'],
['to bang', 'ударить, стункнуть (на "b")'],
['to flop', 'провалиться'],
['doormat', 'коврик перед дверью'],
['to poke', 'тыкать'],
['to dodge', 'изворачиваться, увернуться'],
['envelope', 'конверт'],
['yellowish', 'желтоватый'],
['parchment', 'пергамент'],
['seal', 'печать'],
['coat of arms', 'герб'],
['eagle', 'орел'],
['badger', 'барсук'],
['to hand', 'передать'],
['to flip', 'перевернуть, на "f"'],
['to snort', 'фыркнуть'],
['whelk', 'щенок'],
['to unfold', 'раскрывать, на "u"'],
['to snatch', 'хватать, на "sn"'],
['to sneer', 'насмехаться'],
['to glance', 'взглянуть'],
['to choke', 'задыхаться'],
['to croak', 'квакать'],
['scruff', 'загривок'],
['promptly', 'быстро, на "p"'],
['to dangle', 'свисать'],
['crack', 'трещина, щель'],
['to quiver', 'дрожать, на "q"'],
['to pace', 'шагать, расхаживать, на "p"'],
['to stamp out', 'уничтножить (словосочетание)'],
['to swap', 'менять'],
['rifle', 'винтовка'],
['bent', 'изогнутый, погнутый (4 буквы)'],
['to bawl', 'орать, на "b"'],
['to sigh', 'вздыхать'],
['on purpose', 'нарочно, намеренно'],
['to whack', 'бить, колотить, на "w"'],
['tortoise', 'черепашка'],
['greenhouse', 'теплица'],
['to strangle', 'душить'],
['to wheeze', 'хрипеть'],
['to tread', 'топтать, наступить'],
['squashy', 'мягкий'],
['lap', 'колени'],
['to tear', 'рвать, на "t"'],
['to nail up', 'заколачивать гвоздями'],
['to slot', 'прорезать'],
['to board up', 'заколачивать досками'],
['to tiptoe', 'ходить на цыпочках'],
['to shred', 'измельчать'],
['dairy', 'молочный, сыроварня'],
['to spread', 'распространять'],
['to whiz', 'свистеть, просвистеть'],
['to pelt', 'сыпаться'],
['waist', 'талия'],
['to bounce', 'подпрыгивать, отскакивать'],
['wrench', 'гаечный ключ'],
['to wrench', 'вырывать, раскнутить гайки'],
['whenever', 'всякий раз, когда...'],
['nightfall', 'сумерки'],
['to blow up', 'взрываться'],
['gloomy', 'мрачный'],
['outskirts', 'окраина, на "o"'],
['damp', 'сырой'],
['musty', 'затхлый'],
['stale', 'несвежий'],
['tinned', 'консервированный'],
['dining-room', 'столовая'],
  ['outta', 'из'],
['flame', 'пламя'],
['purge', 'очистка'],
['basement', 'подвал, на "b"'],
['boozer', 'пьяница'],
['fiend', 'изверг, злодей'],
['to itch', 'зудеть'],
['gruesome', 'ужасный, отвратительный (на "g")'],
['denial', 'отказ'],
['seem to', 'кажется, что...'],
['stake', 'кол'],
['to pop', 'хлопнуть'],
['peak', 'пик'],
['to represent', 'представлять (шоу)'],
['threat', 'угроза'],
['to crowl', 'красться, на "c"'],
['just so', 'просто чтобы...'],
['disregard', 'пренебрежение'],
['handful', 'горсть'],
['do not get me wrong', 'не пойми меня неправильно (без апострофа)'],
['to convince', 'убеждать, на "c"'],
['insecure', 'небезопасный'],
['unconfident', 'неуверенный'],
['it does not make sense', 'это не имеет смысла, главное слово на "s"'],
['to doubt', 'сомневаться'],
['pervert', 'извращенец'],
['stubborn', 'упрямый'],
['frugal', 'бережливый, экономный'],
['skam', 'мошенничество, на "s"'],
['funural', 'похроны'],
['desperation', 'безысходность, отчаяние'],
['hilarious', 'веселый'],
['to supply', 'поставлять (продукцию)'],
['to downsize', 'сократить'],
['advantage', 'преимущество'],
['theft', 'кража'],
['margin', 'прибыль'],
['misconduct', 'проступок'],
['gross', 'суммарный, на "g"'],
['severance pay', 'выходное пособие'],
['inventory', 'инвентарь'],
['barely', 'едва (на "b")'],
['expenses', 'расходы'],
['godfather', 'крестный отец'],
['goofy', 'бестолковый'],
['to attend', 'посещать, на "a"'],
['scrubs', 'заросли'],
['to sued', 'подать иск'],
['to admit', 'признаваться, на "a"'],
['to confess', 'признаваться, на "c"'],
['to encourage', 'поощерять'],
['male', 'самец, мужчина'],
['splash', 'всплеск'],
['sissy', 'неженка, маменькин сынок'],
['inch', 'дюйм'],
['subconscious', 'подсознание'],
['ailment', 'недуг'],
['to frazzle', 'вымотать, измотать, на "f"'],
['to overstate', 'преувеличивать'],
['stiff', 'жесткий, твердый, на "s"'],
['to bleed', 'кровоточить'],
['stain', 'пятно, 5 букв'],
['harmful', 'вредный'],
['to stick', 'вставлять, на "sti"'],
['to insert', 'вставлять, на "i"'],
['fluid', 'жидкость'],
['needle', 'игла'],
['to branch out', 'разъеденться (словосочетание)'],
['to attach', 'прикреплять, пристегнуть'],
['to pronounce', 'объявить, на "p"'],
['to declare', 'объявить, на "d"'],
['already', 'уже'],
['wind', 'дыхание, на "w"'],
['insurance', 'страховка'],
['renal failer', 'почечная недостаточность'],
['autopsy', 'вскрытие трупа'],
['to scratch off', 'соскребать с...'],
['diversity', 'разнообразие'],
['to mandate', 'уполномочить'],
['punch', 'удар'],
['sturdy', 'крепкий'],
['consumer', 'потребитель'],
['content', 'довольный'],
['retaliation', 'возмездие'],
['for some reason', 'по какой-то причине'],
['comission', 'поручение'],
['ignorance', 'невежество'],
['to arise', 'возникать'],
['permission', 'разрешение'],
['to steer away', 'держаться подальше, на "s"'],
['familiar', 'ознакомленный'],
['to reenact', 'воспроизвести'],
['outcome', 'исход'],
['to account', 'объяснять, на "a"'],
['to butcher', 'убивать, на "b"'],
['acronym', 'аббревиатура'],
['harm', 'вред, на "h"'],
['supernatural', 'сверхъестесственный'],
['trauma', 'травма'],
['to avenge', 'мстить'],
['envy', 'зависть'],
['joint', 'совместный'],
['to pledge', 'обязаться, пообещать'],
['candidly', 'откровенно'],
['to advance', 'продвигать'],
['advanced', 'продвинутый'],
['awareness', 'осведомленность'],
['terms', 'условия, правила'],
['to embarrass', 'смущать'],
['to regret', 'сожалеть'],
['truly', 'действительно'],
['to insult', 'оскорблять'],
['to abandon', 'покидать, на "a"'],
['lame', 'убогий'],
['to lame', 'калечить'],
['offensive', 'обидно'],
['to squat', 'присесть, сесть на корточки'],
['cornerstone', 'камень преткновения'],
['tape', 'лента'],
['to lead', 'вести что-либо или куда-либо'],
['to get down business', 'приступить к делу'],
['connotation', 'значение'],
['term', 'термин'],
['beside', 'рядом, на "b"'],
['to treat', 'лечить'],
['sparks', 'искры'],
['versus', 'против, на "v"'],
['to percolate', 'просачиваться, проникать'],
['loan', 'займ'],
['to stir', 'размешивать, на "s"'],
['further', 'в дальнейшем'],
['convenient', 'удобный'],
['minority', 'меньшенство'],
['to redo', 'переделывать'],
['heist', 'ограбление'],
['entrepreneur', 'предприниматель'],
['against', 'против, на "a"'],
['to run', 'управлять, на "r"'],
['profitable', 'прибыльный'],
['unemployed', 'безработный'],
['to seek employment', 'искать работу'],
['to apply for a job', 'подать заявление на работу'],
['to turn down the offer', 'отклонить предложение, на "t"'],
['to accept the offer', 'принять предложение'],
['to reject the offer', 'отклонить предложение, на "r"'],
['either, or', 'или, или'],
['to recruite', 'завербовать'],
['double shift', 'двойная смена'],
['to transfer', 'переводить (в другой отдел)'],
['to promote', 'повышать'],
['department', 'отдел'],
['to demote', 'понижать'],
['in 5 years', 'через 5 лет'],
['suburb', 'пригород'],
['by then', 'к тому времени'],
['sober', 'трезвый'],
['head', 'начальник, на "h"'],
['expertise', 'компетенция'],
['strengths', 'сильные стороны'],
['goal-oriented', 'целеустремленный'],
['eager', 'жаждущий'],
['responsible', 'ответственный'],
['to be passionate to', 'испытывать страсть к...'],
['weakness', 'слабость, на "w"'],
['kidney', 'почка'],
['to justify', 'оправдать, на "j"'],
['redemption', 'искупление'],
['to reply', 'отвечать, на "rep"'],
['to get acquainted', 'знакомиться'],
['at all costs', 'любой ценой'],
['engagement', 'помолвка'],
['do not quite get you', 'не вполне тебя понял'],
['to propose', 'предлагать, на "p"'],
['for a while', 'давно'],
['to figure out', 'выяснять, на "fig"'],
['it does not add up', 'это не имеет смысла, главное слово на "a"'],
['to clear up', 'прояснить'],
['to suss out', 'раскусить'],
['to check out', 'проверить'],
['wiener', 'сарделька'],
['ladder', 'лестница, на "l"'],
['to cuddle', 'обнимать, прижимать'],
['to be in good terms', 'быть в хороших отношениях'],
['sacrifice', 'жертва'],
['rage', 'ярость'],
['evident', 'очевидный (наречие)'],
['to gather', 'собирать(ся)'],
['customs', 'таможня'],
['to delay', 'задерживаться'],
['due', 'по причине (одно слово)'],
['to proceed', 'проследовать'],
['just browse', 'просто смотреть'],
['spade', 'лопата'],
['fiance', 'жених'],
['gift-wrapped', 'подарочная упаковка'],
['to decline', 'отклонять, на "d"'],
['insufficient', 'недостаточный, неудовлетворительный'],
['funds', 'средства'],
['scarcely', 'едва, на "s"'],
['fare', 'плата за проезд'],
['plaster', 'гипс, штукатурка'],
['puddles', 'лужи'],
['to steer', 'управлять, на "s"'],
['superb', 'великолепный. на "su"'],
['remarkable', 'замечательно. на "r"'],
['to assume', 'предполагать, на "a"'],
['janitor', 'дворник'],
['humble', 'скромный'],
['attitude', 'отношение, жизненная позиция, на "a"'],
['occasionally', 'иногда, на "o"'],
['to tease', 'дразнить'],
['for instance', 'например'],
['to phrase', 'формулировать'],
['jock', 'качок'],
['chart', 'диаграмма'],
['to tattle', 'болтать'],
['to respond', 'отликаться, отвечать, на "res"'],
['ramification', 'разветвление, развилка'],
['whiny', 'плаксивый'],
['squabble', 'перебранка, ссора'],
['to drag', 'тащить, тянуть'],
['bunch', 'кучка, на "b"'],
['malcontent', 'недовольный'],
['slope', 'склон'],
['slippery', 'скользкий'],
['to suture', 'зашить, сшить'],
['lapdog', 'собачонка'],
['freckles', 'веснушки'],
['to hang out with', 'тусоваться с...'],
['surgeon', 'хирург'],
['tricky', 'хитрый'],
['plague', 'зараза, чума'],
['grace', 'изящество, милосердие'],
['ligament', 'связка, сухожилие'],
['to braid', 'заплетать (волосы)'],
['cushion', 'подушка (диванная)'],
['to plop', 'шлепнуться'],
['to bust', 'разориться'],
['to hop off', 'спрыгнуть'],
['to go ahead', 'идти вперед'],
['renewal', 'обновление'],
['acceptance', 'принятие'],
['enema', 'клизма'],
['conviction', 'убеждение, взгляды, на "c"'],
['dazzling', 'ослепительный'],
['in advance', 'заранее'],
['marvellous', 'чудесный, на "m"'],
['timit', 'робкий'],
['to plough', 'пахать (поле)'],
['suspension', 'висячий, подвисной'],
['to snivel', 'хныкать'],
['hanger', 'вешалка'],
['to perch', 'усесться, взгромоздиться'],
['shack', 'лачуга, на "s"'],
['gleefuly', 'ликующе'],
['below', 'ниже'],
['to amble up', 'подниматься неторопливой походкой'],
['wicked', 'злой'],
['to row', 'грести'],
['to whip', 'стегать, хлестать, на "w"'],
['seaweed', 'водоросли'],
['ration', 'рацион'],
['to shrivel', 'съеживаться, на "s"'],
['cheerfull', 'жизнерадостный'],
['filthy', 'грязный'],
['to splatter', 'плескаться, брызгаться'],
['hut', 'хижина, на "h"'],
['fierce', 'свирепый, на "fi"'],
['mouldy', 'заплесневелый'],
['to curl up', 'свернуться калачиком'],
['lumpy', 'бугристый, на "l"'],
['ferocious', 'свирепый, на "fe"'],
['to shiver', 'дрожать, на "s"'],
['to drown', 'тонуть'],
['dial', 'циферблат'],
['to creak', 'скрипеть'],
['to crumble', 'крошить'],
['cannon', 'пушка'],
['to skid', 'заносить (на поворотах), скользить'],
['to warn', 'предупреждать'],
['to arm', 'вооружать'],
['force', 'сила'],
['hinge', 'дверная петля'],
['to glint', 'сверкать, на "gl"'],
['mane', 'грива'],
['shaggy', 'лохматый'],
['to stoop', 'сутулиться'],
['to stride', 'шагать, на "s"'],
['to budge up', 'подвинуться'],
['lump', 'кусок, глыба'],
['to crouch', 'скорчиться'],
['rasp', 'скрежет'],
['knot', 'узел'],
['summat', 'итог, на "s"'],
['sligh', 'незначтельный, на "s"'],
['to squash', 'раздавить'],
['to rub', 'тереть'],
['to bend down', 'наклониться вниз'],
['flicker', 'вспышка, мерцание'],
['to sink', 'погрузиться (в воду)'],
['stat', 'статистика'],
['sacred', 'священный'],
['to provide', 'обеспечивать'],
['directly', 'непосредственно, напрямую'],
['in a way', 'в некотором смысле'],
['acupunchure', 'иглоукалывание'],
['assigment', 'назначение, распределение'],
['tough', 'жесткий, сильный, на "t"'],
['temporary', 'временный'],
['strike', 'удар, на "s"'],
['to groom', 'холить'],
['to slash', 'хлестать, рубить, на "s"'],
['benefit', 'выгода'],
['unless', 'если не'],
['harsh', 'суровый, на "h"'],
['to coddle', 'няньчиться, баловать'],
['to deduct', 'вычитать'],
['to swamp', 'заливать, затонуть'],
['memo', 'памятка, заметка'],
['superior', 'начальник, вышестоящий'],
['to be in charge in', 'быть ответственным за'],
['to pick', 'выбирать'],
['inappropriate', 'неподходящий, несоответствующий'],
['fortune', 'состояние (деньги)'],
['to decrease', 'сокращаться, уменьшаться (численно)'],
['specific', 'конкретный'],
['pathetic', 'жалкий, убогий, на "p"'],
['knob', 'дверная ручка'],
['pile', 'куча, груда, на "p"'],
['to invent', 'изобретать, выдумывать'],
['troop', 'отряд'],
['shaft', 'шахта'],
['to thrive', 'процветать'],
['felon', 'преступник'],
['to forge', 'подделывать'],
['to accuse', 'обвинять, на "a"'],
['to perpetrait', 'совершать'],
['carefully', 'внимательно'],
['entirely', 'полностью'],
['for cristes sake', 'ради Бога'],
['option', 'вариант'],
['to submit', 'предоставлять (информацию)'],
['to forfait', 'утратить'],
['to refer', 'ссылаться (на что-то)'],
['terrific', 'потрясающе, на "t"'],
['to expire', 'истекать (срок годности)'],
['judgmental', 'склонный к осуждению'],
['to sag', 'провисать, обвисать'],
['kettle', 'чайник (для кипячения)'],
['teapot', 'чайник (для завариваия)'],
['mug', 'кружка'],
['to chip', 'откалывать, отколоть'],
['amber', 'янтарь, янтарный'],
['swig', 'глоток, на "s"'],
['to sizzle', 'шипеть, шкварчать'],
['poker', 'кочерга, шампур'],
['to fitjet', 'ёрзать, на "f"'],
['gulp', 'глоток, на "g"'],
['to cower', 'съёжиться, на "c"'],
['to growl', 'рычать, на "g"'],
['pale', 'бледный'],
['to bewilder', 'сбивать с толку'],
['syllable', 'слог'],
['to quail', 'дрогнуть, испугаться'],
['deputy', 'заместитель'],
['to stammer', 'заикаться'],
['quill', 'перо'],
['to scribble', 'нацарапать, начеркать'],
['beak', 'клюв'],
['to clamp', 'зажимать, зажать'],
['ash', 'пепел'],
['indeed', 'действительно, в самом деле'],
['dratted', 'проклятый'],
['to shriek', 'вопить, кричать на "s"'],
['spawn', 'потомство'],
['to rant', 'разглогольствовать, говорить с особой важностью'],
['to draw', 'втянуть'],
['to scuttle', 'удирать'],
['to get lend', 'получить взаймы'],
['outrage', 'безобразие'],
['urgently', 'срочно, неотложно'],
['to fade', 'увядать'],
['foghorn', 'сирена, горн'],
['curse', 'проклятие'],
['fosh', 'ерунда, на "f"'],
['to glare', 'свирепо смотреть (1 слово)'],
['to clench', 'сжимать, на "cl"'],
['sword', 'меч'],
['to flatten', 'сгладить, выравнивать'],
['to spear', 'пронзать'],
['codswallop', 'ерунда, на "c"'],
['to bide', 'выжидать'],
['to reckon', 'рассчитывать на что-то, 1 слово'],
['to blaze', 'сверкать, сиять, на "bl"'],
['to be clouted', 'быть затмённым'],
['toad', 'жаба'],
['wart', 'бородавка'],
['sorcerer', 'колдун'],
['to dread', 'опасаться'],
['to beam', 'сиять, на "be"'],
['crackpot', 'чокнутый'],
['to whirl', 'кружить, вертеть, на "w"'],
['firecracker', 'фейерверк, петарда'],
['squeal', 'визг'],
['spot', 'место'],
['to clasp', 'сцепить, сжать'],
['temper', 'характер'],
['to keen', 'сильно желать'],
['to expel', 'выгонять, исключать'],
['gamekeeper', 'егерь, лесник'],
['to wriggle', 'извиваться'],
['claw', 'коготь'],
['to scramble', 'карабкаться, на "s"'],
['to carry on', 'продолжать'],
['savage', 'свирепый, жестокий, на "s"'],
['bunch', 'кучка, связка (ключей)'],
['pellet', 'гранула'],
['pouch', 'сумка, мешок'],
['to tie', 'привязывать, завязывать'],
['to puncture', 'проколоть, на "pu"'],
['to mess with', 'возиться. связываться с кем-то'],
['to gleam', 'блестеть, на "gle"'],
['to settle down', 'расположиться'],
['enchantment', 'очарование, магия'],
['vault', 'подвал, погреб, на "v"'],
['prophet', 'пророк, прорицатель'],
['bungler', 'растяпа, плохой работник'],
['blimey', 'вот это да'],
['harbour', 'бухта'],
['to fold up', 'свернуть (газету)'],
['to clamber', 'карабкаться, на "c"'],
['to pant', 'запыхаться, тяжело дышать'],
['stitch', 'шов, стяжок'],
['to require', 'требоваться, нуждаться'],
['pointed', 'остроконечный, заостренный'],
['hide', 'шкура'],
['fastening', 'крепление'],
['fungi', 'грибы'],
['draft', 'проект'],
['couldron', 'котел'],
['pewter', 'оловянный, на "p"'],
['to get stuck', 'застрять'],
['bustling', 'шумный, суетливый'],
['halt', 'остановка'],
['leaky', 'дырявый'],
['grubby', 'неряшливый, неопрятный'],
['shabby', 'обшарпанный'],
['sherry', 'херес'],
['walnut', 'грецкий орех'],
['to buzz', 'жужжать'],
['chatter', 'болтовня, на "c"'],
['to buckle', 'согнуться, изгибаться на "bu"'],
['honour', 'честь'],
['to puff', 'затягиваться (сигаретой)'],
['scraping', 'скрежет'],
['to delight', 'восхищаться, на "d"'],
['to grasp', 'схватить, на "g"'],
['babble', 'лепет, бормотание на "b"'],
['cemetery', 'кладбище'],
['odd', 'странность'],
['to bump', 'врезаться, ударяться'],
['certain', 'определенный'],
['battlefield', 'поле боля'],
['to desert', 'покидать'],
['hostage', 'заложник'],
['loss', 'потеря'],
['vomit', 'тошнота'],
['despite', 'несмотря на'],
['minor', 'незначительный, на "m"'],
['percentage', 'процент, доля'],
['inning', 'подача (спорт)'],
['bulge', 'выпуклость'],
['to rebound', 'восстанавливаться'],
['evidence', 'доказательства'],
['disposable', 'одноразовый'],
['hitter', 'нападающий (спорт)'],
['snag', 'загвоздка'],
['authenticity', 'подлинность'],
['siccinct', 'кратко'],
['guilty', 'виновный'],
['to arch', 'выгнуть, прогнуться'],
['to strike out', 'вычеркнуть'],
['bothering', 'надоедающий'],
['to accomplish', 'выполнять, совершать на "a"'],
['cab', 'такси'],
['to fall apart', 'разваливаться'],
['to rescue', 'спасать'],
['catchphrase', 'ключевая фраза (лозунг)'],
['disadvantage', 'недостаток'],
['maintenance', 'обсоуживание, ремонт'],
['scuttlebutt', 'слухи, сплетни'],
['stroke of genius', 'гениальный ход'],
['streamer', 'плакат'],
['whorish', 'развратный'],
['to gamble', 'рисковать'],
['to flip a coin', 'бросить монетку'],
['vulnerable', 'уязвимый'],
['to giggle', 'хихикать, на "g"'],
['to appreciate', 'ценить, оценивать'],
['to condone', 'оправдывать, на "c"'],
['fraud', 'обман, мошенничество, на "f"'],
['accountant', 'бухгалтер'],
['chummy', 'дружелюбный, обаятельный'],
['tension', 'напряжение'],
['therefore', 'следовательно'],
['cerebral palsy', 'церебральный паралич'],
['generous', 'щедрый'],
['convalscence', 'выздоровление, восстановление'],
['issue', 'вопрос, проблема'],
['warehouse', 'склад'],
['downer', 'зануда'],
['effort', 'усилие'],
['to flaunt', 'щеголять, выставлять напоказ'],
['sizeable', 'значительный'],
['to betray', 'предавать'],
['valuable', 'ценный'],
['weed', 'сорняк'],
['bloke', 'парень. тип'],
['hag', 'ведьма'],
['above', 'выше'],
['cobble', 'булыжник (для мощения дороги)'],
['to twist', 'крутить, закручиваться, на "t"'],
['instantly', 'немедленно'],
['to hang', 'висеть'],
['plump', 'пухлый, упитанный'],
['hooting', 'уханье (крик совы)'],
['emporium', 'магазин'],
['barn', 'сарай, амбар'],
['to stack', 'складывать, на "s"'],
['barrel', 'бочка'],
['spleen', 'селезенка'],
['eel', 'угорь'],
['to totter', 'шататься'],
['to tower', 'возвышаться'],
['scarlet', 'алый'],
['to burnish', 'полировать'],
['swartly', 'смуглый'],
['to engrave', 'выгравировать'],
['to heed', 'внимать, учитывать'],
['greed', 'жадность'],
['dearly', 'дорого'],
['ledger', 'бухгалтерская книга'],
['to scatter', 'рассыпать'],
['to cram', 'впихивать, втискивать'],
['torch', 'факел'],
['steep', 'крутой (склон)'],
['railway track', 'рельсовая дорога'],
['to hurtle', 'мчаться, на "h"'],
['maze', 'лабиринт'],
['to sting', 'жалить'],
['to plunge', 'броситься, ринуться, на "p"'],
['to lean', 'опираться'],
['passage', 'коридор, проход'],
['to billow', 'вздыматься (дым)'],
['mound', 'насыпь, холм'],
['heap', 'куча, груда, на "h"'],
['to pile', 'сложить, на "p"'],
['ravine', 'овраг'],
['to trap', 'застять (в ловушке)'],
['squat', 'приземистый, коренастый'],
['mauve', 'лиловый, сиреневый'],
['to pin up', 'подкалывать (одежду при примерке)'],
['to drowl', 'растягивать (слова)'],
['rep', 'представитель'],
['mean', 'подлый'],
['generally', 'обычно'],
['feather', 'перо, на f"'],
['do you mind if', 'ты не будешь против, если...'],
['agreement', 'соглашение'],
['to appreciate', 'ценить'],
['grumpy', 'угрюмый, сердитый, на "g"'],
['to taunt', 'дразнить, насмехаться, на "t"'],
['spose', 'супруг'],
['toreplay', 'предварительные ласки'],
['seduction', 'соблазнение, искушение'],
['merely', 'просто, только, лишь'],
['cranky', 'капризный, эксцентричный'],
['circumstances', 'обстоятельства'],
['to chase out', 'выгонять'],
['to loom', 'виднеться, маячить'],
['mutually', 'взаимно'],
['delusion', 'заблуждение'],
['discourse', 'рассуждение'],
['to reciprocate', 'отвечать взаимностью'],
['overly', 'чрезмерно'],
['exedingly', 'настойчиво'],
['verbal', 'словестный, устный'],
['to stump', 'озадачить, поставить в тупик'],
['adjective', 'прилагательное'],
['boundaries', 'границы'],
['properiety', 'правильность'],
['misplace', 'терять'],
['utter', 'полнейший, абсолютный'],
['flood', 'наводнение, потоп'],
['once', 'однажды'],
['pity', 'жалость'],
['within', 'в течение'],
['to owe', 'быть должным'],
['gut', 'кишка'],
['unconditional', 'безусловный'],
['specimen', 'экземпляр, образец'],
['to long', 'тосковать'],
['to throb', 'пульсировать'],
['inconsistent', 'несоответствующий'],
['unsettle', 'расстраивать, тревожить'],
['gesture', 'жест'],
['to reconsider', 'пересмотреть'],
['purse', 'кошелек'],
['vague', 'смутный, туманный'],
['to condemn', 'осуждать, порицать'],
['valid', 'актуальный, действительный'],
['thoughtful', 'заботливый, внимательный'],
['arrange', 'организовывать'],
['to diminish', 'снижать, уменьшать'],
['rough', 'грубый, на "r"'],
['rug', 'коврик'],
['ally', 'союзник'],
['bellybutton', 'пупок'],
['to compound', 'составлять (смесь)'],
['to rid', 'избавляться'],
['to admit', 'признавать'],
['crotch', 'пах, ширинка'],
['to smuggle', 'провозить контрабандой'],
['to bully', 'запугивать, задирать'],
['servant', 'прислуга'],
['savage', 'дикарь'],
['to excuse', 'оправдываться'],
['to cheer up', 'развеселиться, взбодриться'],
['duffer', 'простофиля'],
['paving stones', 'брусчастка (словосочетание)'],
['postage stamp', 'марка'],
['to drag away', 'оттащить'],
['to bewitch', 'околдовать'],
['to befuddle', 'одурманить'],
['revenge', 'месть'],
['collapsible', 'складной, разборный'],
['to rot', 'гнить'],
['slimy', 'склизский, липкий'],
['to line', 'выстраивать (в линию)'],
['fang', 'клык'],
['snarled', 'запутанный'],
['horn', 'рог'],
['miniscule', 'крошечный'],
['to sneeze', 'чихать'],
['rustling', 'шелест, шуршание'],
['to peel', 'облезть, облупиться'],
['depth', 'глубина'],
['finkle', 'звон'],
['occure', 'случаться, возникать'],
['to prickle', 'покалывать'],
['gloom', 'мрак, темнота'],
['awkwardly', 'неловко'],
['willow', 'ива'],
['mahogany', 'красное дерево'],
['pliable', 'гибкий, пластичный, на "p"'],
['to reflect', 'отражаться'],
['armpit', 'подмышка'],
['core', 'ядро'],
['nostril', 'ноздря'],
['to flit', 'порхать'],
['to crumple', 'смять, скомкать'],
['beechwood', 'бук'],
['maple', 'клен'],
['whippy', 'гибкий, на "w"'],
['springy', 'упругий'],
['customer', 'покупатель'],
['to whoop', 'выкрикнуть'],
['to destine', 'предназначать (судьбой)'],
['to gawp', 'глазеть, на gaw"'],
['laden', 'нагруженный (чем-то тяжелым)'],
['mistress', 'любовница']
  ]

  let buttonCheck = document.querySelector('.check-btn');
  let word = document.querySelector('.rus_word');
  let buttonNext = document.querySelector('.next-btn');
  let comment = document.querySelector('.comment');
  let input = document.querySelector('.input');
  let engWord = document.querySelector('.eng_word');

  let correctCount = document.querySelector('.correct-count');
  let wrongCount = document.querySelector('.wrong-count');

function getRandomWord(words) { //выбирает рандомное слово на английском и передает его в код
  let randIndex = Math.floor(Math.random() * words.length);
  word.textContent = words[randIndex][1];
  engWord.textContent = words[randIndex][0];
  word.setAttribute('index', randIndex)
  return words[randIndex][0];
}

getRandomWord(words);
to();

function checkAnswer() { //провеяет соотвествие английского слова и поля ввода
  engWord.classList.remove('hidden')
  if (input.value.toLowerCase() === engWord.textContent) {
    comment.textContent = 'Success!';
    comment.classList.add('green');
    comment.classList.remove('red');
    correctCount.textContent = Number(correctCount.textContent) + 1;
    buttonCheck.setAttribute('disabled', '');
    buttonCheck.classList.add('disabled');
  }else{
    comment.textContent = 'Wrong :(';
    comment.classList.add('red');
    comment.classList.remove('green');
    wrongCount.textContent = Number(wrongCount.textContent) + 1;
    buttonCheck.setAttribute('disabled', '');
    buttonCheck.classList.add('disabled');
  }
}

function deleteWord () {
  const index = word.getAttribute('index');
words.splice(index, 1);
}

function to () {
  const word = engWord.textContent; 
if (word[0] === 't' && word[1] === 'o' && word[2] === ' ') {
  input.value = 'to '
}
}

buttonNext.addEventListener('click', function(){
  buttonCheck.removeAttribute('disabled');
  buttonCheck.classList.remove('disabled')
  if (comment.textContent === 'Success!') {
    deleteWord ()
  }
  
  if (input.value === '' || input.value === 'to ' && comment.textContent === 'Wrong :(') {
    wrongCount.textContent = Number(wrongCount.textContent) - 1;
  }

  if (input.value === '' || input.value === 'to ') {
    wrongCount.textContent = Number(wrongCount.textContent) + 1;
  }
  engWord.classList.add('hidden');
  comment.textContent = '';
  input.value = '';
  engWord.textContent = '';

  getRandomWord(words);
  to()
})

buttonCheck.addEventListener('click', function(){
  checkAnswer();
})

function pressEnter (evt) {
if (evt.key === 'Enter' && !buttonCheck.classList.contains('disabled')) {
  checkAnswer()
} else if(evt.key === 'Enter' && buttonCheck.classList.contains('disabled')) {
  buttonCheck.removeAttribute('disabled');
  buttonCheck.classList.remove('disabled')
  if (comment.textContent === 'Success!') {
    deleteWord ()
  }
  
  if (input.value === '' || input.value === 'to ' && comment.textContent === 'Wrong :(') {
    wrongCount.textContent = Number(wrongCount.textContent) - 1;
  }

  if (input.value === '' || input.value === 'to ') {
    wrongCount.textContent = Number(wrongCount.textContent) + 1;
  }
  engWord.classList.add('hidden');
  comment.textContent = '';
  input.value = '';
  engWord.textContent = '';

  getRandomWord(words);
  to()
}}

document.addEventListener('keydown', pressEnter)
