export const words1 = [
  /*
    ['daily', 'ежедневный'],
    ['courage', 'смелость'],
    ['affair', 'связь'],
    ['to involve', 'вовлекать'],
    ['to hold with', 'быть согласным с чем-то, поддерживать какую-то идею'],
    ['to expect', 'ожидать'],
    ['hardly', 'почти, едва, на "h"'],
    ['although', 'хотя, однако, на "alt"'],
    ['nearly', 'почти, на "n"'],
    ['to crane', 'вытягивать шею'],
    ['fence', 'забор'],
    ['to bear', 'выносить (плохую новость)'],
    ['to find out', 'выяснять, на "fin"'],
    ['to shudder to think', 'содрагаться от мысли'],
    ['to keep away', 'держаться подальше, на "k"'],
    ['dull', 'скучный, унылый'],
    ['to suggest', 'предлагать, на "s"'],
    ['to hum', 'урчать, напевать'],
    ['to pick up', 'подобрать, подвезти'],
    ['to wrestle', 'бороться, на "w"'],
    ['to notice', 'замечать (на "n")'],
    ['tawn', 'загорелый'],
    ['tawny', 'коричневатый'],
    ['to flutter', 'трепетать'],
    ['to peck', 'клевать'],
    ['briefcase', 'портфель'],
    ['tantrum', 'истерика'],
    ['to chortle', 'усмехнуться, на "c"'],
    ['to back out', 'покидать, отступать, на "b"'],
    ['sign', 'знак'],
    ['peculiar', 'специфичный, своеобразный'],
    ['to jerk', 'дернуть'],
    ['tabby', 'полосатый'],
    ['trick', 'уловка, трюк, на "t"'],
    ['toward', 'в направлении'],
    ['edge', 'край чего-то'],
    ['traffic jam', 'дорожная пробка'],
    ['cloak', 'плащ'],
    ['get-ups', 'прически'],
    ['to suppose', 'предполагать, на "s"'],
    ['steering wheel', 'руль машины'],
    ['huddle', 'кучка, на "h"'],
    ['weirdos', 'чудаки'],
    ['to enrage', 'приводить в ярость'],
    ['struck', 'пораженный, на "str", 6 букв'],
    ['stunt', 'трюк, фокус, на "s"'],
    ['obviously', 'очевидно (вводное слово)'],
    ['to swoop', 'налетать'],
    ['in broad daylight', 'средь бела дня'],
    ['to gaze', 'пристально глядеть'],
    ['to speed overhead', 'проноситься над головой'],
    ['however', 'однако'],
    ['bun', 'булочка, пучок'],
    ['to stretch legs', 'размять ноги'],
    ['uneasy', 'беспокойный'],
    ['tin', 'олово, жестяная банка, на "t"'],
    ['to stop dead', 'остановиться как вкопанный'],
    ['to flood', 'наводнить, затопить'],
    ['to clutch', 'хватать, на "c"'],
    ['to dash', 'ринуться, броситься, на "das"'],
    ['to snap', 'щелкнуть, огрызнуться'],
    ['to seize', 'схватить, на "se"'],
    ['almost', 'почти, на "a"'],
    ['to dial', 'набирать номер'],
    ['receiver', 'приемник (емкость)'],
    ['to stroke', 'поглаживать'],
    ['to blame', 'винить, на "b"'],
    ['to walk straight into', 'идти прямо в...'],
    ['to grunt', 'хрюкать'],
    ['to stumble', 'спотыкаться, на "s"'],
    ['to knock on the ground', 'повалить на землю'],
    ['on the contrary', 'с другой стороны'],
    ['wide', 'широкий'],
    ['squeaky', 'визгливый, писклявый'],
    ['passers by', 'прохожие'],
    ['to rejoice', 'ликовать'],
    ['rattle', 'грохот, хрип, скрежет, на "ra"'],
    ['to spot', 'замечать (на "s")'],
    ['stern', 'суровый, на "st"'],
    ['to wonder', 'задаваться вопросом'],
    ['to let into', 'впустить в...'],
    ['to determine', 'определять, обуславливать'],
    ['unable', 'не в состоянии'],
    ['pattern', 'шаблон, образец'],
    ['to grin', 'скалить зубы'],
    ['oddly', 'странно'],
    ['downpour', 'ливень'],
    ['until', 'до того момента'],
    ['folks', 'ребята'],
    ['all over the place', 'повсюду'],
    ['throat', 'горло'],
    ['lately', 'недавно, в последнее время'],
    ['sharp', 'острый'],
    ['sharply', 'резко'],
    ['to mumble', 'бормотать (на "mum")'],
    ['to purse', 'поджимать, морщить, на "p"'],
    ['to dare', 'oсмеливаться, посметь'],
    ['stiffly', 'чопорно'],
    ['common', 'распространенный, общий'],
    ['heart sinking', 'сердце замирает'],
    ['to creep', 'ползать'],
    ['to peer', 'всматриваться'],
    ['to relate', 'относиться, рассказывать'],
    ['to yawn', 'завать'],
    ['to affect', 'влиять'],
    ['to slam', 'захлопывать, хлопнуть, швырнуть'],
    ['neither, nor', 'ни, ни'],
    ['to twitch', 'дергаться, дрогнуть, на "t"'],
    ['to narrow', 'сужаться'],
    ['judging by', 'судя по...'],
    ['to tuck', 'подгибать, заправлять'],
    ['robe', 'халат, на "r"'],
    ['to sweep', 'подметать, проноситься'],
    ['high-heeled', 'на высоком каблуке'],
    ['buckle', 'пряжка, застежка'],
    ['as though', 'как будто'],
    ['spectacles', 'очки'],
    ['crook', 'согнутый, на "c"'],
    ['to rummage', 'рыться'],
    ['for some reason', 'по какой-то причине'],
    ['to chuckle', 'посмеиваться'],
    ['to mutter', 'бормотать, на "mut"'],
    ['it seem to be', 'кажется, это...'],
    ['to flick', 'щелкнуть, на "f"'],
    ['heady', 'опрометчивый, безрассудный'],
    ['pavement', 'тротуар'],
    ['to slip', 'скользить (4 буквы), подсунуть'],
    ['to set off', 'отправляться'],
    ['fancy', 'причудливый, фантазия'],
    ['rather', 'скорее (вводное слово)'],
    ['severe', 'суровый, на "se"'],
    ['to ruffle', 'взъерошить'],
    ['distinctly', 'отчетливо, внятно'],
    ['dozen', 'дюжина'],
    ['to sniff', 'нюхать'],
    ['impatiently', 'нетерпеливо'],
    ['to be bound to', 'обязательно (словосочетание)'],
    ['bound', 'связанный'],
    ['i will bet', 'могу поспорить...'],
    ['precious', 'бесценный. драгоценный'],
    ['to swap', 'обмениваться'],
    ['downright', 'явно'],
    ['careless', 'беспечный, неосторожный'],
    ['sideway glance', 'косой взгляд (словосочетание)'],
    ['very day', 'тот самый день (словосочетание)'],
    ['surely', 'конечно'],
    ['to persuade', 'убеждать, на "p"'],
    ['proper', 'правильный'],
    ['nonsense', 'чепуха, на "n"'],
    ['to flinch', 'вздрагивать, на "f"'],
    ['exasperate', 'раздраженный'],
    ['to admire', 'восхищаться, на "a"'],
    ['to flatter', 'льстить, быть польщенным'],
    ['noble', 'благородный'],
    ['to blush', 'краснеть'],
    ['earmuffs', 'наушники'],
    ['anxious', 'тревожный, озадаченный'],
    ['to pierce', 'прокалывать'],
    ['piercing stare', 'пронзительный взгляд'],
    ['plain', 'простой'],
    ['however', 'однако'],
    ['drop', 'леденец, капля'],
    ['to turn up', 'оказаться'],
    ['to bow', 'кланяться'],
    ['bow', 'лук (оружие)'],
    ['to gasp', 'дышать с трудом (одно слово)'],
    ['to pat on', 'похлопать по..., на "p"'],
    ['to reach out', 'дотянуться'],
    ['to tremble', 'дрожать, на "tr"'],
    ['somehow', 'как-то'],
    ['to nod', 'кивать'],
    ['glum', 'угрюмый'],
    ['to falter', 'запинаться'],
    ['to astound', 'поражать (astonish)'],
    ['in the name of heaven', 'во имя небес'],
    ['handkerchief', 'носовой платок'],
    ['lace', 'кружево'],
    ['to pull out', 'вытаскивать'],
    ['to dab', 'вытирать, на "d"'],
    ['beneath', 'под'],
    ['to examine', 'исследовать, изучать, на "e"'],
    ['though', 'хотя, впрочем, на "t"'],
    ['firm', 'твердый'],
  ['firmly', 'твердо'],
  ['to be able to', 'быть способным сделать что-то'],
  ['faint', 'слабый'],
  ['faintly', 'слабо'],
  ['to swallow', 'глотать'],
  ['wise', 'мудрый'],
  ['to trust with', 'доверить что-либо (словосочетание)'],
  ['grudgingly', 'неохотно'],
  ['tend to', 'склонный к...'],
  ['rumble', 'грохот, на "ru"'],
  ['steadly', 'непрерывно'],
  ['headlight', 'фара'],
  ['roar', 'рев'],
  ['to swell', 'набухать, возрастать'],
  ['astride', 'верхом'],
  ['to allow', 'позволять'],
  ['tangle', 'клубок, спутанный клубок'],
  ['dustbin', 'мусорный ящик'],
  ['lid', 'крышка'],
  ['bushy', 'густой'],
  ['vast', 'крупный, обширный, огромный, на "v"'],
  ['bundle', 'сверток, комплект, набор'],
  ['blanket', 'одеяло'],
  ['to relieve', 'облегчать, освобождать'],
  ['to borrow', 'одалживать (получать)'],
  ['to lend', 'одалживать (отдавать)'],
  ['to swarm', 'кишеть, толпиться, на "s"'],
  ['to bend', 'сгибаться, на "b"'],
  ['fast asleep', 'крепко уснуть'],
  ['tuft', 'пучок (не прическа)'],
  ['jet-black', 'угольно-черный'],
  ['forehead', 'лоб'],
  ['curiously', 'любопытно'],
  ['to get over with', 'покончить с...'],
  ['scratchy', 'колючий, на "sc"'],
  ['whiskery', 'усатый'],
  ['to howl', 'выть'],
  ['to wound', 'ранить, на "w"'],
  ['to hiss', 'шипеть'],
  ['to sob', 'всхлипывать'],
  ['to get a grip', 'собраться, взять себя в руки'],
  ['grip', 'захват'],
  ['gingerly', 'осторожно'],
  ['to twinkle', 'мерцать, на "t"'],
  ['to muffle', 'глушить, заглушить'],
  ['stream', 'течение, поток'],
  ['to wipe', 'вытирать (на "w")'],
  ['engine', 'двигатель'],
  ['to blow nose', 'высморкаться'],
  ['to make out', 'разобрать, различить'],
  ['to slink', 'красться, проскальзывать, на "s"'],
  ['to murmur', 'ворчать, шептать'],
  ['heel', 'каблук'],
  ['swish', 'шелест, взмах, на "s"'],
  ['neat', 'аккуратный'],
  ['ink', 'чернила'],
  ['to prod', 'токать, подгонять (на "p")'],
  ['to pinch', 'зажимать, щипать'],
  ['hush', 'тишина, молчание'],
  ['to vanish', 'исчезать'],
  ['brass', 'латунь, латунный'],
  ['mantelpiece', 'каминная полка'],
  ['to bobble', 'бурлить'],
  ['on a roundabout at the fair', 'на карусели на ярмарке'],
  ['not for long', 'ненадолго'],
  ['shrill', 'пронзительный'],
  ['to rap on', 'стучать в... (на "r")'],
  ['to screech', 'визжать'],
  ['cooker', 'кухонная плита'],
  ['pan', 'кастрюля'],
  ['frying pan', 'сковорода'],
  ['to demand', 'требовать'],
  ['to groan', 'стонать'],
  ['cupboard', 'буфет, чулан'],
  ['punch bag', 'боксерская груша'],
  ['knobbly', 'бугристый, на "k"'],
  ['sellotape', 'скотч'],
  ['by the way of', 'посредством (словосочетание)'],
  ['to comb', 'причесываться'],
  ['put together', 'вместе взятые'],
  ['rest of', 'остальная часть'],
  ['thick', 'толстый'],
  ['smooth', 'гладкий'],
  ['wig', 'парик'],
  ['in case', 'в случае'],
  ['to scent', 'чуять'],
  ['to grab', 'захватывать, хватать (на "g", 4 буквы)'],
  ['parcel', 'посылка, сверток'],
  ['tyke', 'дворняжка, грубиян'],
  ['to unwrap', 'разворачивать'],
  ['to rip', 'рвать'],
  ['to leap', 'скакать, вскочить, на "l"'],
  ['ought', 'должен'],
  ['slug', 'слизень'],
  ['for a change', 'для разнообразия'],
  ['to snarl', 'рычать, на "s"'],
  ['to blow up', 'взрываться'],
  ['to screw up face', 'скривить лицо'],
  ['to wail', 'вопить, на "w"'],
  ['to spoil', 'портить'],
  ['to fling', 'бросать, кидать (на "f")'],
  ['gap', 'пробел'],
  ['frantically', 'неистово, отчаянно'],
  ['scrawny', 'тощий, на "s"'],
  ['at once', 'сразу же'],
  ['aside', 'в сторону'],
  ['fringe', 'челка'],
  ['baggy', 'мешковатый'],
  ['however', 'однако'],
  ['to shear', 'срезать, стричь'],
  ['to force', 'заставлять, навязывать'],
  ['to revolt', 'бунтовать, восставать, на "rev"'],
  ['puppet', 'марионетка, на "p"'],
  ['revolting', 'отвратительный'],
  ['glove puppet', 'кукла, которая надевается на руку'],
  ['to shrink', 'сокращаться, уменьшаться, съеживаться'],
  ['relief', 'облегчение'],
  ['to punish', 'наказывать'],
  ['to chase', 'преследовать'],
  ['chimney', 'дымоход'],
  ['headmistress', 'директриса'],
  ['bin', 'мусорное ведро'],
  ['to complain', 'жаловаться'],
  ['to overtake', 'обогнать, на "ov"'],
  ['hoodlums', 'хулиганы'],
  ['beetroot', 'свекла'],
  ['to snig', 'хихикать (на "s", 4 буквы)'],
  ['van', 'фургон'],
  ['remarkably', 'в высшей степени'],
  ['either', 'тоже'],
  ['to scratch', 'царапать'],
  ['afterwards', 'в последствии'],
  ['lit', 'освещенный'],
  ['to slither', 'скользить (7 букв)'],
  ['to wrap', 'заворачивать, оборачивать'],
  ['glistening', 'блестящий'],
  ['to whin', 'скулить'],
  ['to budge', 'сдвинуться с места'],
  ['to tap', 'постучаться, на "t"'],
  ['to order', 'приказывать, заказывать'],
  ['knuckle', 'сустав пальца'],
  ['smartly', 'ловко (придумать, найти решение)'],
  ['to snooze', 'дремать'],
  ['to shuffle', 'шаркать, тасовать, перестанавливать'],
  ['tank', 'резервуар'],
  ['boredom', 'скука'],
  ['hummer', 'молоток'],
  ['at least', 'по крайней мере, в конце концов'],
  ['beady', 'как бусинки'],
  ['to wink', 'подмигивать'],
  ['ceiling', 'потолок'],
  ['vigorously', 'решительно, энергично, на "v"'],
  ['to jab', 'тыкать (на "j")'],
  ['to breed', 'разводить'],
  ['deafening', 'оглушительный'],
  ['to waddle', 'ковылять, на "w"'],
  ['concrete', 'бетон'],
  ['caught by surprise', 'застанный врасплох'],
  ['to constrict', 'сжимать на "co"'],
  ['to uncoil', 'размотать'],
  ['throughout', 'повсюду (на "t")'],
  ['to slide', 'сколькзить (5 букв)'],
  ['swift', 'быстрый'],
  ['to gibber', 'невнятно бормотать'],
  ['to squeeze', 'сжимать, протиснуться, на "s"'],
  ['managed to', 'суметь что-то, смочь,t на "m"'],
  ['to collapse', 'разрушиться'],
  ['to strain', 'напрягать'],
  ['to forbid', 'запретить, на "f"'],
  ['to rush out', 'выбежать (словосочетание)'],
  ['to wave', 'махать'],
  ['merrily', 'радостно'],
  ['boa', 'удав (на "b")'],
  ['constrictor', 'удав (на "c")'],
  ['crutches', 'костыли'],
  ['to wander', 'бродить, на "w"'],
  ['ray', 'луч'],
  ['comprehensive', 'всесторонний'],
  ['to stuff', 'засовывать, на "stu"'],
  ['to trip', 'споткнуться (на "t")'],
  ['to fond', 'любить'],
  ['to smelt', 'плавить, выплавлять'],
  ['maroon', 'темно-бордовый'],
  ['tailcoat', 'фрак'],
  ['knickerbockers', 'бриджи'],
  ['flat', 'плоский'],
  ['straw', 'солома, соломинка'],
  ['boater', 'лодочник'],
  ['gruff', 'грубо'],
  ['to burst', 'взрываться, ворваться (5 букв)'],
  ['to burst into tears', 'разразиться слезами'],
  ['tub', 'ванная, бадья'],
  ['rag', 'тряпка'],
  ['bowl', 'чаша'],
  ['to dye', 'красить'],
  ['to argue', 'спорить'],
  ['to wrinkle', 'морщить, на "w"'],
  ['to bang', 'ударить, стункнуть (на "b")'],
  ['to flop', 'провалиться'],
  ['doormat', 'коврик перед дверью'],
  ['to poke', 'тыкать'],
  ['to dodge', 'изворачиваться, увернуться'],
  ['envelope', 'конверт'],
  ['yellowish', 'желтоватый, на "y"'],
  ['parchment', 'пергамент'],
  ['seal', 'печать'],
  ['coat of arms', 'герб'],
  ['eagle', 'орел'],
  ['badger', 'барсук'],
  ['to hand', 'передать'],
  ['to flip', 'перевернуть, на "f"'],
  ['to snort', 'фыркнуть'],
  ['whelk', 'щенок'],
  ['to unfold', 'раскрывать, на "u"'],
  ['to snatch', 'хватать, на "sn"'],
  ['to sneer', 'насмехаться, на "s", 5 букв'],
  ['to glance', 'взглянуть'],
  ['to choke', 'задыхаться'],
  ['to croak', 'квакать'],
  ['scruff', 'загривок'],
  ['promptly', 'быстро, на "p"'],
  ['to dangle', 'свисать'],
  ['crack', 'трещина, щель'],
  ['to quiver', 'дрожать, на "q"'],
  ['to pace', 'шагать, расхаживать, на "p"'],
  ['to stamp out', 'уничтножить (словосочетание)'],
  ['to swap', 'менять'],
  ['rifle', 'винтовка'],
  ['bent', 'изогнутый, погнутый (4 буквы)'],
  ['to bawl', 'орать, на "b"'],
  ['to sigh', 'вздыхать'],
  ['on purpose', 'нарочно, намеренно'],
  ['to whack', 'бить, колотить, на "w"'],
  ['tortoise', 'черепашка'],
  ['greenhouse', 'теплица'],
  ['to strangle', 'душить, на "str"'],
  ['to wheeze', 'хрипеть'],
  ['to tread', 'топтать, наступить, на "tre"'],
  ['squashy', 'мягкий'],
  ['lap', 'колени'],
  ['to tear', 'рвать, оторвать, на "t"'],
  ['to nail up', 'заколачивать гвоздями'],
  ['to slot', 'прорезать'],
  ['to board up', 'заколачивать досками'],
  ['to tiptoe', 'ходить на цыпочках'],
  ['to shred', 'измельчать'],
  ['dairy', 'молочный, сыроварня'],
  ['to spread', 'распространять'],
  ['to whiz', 'свистеть, просвистеть'],
  ['to pelt', 'сыпаться, бросать'],
  ['waist', 'талия'],
  ['to bounce', 'подпрыгивать, отскакивать'],
  ['wrench', 'гаечный ключ'],
  ['to wrench', 'вывернуть, раскрутить гайки'],
  ['whenever', 'всякий раз, когда...'],
  ['nightfall', 'сумерки, на "n"'],
  ['to blow up', 'взрываться'],
  ['gloomy', 'мрачный'],
  ['outskirts', 'окраина, на "o"'],
  ['damp', 'сырой'],
  ['musty', 'затхлый'],
  ['stale', 'несвежий'],
  ['tinned', 'консервированный'],
  ['dining-room', 'столовая'],
    ['outta', 'из'],
  ['flame', 'пламя'],
  ['purge', 'очистка'],
  ['basement', 'подвал, на "b"'],
  ['boozer', 'пьяница'],
  ['fiend', 'изверг, злодей'],
  ['to itch', 'зудеть'],
  ['gruesome', 'ужасный, отвратительный (на "g")'],
  ['denial', 'отказ, отрицание'],
  ['seem to', 'кажется, что...'],
  ['stake', 'кол'],
  ['to pop', 'хлопнуть'],
  ['peak', 'пик'],
  ['to represent', 'представлять (шоу)'],
  ['threat', 'угроза'],
  ['to crowl', 'красться, на "c"'],
  ['just so', 'просто чтобы...'],
  ['disregard', 'пренебрежение'],
  ['handful', 'горсть'],
  ['do not get me wrong', 'не пойми меня неправильно (без апострофа)'],
  ['to convince', 'убеждать, на "c"'],
  ['insecure', 'небезопасный'],
  ['unconfident', 'неуверенный'],
  ['it does not make sense', 'это не имеет смысла, главное слово на "s"'],
  ['to doubt', 'сомневаться'],
  ['pervert', 'извращенец'],
  ['stubborn', 'упрямый'],
  ['frugal', 'бережливый, экономный'],
  ['skam', 'мошенничество, на "s"'],
  ['funeral', 'похроны'],
  ['desperation', 'безысходность, отчаяние'],
  ['hilarious', 'веселый'],
  ['to supply', 'поставлять (продукцию)'],
  ['to downsize', 'сократить, на "d"'],
  ['advantage', 'преимущество'],
  ['theft', 'кража'],
  ['margin', 'прибыль'],
  ['misconduct', 'проступок'],
  ['gross', 'суммарный, брутто, на "g"'],
  ['severance pay', 'выходное пособие'],
  ['inventory', 'инвентарь'],
  ['barely', 'едва (на "b")'],
  ['expenses', 'расходы'],
  ['godfather', 'крестный отец'],
  ['goofy', 'бестолковый'],
  ['to attend', 'посещать, на "a"'],
  ['scrubs', 'заросли'],
  ['to sue', 'подать иск'],
  ['to confess', 'признаваться, на "c"'],
  ['to encourage', 'поощерять'],
  ['male', 'самец, мужчина'],
  ['splash', 'всплеск'],
  ['sissy', 'неженка, маменькин сынок'],
  ['inch', 'дюйм'],
  ['subconscious', 'подсознание'],
  ['ailment', 'недуг'],
  ['to frazzle', 'вымотать, измотать, на "f"'],
  ['to overstate', 'преувеличивать'],
  ['stiff', 'жесткий, твердый, на "s"'],
  ['to bleed', 'кровоточить'],
  ['stain', 'пятно, 5 букв'],
  ['harmful', 'вредный'],
  ['to stick', 'вставлять, на "sti"'],
  ['to insert', 'вставлять, на "i"'],
  ['fluid', 'жидкость'],
  ['needle', 'игла'],
  ['to branch out', 'разъеденться (словосочетание)'],
  ['to attach', 'прикреплять, пристегнуть, привязаться морально, на "a"'],
  ['to pronounce', 'объявить, на "p"'],
  ['to declare', 'объявить, на "d"'],
  ['already', 'уже'],
  ['wind', 'дыхание, на "w"'],
  ['insurance', 'страховка'],
  ['renal failer', 'почечная недостаточность'],
  ['autopsy', 'вскрытие трупа'],
  ['to scratch off', 'соскребать с...'],
  ['diversity', 'разнообразие'],
  ['to mandate', 'уполномочить'],
  ['punch', 'удар'],
  ['sturdy', 'крепкий, на "s"'],
  ['consumer', 'потребитель'],
  ['content', 'довольный'],
  ['retaliation', 'возмездие'],
  ['for some reason', 'по какой-то причине'],
  ['commission', 'поручение'],
  ['ignorance', 'невежество'],
  ['to arise', 'возникать, на "a"'],
  ['permission', 'разрешение'],
  ['to steer away', 'держаться подальше, на "s"'],
  ['familiar', 'ознакомленный'],
  ['to reenact', 'воспроизвести'],
  ['outcome', 'исход'],
  ['to account', 'объяснять, на "a"'],
  ['to butcher', 'убивать, на "b"'],
  ['acronym', 'аббревиатура'],
  ['harm', 'вред, на "h"'],
  ['supernatural', 'сверхъестесственный'],
  ['trauma', 'травма'],
  ['to avenge', 'мстить'],
  ['envy', 'зависть'],
  ['joint', 'совместный'],
  ['to pledge', 'обязаться, пообещать'],
  ['candidly', 'откровенно, на "c"'],
  ['to advance', 'продвигать'],
  ['advanced', 'продвинутый'],
  ['awareness', 'осведомленность'],
  ['terms', 'условия, правила'],
  ['to embarrass', 'смущать, на "e"'],
  ['to regret', 'сожалеть'],
  ['truly', 'действительно, на "t"'],
  ['to insult', 'оскорблять, на "i"'],
  ['to abandon', 'покидать, оставлять, на "a"'],
  ['lame', 'убогий'],
  ['to lame', 'калечить, на "l"'],
  ['offensive', 'обидно'],
  ['to squat', 'присесть, сесть на корточки'],
  ['cornerstone', 'камень преткновения'],
  ['tape', 'лента, на "t"'],
  ['to lead', 'вести что-либо или куда-либо'],
  ['to get down business', 'приступить к делу'],
  ['connotation', 'значение'],
  ['term', 'термин'],
  ['beside', 'рядом, на "b"'],
  ['to treat', 'лечить, относиться, трактовать'],
  ['sparks', 'искры'],
  ['versus', 'против, на "v"'],
  ['to percolate', 'просачиваться, проникать, на "perc"'],
  ['loan', 'займ'],
  ['to stir', 'размешивать, на "s"'],
  ['further', 'в дальнейшем'],
  ['convenient', 'удобный'],
  ['minority', 'меньшенство'],
  ['to redo', 'переделывать'],
  ['heist', 'ограбление'],
  ['entrepreneur', 'предприниматель'],
  ['against', 'против, на "a"'],
  ['to run', 'управлять, на "r"'],
  ['profitable', 'прибыльный'],
  ['unemployed', 'безработный'],
  ['to seek en employment', 'искать работу'],
  ['to apply for a job', 'подать заявление на работу'],
  ['to turn down the offer', 'отклонить предложение, на "t"'],
  ['to accept the offer', 'принять предложение'],
  ['to reject the offer', 'отклонить предложение, на "r"'],
  ['either, or', 'или, или'],
  ['to recruit', 'завербовать'],
  ['double shift', 'двойная смена'],
  ['to transfer', 'переводить (в другой отдел)'],
  ['to promote', 'повышать'],
  ['department', 'отдел'],
  ['to demote', 'понижать'],
  ['in 5 years', 'через 5 лет'],
  ['suburb', 'пригород'],
  ['by then', 'к тому времени'],
  ['sober', 'трезвый'],
  ['head', 'начальник, на "h"'],
  ['expertise', 'компетенция'],
  ['strengths', 'сильные стороны'],
  ['goal-oriented', 'целеустремленный'],
  ['eager', 'жаждущий'],
  ['responsible', 'ответственный'],
  ['to be passionate to', 'испытывать страсть к...'],
  ['weakness', 'слабость, на "w"'],
  ['kidney', 'почка'],
  ['to justify', 'оправдать, на "j"'],
  ['redemption', 'искупление'],
  ['to reply', 'отвечать, на "rep"'],
  ['to get acquainted', 'знакомиться'],
  ['at all costs', 'любой ценой'],
  ['engagement', 'помолвка'],
  ['do not quite get you', 'не вполне тебя понял'],
  ['to propose', 'предлагать, на "p"'],
  ['for a while', 'на некоторое время'],
  ['to figure out', 'выяснять, на "fig"'],
  ['it does not add up', 'это не имеет смысла, главное слово на "a"'],
  ['to clear up', 'прояснить'],
  ['to suss out', 'раскусить'],
  ['to check out', 'проверить'],
  ['wiener', 'сарделька'],
  ['ladder', 'лестница, на "l"'],
  ['to cuddle', 'обнимать, прижимать'],
  ['to be in good terms', 'быть в хороших отношениях'],
  ['sacrifice', 'жертва, на "s"'],
  ['rage', 'ярость'],
  ['evident', 'очевидный (наречие)'],
  ['to gather', 'собирать(ся), на "g"'],
  ['customs', 'таможня'],
  ['to delay', 'задерживаться, на "d"'],
  ['due', 'по причине (одно слово)'],
  ['to proceed', 'проследовать'],
  ['just browse', 'просто смотреть'],
  ['spade', 'лопата, 5 букв'],
  ['fiance', 'жених'],
  ['gift-wrapped', 'подарочная упаковка'],
  ['to decline', 'отклонять, на "d"'],
  ['insufficient', 'недостаточный, неудовлетворительный'],
  ['funds', 'средства'],
  ['scarcely', 'едва, на "s"'],
  ['fare', 'плата за проезд'],
  ['plaster', 'гипс, штукатурка'],
  ['puddles', 'лужи'],
  ['to steer', 'управлять, на "s"'],
  ['superb', 'великолепный. на "su"'],
  ['remarkable', 'замечательно. на "r"'],
  ['to assume', 'предполагать, на "a"'],
  ['janitor', 'дворник'],
  ['humble', 'скромный'],
  ['attitude', 'отношение, жизненная позиция, на "a"'],*/

  ['occasionally', 'иногда, на "o"', "'I call him occasionally to ask about you'", "occasionally"],
  ['to tease', 'дразнить', "His sisters were very kind, but never bothered to tease him", "tease"],
  ['for instance', 'например', "'Let's take you for instance Sister Antonia: are you a good person?'", "for instance"],
  ['to phrase', 'формулировать', "'I just think you need to be careful how you phrase things,sir'", "phrase"],
  ['jock', 'качок', "A jock with manicured nails, too tight of pants, and he drives a 20-year-old muscle car", "jock"],
  ['chart', 'диаграмма', "'Well,you don't get $90 trillion, but the chart says that's what it's worth'", "chart"],
  ['to tattle', 'болтать', "'I think we've established that you don't like tattling'", "tattling"],
  ['to respond', 'отликаться, отвечать', "Before they could respond, a sea of blue police lights and sirens erupted at the bottom of the hill", "respond"],
  ['ramification', 'разветвление, развилка', "'Debating the geopolitical ramifications of bioengineering?'", "ramifications"],
  ['whiny', 'плаксивый', "'Yeah, because no one wants to buy their whiny music, they gotta give it away for free'", "whiny"],
  ['squabble', 'перебранка, ссора', "'Ladies and gentlemen, I apologize for the disturbance, but what's a Mikaelson family party without a little squabble?'", "squabble"],
  ['to drag', 'тащить, тянуть', "'Bind him, chain him, drag him to the nearest police-station!'", "drag"],
  ['bunch', 'кучка, связка', "The little bunch of curious and sympathizing people around the body kept changing all the time", "bunch"],
  ['malcontent', 'недовольный', "'I don't know who, some malcontent who has just enough information to sound knowledgeable and do serious damage'", "malcontent"],
  ['slope', 'склон', "Once more they set out to climb the slope of the mountain", "slope"],
  ['slippery', 'скользкий', "Then, violently, his body rolled, causing Langdon to lose his grip on the slippery chains", "slippery"],
  ['to suture', 'зашить, сшить', "'If I don't suture this wound, it will become infested with bacteria'", "suture"],
  ['lapdog', 'собачонка', "'I WAS ALWAYS HIS BEST FRIEND UNTIL YOU TURNED HIM INTO A LAPDOG'", "LAPDOG"],
  ['freckles', 'веснушки', "He was tall, thin and gangling, with freckles, big hands and feet and a long nose", "freckles"],
  ['to hang out with', 'тусоваться с...', "'We don't want to hang out with any more dudes'", "hang out with"],
  ['surgeon', 'хирург', "Watching him, Eve thought with amusement: 'No one would ever guess what a brilliant surgeon he is'", "surgeon"],
  ['tricky', 'хитрый', "'Well, he's a tricky son of a bitch, that's how'", "tricky"],
  ['plague', 'зараза, чума', "The bezoar, that was found in the heart of the Arabian deer, was a cure that could cure the plague", "plague"],
  ['grace', 'изящество, милосердие', "Despite his beauty, his grace and his ease of manner, Michael remained a cold lover", "grace"],
  ['ligament', 'связка, сухожилие', "'I'd just torn a ligament or something'", "ligament"],
  ['to braid', 'заплетать (волосы)', "'Braid each other's hair and ride horseback on the beach?'", "Braid"],
  ['cushion', 'подушка (диванная)', "A single wand lay on a faded purple cushion in the dusty window", "cushion"],
  ['to plop', 'шлепнуться', "First drops plopped on the ground out of the riven sky", "plopped"],
  ['to bust', 'разориться',"Ever since that mall went bust, half the town is out of work", "bust"],
  ['to hop off', 'спрыгнуть', "They hop off the buses and begin the ancient practice of begging for food", "hop off"],
  ['to go ahead', 'идти вперед', "'I'll go ahead, check out the tunnel, make sure it's clear'", "go ahead"],
  ['renewal', 'обновление', "'It is a journey of spiritual renewal where one receive strength from the earth and becomes inseparable from it'", "renewal"],
  ['acceptance', 'принятие', "'It's the best gift I can give to you on your 21st birthday - my friendship and unconditional acceptance'", "acceptance"],
  ['enema', 'клизма', "'I went into labour naturally, but had the routine shave and enema - very unpleasant'", "enema"],
  ['conviction', 'убеждение, взгляды, на "c"', "Once a man had been her beau, she never lost the conviction that he belonged to her", "conviction"],
  ['dazzling', 'ослепительный', "He was strapped into a chair surrounded by dials, under dazzling lights", "dazzling"],
  ['in advance', 'заранее', "'I never knew in advance where my journeys in time would take me'", "in advance"],
  ['marvellous', 'чудесный, на "m"', "He emptied the suitcases once again, and once again they were filled with the marvellous gifts of the sea", "marvellous"],
  ['timid', 'робкий, трусливый', "'Wouldn’t it be better just to go home, dear?' Aunt Petunia suggested timidly", "timidly"],
  ['to plough', 'пахать (поле)', "The same thing happened in the middle of a ploughed field and halfway across a suspension bridge", "ploughed"],
  ['suspension', 'висячий, подвисной', "The same thing happened in the middle of a ploughed field and halfway across a suspension bridge", "suspension"],
  ['to snivel', 'хныкать, на "s"', "Great drops beat on the roof of the car. Dudley snivelled", "snivelled"],
  ['hanger', 'вешалка', "Last year, the Dursleys had given him a coat-hanger and a pair of Uncle Vernon’s old socks.", "-hanger"],
  ['to perch', 'усесться, взгромоздиться', "Perched on top of the rock was the most miserable little shack you could imagine", "Perched"],
  ['shack', 'лачуга, на "s"', "Perched on top of the rock was the most miserable little shack you could imagine", "shack"],
  ];
  