export const words2 = [
  ['gleefully', 'ликующе', "‘Storm forecast for tonight!’ said Uncle Vernon gleefully, clapping his hands together", "gleefully"],
  ['below', 'ниже', "A toothless old man pointed at an old rowing boat bobbing in the iron-grey water below them", "below"],
  ['to amble up', 'подниматься неторопливой походкой', "A toothless old man came ambling up to them, pointing at an old rowing boat", "ambling up"],
  ['wicked', 'злой, на "w"', "A toothless old man pointed, with a rather wicked grin, at an old rowing boat", "wicked"],
  ['to row', 'грести', "'I can still row and you will throw the net'", "row"],
  ['to whip', 'стегать, хлестать', "Icy sea spray and rain crept down their necks and a chilly wind whipped their faces", "whipped"],
  ['seaweed', 'водоросли', "The inside was horrible; it smelled strongly of seaweed, the wind whistled through the gaps in the wooden walls", "seaweed"],
  ['ration', 'рацион, пища', "'I’ve already got us some rations,' said Uncle Vernon, 'so all aboard!'", "rations"],
  ['to shrivel', 'съеживаться, на "s"', "He tried to start a fire but the empty crisp packets just smoked and shrivelled up", "shrivelled"],
  ['cheerful', 'жизнерадостный', "'Could do with some of those letters now, eh?' he said cheerfully", "cheerfully"],
  ['filthy', 'грязный', "Fierce wind rattled the filthy windows", "filthy"],
  ['to splatter', 'плескаться, брызгаться', "Spray from the high waves splattered the walls of the hut", "splattered"],
  ['hut', 'хижина, на "h"', "Spray from the high waves splattered the walls of the hut", "hut"],
  ['fierce', 'свирепый, неистовый, на "fi"'],
  ['mouldy', 'заплесневелый', "Aunt Petunia found a few mouldy blankets in the second room and made up a bed for Dudley", "mouldy"],
  ['to curl up', 'свернуться калачиком', "Harry was left to curl up under the thinnest blanket", "curl up"],
  ['lumpy', 'бугристый, на "l"', "She and Uncle Vernon went off to the lumpy bed next door", "lumpy"],
  ['ferocious', 'свирепый, на "fe"', "The storm raged more and more ferociously as the night went on", "ferociously"],
  ['to shiver', 'дрожать, на "s"', "He shivered and turned over, trying to get comfortable, his stomach rumbling with hunger", "shivered"],
  ['to drown', 'тонуть', "Dudley’s snores were drowned by the low rolls of thunder that started near midnight", "drowned"],
  ['dial', 'циферблат', "The lighted dial of Dudley’s watch told Harry he’d be eleven in ten minutes’ time", "dial"],
  ['to creak', 'скрипеть', "Harry heard something creak outside. He hoped the roof wasn’t going to fall in", "creak"],
  ['to crumble', 'крошиться, разрушаться', "Was the rock crumbling into the sea?", "crumbling"],
  ['cannon', 'пушка', "‘Where’s the cannon?’ he said stupidly", "cannon"],
  ['to skid', 'заносить (на поворотах), скользить', "There was a crash behind them and Uncle Vernon came skidding into the room", "skidding"],
  ['to warn', 'предупреждать', "‘Who’s there?’ he shouted. ‘I warn you – I’m armed!’", "warn"],
  ['to arm', 'вооружать', "‘Who’s there?’ he shouted. ‘I warn you – I’m armed!’", "armed"],
  ['force', 'сила', "The door was hit with such force that it swung clean off its hinges", "force"],
  ['hinge', 'дверная петля', "The door was hit with such force that it swung clean off its hinges", "hinges"],
  ['to glint', 'сверкать, на "gl"', "But you could make out his eyes, glinting like black beetles under all the hair", "glinting"],
  ['mane', 'грива', "His face was almost completely hidden by a long, shaggy mane of hair", "mane"],
  ['shaggy', 'лохматый', "His face was almost completely hidden by a long, shaggy mane of hair", "shaggy"],
  ['to stoop', 'сутулиться, на "st"', "The giant squeezed his way into the hut, stooping so that his head just brushed the ceiling", "stooping"],
  ['astride', 'верхом', "If the motorbike was huge, it was nothing to the man sitting astride it", "astride"],
  ['to budge up', 'подвинуться', "‘Budge up, yeh great lump,’ said the stranger", "Budge up"],
  ['lump', 'кусок, глыба, шишка от удара', "A troll even larger than the one they had tackled, out cold with a bloody lump on its head", "lump"],
  ['to crouch', 'скорчиться, прегнуться', "He ran to hide behind his mother, who was crouching, terrified, behind Uncle Vernon", "crouching"],
  ['rasp', 'скрежет, на "r"', "You can’t see a door on stage but you hear the rasp of a key in a lock", "rasp"],
  ['knot', 'узел', "He bent gun into a knot as easily as if it had been made of rubber", "knot"],
  ['summat', 'кое-что', "I've got summat for you here – I mighta sat on it at some point, but it’ll taste all right", "summat"],
  ['sligh', 'незначтельный, на "s"', "From an inside pocket of his black overcoat he pulled a slightly squashed box", "slightly"],
  ['to squash', 'раздавить', "From an inside pocket of his black overcoat he pulled a slightly squashed box", "squashed"],
  ['to rub', 'тереть', "'What about that tea then, eh?' he said, rubbing his hands together", "rubbing"],
  ['to bend down', 'наклониться вниз', "He bent down over the fireplace", "bent down"],
  ['flicker', 'вспышка, мерцание', "It filled the whole damp hut with flickering light", "flickering"],
  ['to sink', 'погрузиться (в воду), тонуть, провисать', "Said Hagrid, sitting back down on the sofa, which groaned and sank even lower", "sank"],
  ['stat', 'статистика', "'We're basing this decision on a stat'", "stat"],
  ['sacred', 'священный, на "s"', "The thoughts of historical spirits suddenly made Rachel realize what a sacred place this room was", "sacred"],
  ['to provide', 'обеспечивать', "These permanent holes in the ice provide seafood throughout the winter for birds", "provide"],
  ['directly', 'непосредственно, напрямую', "The alarms connect directly to the police station", "directly"],
  ['in a way', 'в некотором смысле', "I lacked humility, in a way I aspired to be God", "humility"],
  ['acupuncture', 'иглоукалывание', "'She's going to see if acupuncture will improve the circulation to my dad's brain'", "acupuncture"],
  ['assignment', 'назначение, распределение, инструкции на "as"', "Because I've got an important assignment for you", "assignment"],
  ['tough', 'жесткий, сильный, на "t"', "They could usually shoot well, knew the value of obeying an order, and they were tough", "tough"],
  ['temporary', 'временный', "He suffered temporary full-body paralysis and full movement was never restored", "temporary"],
  ['strike', 'удар, на "s"', "He came to sitting on the ground and waited for the knife to strike him", "strike"],
  ['to groom', 'холить, ухаживать', "'Why would any man dress well, groom himself and lift weights just to sleep with other men?'", "groom"],
  ['to slash', 'хлестать, рубить, на "s"', "'I slashed wildly at any part of the filthy body that presented itself'", "slashed"],
  ['benefit', 'выгода, превилегия', "Was it a mistake or are we friends with benefits?", "benefits"],
  ['unless', 'до тех пор, пока; если не', "'I wouldn't murder you tonight; unless, perhaps, I set the house on fire: but that's as my fancy goes'", "unless"],
  ['harsh', 'суровый, на "h"', "he had been slapped by his mother for the first time and had heard her voice raised at him in harsh words", "harsh"],
  ['to coddle', 'няньчиться, баловать', "'I should be ashamed to coddle myself as you do!'", "coddle"],
  ['to deduct', 'вычитать', "You pay a certain percentage, which you deduct from your trading account", "deduct"],
  ['to swamp', 'заливать, затопить', "Though bay completely swamped, the boat was nearly unharmed", "swamped"],
  ['memo', 'памятка, заметка', "'She's even send a memo telling us not to speak with the reporters'", "memo"],

/*
  ['superior', 'начальник, вышестоящий'],
  ['to be in charge in', 'быть ответственным за'],
  ['to pick', 'выбирать'],
  ['inappropriate', 'неподходящий, неуместный, на "in"'],
  ['fortune', 'состояние (деньги)'],
  ['to decrease', 'сокращаться, уменьшаться (численно)'],
  ['specific', 'конкретный'],
  ['pathetic', 'жалкий, убогий, на "p"'],
  ['knob', 'дверная ручка'],
  ['pile', 'куча, стопка, на "p"'],
  ['to invent', 'изобретать, выдумывать'],
  ['troop', 'отряд, на "t"'],
  ['shaft', 'шахта'],
  ['to thrive', 'процветать'],
  ['felon', 'преступник, на "f"'],
  ['to forge', 'подделывать'],
  ['to accuse', 'обвинять, на "a"'],
  ['to perpetrate', 'совершать, на "p"'],
  ['carefully', 'внимательно'],
  ['entirely', 'полностью'],
  ['for cristes sake', 'ради Бога'],
  ['option', 'вариант'],
  ['to submit', 'предоставлять (информацию)'],
  ['to forfeit', 'утратить'],
  ['to refer', 'ссылаться (на что-то), обращаться к кому-то, направлять'],
  ['terrific', 'потрясающе, на "t"'],
  ['to expire', 'истекать (срок годности)'],
  ['judgemental', 'склонный к осуждению'],
  ['to sag', 'провисать, обвисать'],
  ['kettle', 'чайник (для кипячения)'],
  ['teapot', 'чайник (для завариваия)'],
  ['mug', 'кружка'],
  ['to chip', 'откалывать, отколоть'],
  ['amber', 'янтарь, янтарный'],
  ['swig', 'глоток, на "s"'],
  ['to sizzle', 'шипеть, шкварчать'],
  ['poker', 'кочерга, шампур'],
  ['to fitjet', 'ёрзать, на "f"'],
  ['gulp', 'глоток, на "g"'],
  ['to cower', 'съёжиться, на "c"'],
  ['to growl', 'рычать, на "g"'],
  ['pale', 'бледный'],
  ['to bewilder', 'недоумевать, сбивать с толку'],
  ['syllable', 'слог'],
  ['to quail', 'дрогнуть, испугаться'],
  ['deputy', 'заместитель'],
  ['to stammer', 'заикаться, на "sta"'],
  ['quill', 'перо, игла животного, на "q"'],
  ['to scribble', 'нацарапать, начеркать'],
  ['beak', 'клюв'],
  ['to clamp', 'зажимать, зажать, на "clam"'],
  ['ash', 'пепел'],
  ['indeed', 'действительно, в самом деле, на "i"'],
  ['dratted', 'проклятый, на "d"'],
  ['to shriek', 'вопить, кричать на "s"'],
  ['spawn', 'потомство'],
  ['to rant', 'разглогольствовать, говорить с особой важностью'],
  ['to draw', 'втянуть, вытащить, привлекать'],
  ['to scuttle', 'удирать'],
  ['to get lend', 'получить взаймы'],
  ['outrage', 'безобразие'],
  ['urgently', 'срочно, неотложно'],
  ['to fade', 'увядать'],
  ['foghorn', 'сирена, горн'],
  ['curse', 'проклятие'],
  ['fosh', 'ерунда, на "f"'],
  ['to glare', 'свирепо смотреть (1 слово)'],
  ['to clench', 'сжимать, на "cle"'],
  ['sword', 'меч'],
  ['to flatten', 'сгладить, выравнивать, на "f"'],
  ['to spear', 'пронзать, нанизывать'],
  ['codswallop', 'ерунда, на "c"'],
  ['to bide', 'выжидать'],
  ['to reckon', 'рассчитывать на что-то, считать (думать) 1 слово'],
  ['to blaze', 'сверкать, сиять, на "bl"'],
  ['to be clouted', 'быть затмённым'],
  ['toad', 'жаба'],
  ['wart', 'бородавка'],
  ['sorcerer', 'колдун'],
  ['to dread', 'опасаться'],
  ['to beam', 'сиять, на "be"'],
  ['crackpot', 'чокнутый'],
  ['to whirl', 'кружить, вертеть, на "w"'],
  ['firecracker', 'фейерверк, петарда'],
  ['squeal', 'визг'],
  ['spot', 'место'],
  ['to clasp', 'сцепить, сжать, на "clas"'],
  ['temper', 'характер'],
  ['to keen', 'сильно желать, увлекаться'],
  ['to expel', 'выгонять, исключать'],
  ['gamekeeper', 'егерь, лесник'],
  ['to wriggle', 'извиваться'],
  ['claw', 'коготь'],
  ['to scramble', 'карабкаться, на "s"'],
  ['to carry on', 'продолжать'],
  ['savage', 'свирепый, жестокий, на "s"'],
  ['bunch', 'кучка, связка (ключей)'],
  ['pellet', 'гранула'],
  ['pouch', 'сумка, мешок'],
  ['to tie', 'привязывать, завязывать'],
  ['to puncture', 'проколоть, на "pu"'],
  ['to mess with', 'возиться. связываться с кем-то'],
  ['to gleam', 'блестеть, на "gle"'],
  ['to settle down', 'расположиться'],
  ['enchantment', 'очарование, магия'],
  ['vault', 'подвал, погреб, на "v"'],
  ['prophet', 'пророк, прорицатель'],
  ['bungler', 'растяпа, плохой работник'],
  ['blimey', 'вот это да'],
  ['harbor', 'бухта'],
  ['to fold up', 'свернуть (газету)'],
  ['to clamber', 'карабкаться, на "c"'],
  ['to pant', 'запыхаться, тяжело дышать'],
  ['stitch', 'шов, стяжок'],
  ['to require', 'требоваться, нуждаться'],
  ['pointed', 'остроконечный, заостренный, 7 букв'],
  ['hide', 'шкура'],
  ['fastening', 'крепление'],
  ['fungi', 'грибы'],
  ['draft', 'проект'],
  ['cauldron', 'котел'],
  ['pewter', 'оловянный, на "p"'],
  ['to get stuck', 'застрять, словосочетание'],
  ['bustling', 'шумный, суетливый, на "b"'],
  ['halt', 'остановка'],
  ['leaky', 'дырявый'],
  ['grubby', 'неряшливый, неопрятный, на "g"'],
  ['shabby', 'обшарпанный, на "s"'],
  ['sherry', 'херес'],
  ['walnut', 'грецкий орех'],
  ['to buzz', 'жужжать'],
  ['chatter', 'болтовня, на "c"'],
  ['to buckle', 'согнуться, пристегнуть на "bu"'],
  ['honour', 'честь, честный человек'],
  ['to puff', 'пыхтеть, затягиваться (сигаретой)'],
  ['scraping', 'скрежет, на "s"'],
  ['to delight', 'восхищаться, на "d"'],
  ['to grasp', 'схватить, на "g", 5 букв'],
  ['babble', 'лепет, бормотание на "b"'],
  ['cemetery', 'кладбище'],
  ['odd', 'странность'],
  ['to bump', 'врезаться, ударяться'],
  ['certain', 'определенный'],
  ['battlefield', 'поле боля'],
  ['to desert', 'покидать, на "d"'],
  ['hostage', 'заложник'],
  ['loss', 'потеря'],
  ['vomit', 'тошнота'],
  ['despite', 'несмотря на'],
  ['minor', 'незначительный, на "m"'],
  ['percentage', 'процент, доля'],
  ['inning', 'подача (спорт)'],
  ['bulge', 'выпуклость'],
  ['to rebound', 'восстанавливаться'],
  ['evidence', 'доказательства'],
  ['disposable', 'одноразовый'],
  ['hitter', 'нападающий (спорт)'],
  ['snag', 'загвоздка'],
  ['authenticity', 'подлинность'],
  ['succinct', 'кратко'],
  ['guilty', 'виновный'],
  ['to arch', 'выгнуть, прогнуться'],
  ['to strike out', 'вычеркнуть'],
  ['bothering', 'надоедающий'],
  ['to accomplish', 'выполнять, совершать, достигать на "a"'],
  ['cab', 'такси'],
  ['to fall apart', 'разваливаться'],
  ['to rescue', 'спасать'],
  ['catchphrase', 'ключевая фраза (лозунг)'],
  ['disadvantage', 'недостаток'],
  ['maintenance', 'обсоуживание, ремонт'],
  ['scuttlebutt', 'слухи, сплетни'],
  ['stroke of genius', 'гениальный ход'],
  ['streamer', 'плакат'],
  ['whorish', 'развратный'],
  ['to gamble', 'рисковать'],
  ['to flip a coin', 'бросить монетку'],
  ['vulnerable', 'уязвимый'],
  ['to giggle', 'хихикать, на "g"'],
  ['to appreciate', 'ценить, оценивать, на "a"'],
  ['to condone', 'оправдывать, на "c"'],
  ['fraud', 'обман, мошенничество, на "f"'],
  ['accountant', 'бухгалтер'],
  ['chummy', 'дружелюбный, обаятельный'],
  ['tension', 'напряжение'],
  ['therefore', 'следовательно'],
  ['cerebral palsy', 'церебральный паралич'],
  ['generous', 'щедрый'],
  ['convalescence', 'выздоровление, восстановление'],
  ['issue', 'вопрос, проблема'],
  ['warehouse', 'склад, на "w"'],
  ['downer', 'зануда'],
  ['effort', 'усилие'],
  ['to flaunt', 'щеголять, выставлять напоказ'],
  ['sizeable', 'значительный'],
  ['to betray', 'предавать'],
  ['valuable', 'ценный, 8 букв'],
  ['weed', 'сорняк'],
  ['bloke', 'парень. тип'],
  ['hag', 'ведьма'],
  ['above', 'выше'],
  ['cobble', 'булыжник (для мощения дороги)'],
  ['to twist', 'крутить, закручиваться, на "t"'],
  ['instantly', 'немедленно'],
  ['to hang', 'висеть'],
  ['plump', 'пухлый, упитанный'],
  ['hooting', 'уханье (крик совы)'],
  ['emporium', 'магазин'],
  ['barn', 'сарай, амбар'],
  ['to stack', 'складывать, на "s"'],
  ['barrel', 'бочка, на "b"'],
  ['spleen', 'селезенка'],
  ['eel', 'угорь'],
  ['to totter', 'шататься'],
  ['to tower', 'возвышаться'],
  ['scarlet', 'алый'],
  ['to burnish', 'полировать'],
  ['swartly', 'смуглый'],
  ['to engrave', 'выгравировать'],
  ['to heed', 'внимать, учитывать'],
  ['greed', 'жадность'],
  ['dearly', 'дорого'],
  ['ledger', 'бухгалтерская книга'],
  ['to scatter', 'рассыпать'],
  ['torch', 'факел'],
  ['steep', 'крутой (склон)'],
  ['railway track', 'рельсовая дорога'],
  ['to hurtle', 'мчаться, на "h"'],
  ['maze', 'лабиринт'],
  ['to sting', 'жалить'],
  ['to plunge', 'броситься, окунаться, на "p"'],
  ['to lean', 'опираться'],
  ['passage', 'коридор, проход'],
  ['to billow', 'вздыматься (дым)'],
  ['mound', 'насыпь, холм'],
    ['heap', 'куча, груда, на "h"'],
    ['to pile', 'сложить, нагромоздить, на "p"'],
    ['ravine', 'овраг'],
    ['to trap', 'застять (в ловушке), поймать в ловушку'],
    ['squat', 'приземистый, коренастый'],
    ['mauve', 'лиловый, сиреневый'],
    ['to pin up', 'подкалывать (одежду при примерке)'],
    ['to drowl', 'растягивать (слова)'],
    ['mean', 'подлый, злой'],
    ['generally', 'обычно'],
    ['feather', 'перо, на f"'],
    ['do you mind if', 'ты не будешь против, если...'],
    ['agreement', 'соглашение'],
    ['grumpy', 'угрюмый, сердитый, на "g"'],
    ['to taunt', 'дразнить, насмехаться, на "ta"'],
    ['spose', 'супруг'],
    ['toreplay', 'предварительные ласки'],
    ['seduction', 'соблазнение, искушение'],
    ['merely', 'просто, только, лишь'],
    ['cranky', 'капризный, эксцентричный'],
    ['circumstances', 'обстоятельства'],
    ['to chase out', 'выгонять'],
    ['to loom', 'виднеться, маячить'],
    ['mutually', 'взаимно'],
    ['delusion', 'заблуждение'],
    ['discourse', 'рассуждение'],
    ['to reciprocate', 'отвечать взаимностью'],
    ['overly', 'чрезмерно'],
    ['exeedingly', 'чрезвычайно, крайне, на "e"'],
    ['verbal', 'словестный, устный'],
    ['to stump', 'озадачить, поставить в тупик, ковылять'],
    ['adjective', 'прилагательное'],
    ['boundaries', 'границы'],
    ['properiety', 'правильность'],
    ['misplace', 'терять'],
    ['utter', 'полнейший, абсолютный'],
    ['flood', 'наводнение, потоп'],
    ['once', 'однажды'],
    ['pity', 'жалость'],
    ['to owe', 'быть должным'],
    ['gut', 'кишка'],
    ['unconditional', 'безусловный'],
    ['specimen', 'экземпляр, образец'],
    ['to long', 'тосковать'],
    ['to throb', 'пульсировать'],
    ['inconsistent', 'несоответствующий'],
    ['to unsettle', 'расстраивать, тревожить'],
    ['gesture', 'жест'],
    ['to reconsider', 'пересмотреть, на "rec"'],
    ['purse', 'кошелек'],
    ['vague', 'смутный, туманный'],
    ['to condemn', 'осуждать, порицать, на "cond"'],
    ['valid', 'актуальный, действительный'],
    ['thoughtful', 'заботливый, внимательный, на "t"'],
    ['to arrange', 'организовывать, расставлять, упорядочить'],
    ['to diminish', 'снижать, уменьшать'],
    ['rough', 'грубый, на "ro"'],
    ['rug', 'коврик'],
    ['ally', 'союзник'],
    ['bellybutton', 'пупок'],
    ['to compound', 'составлять (смесь)'],
    ['to rid', 'избавляться'],
    ['crotch', 'пах, ширинка, на "c"'],
    ['to smuggle', 'провозить контрабандой'],
    ['to bully', 'запугивать, задирать'],
    ['servant', 'прислуга'],
    ['savage', 'дикарь'],
    ['to excuse', 'оправдываться'],
    ['to cheer up', 'развеселиться, взбодриться'],
    ['duffer', 'простофиля'],
    ['paving stones', 'брусчастка (словосочетание)'],
    ['postage stamp', 'марка'],
    ['to drag away', 'оттащить'],
    ['to bewitch', 'околдовать'],
    ['to befuddle', 'одурманить'],
    ['revenge', 'месть'],
    ['collapsible', 'складной, разборный'],
    ['to rot', 'гнить'],
    ['slimy', 'склизский, липкий'],
    ['to line', 'выстраивать (в линию)'],
    ['fang', 'клык'],
    ['snarled', 'запутанный'],
    ['horn', 'рог'],
    ['minuscule', 'крошечный'],
    ['to sneeze', 'чихать'],
    ['rustling', 'шелест, шуршание, на "r"'],
    ['to peel', 'облезть, облупиться'],
    ['depth', 'глубина'],
    ['finkle', 'звон'],
    ['to occur', 'случаться, возникать, на "o"'],
    ['to prickle', 'покалывать'],
    ['gloom', 'мрак, темнота'],
    ['awkwardly', 'неловко'],
    ['willow', 'ива'],
    ['mahogany', 'красное дерево'],
    ['pliable', 'гибкий, пластичный, на "p"'],
    ['to reflect', 'отражаться'],
    ['armpit', 'подмышка'],
    ['core', 'ядро'],
    ['nostril', 'ноздря'],
    ['to flit', 'порхать'],
    ['to crumple', 'смять, скомкать, на "cru"'],
    ['beechwood', 'бук'],
    ['maple', 'клен'],
    ['whippy', 'гибкий, на "w"'],
    ['springy', 'упругий'],
    ['customer', 'покупатель'],
    ['to whoop', 'выкрикнуть'],
    ['to destine', 'предназначать (судьбой)'],
    ['to gawp', 'глазеть, на gaw"'],
    ['laden', 'нагруженный (чем-то тяжелым)'],
    ['mistress', 'любовница'],
    ['improvement', 'улучшение'],
    [' a while', 'через некоторое время'],
    ['to hoover', 'пылесосить'],
    ['to pin', 'приколоть'],
    ['quiz', 'викторина'],
    ['howling', 'вопиющий, на "h"'],
    ['to dump', 'сваливать (в кучу)'],
    ['to wheel', 'катить'],
    ['term', 'срок, период'],
    ['to strand', 'застрять, на "s"'],
    ['to swing around', 'развернуться, словосочетание'],
    ['to hammer', 'стучать, долбить'],
    ['divide', 'деление, разделение'],
    ['rucksack', 'рюкзак'],
    ['briskly', 'бодро, резво'],
    ['gangling', 'неуклюжий, нескладный'],
    ['to jostle', 'толкать, на "j"'],
    ['to drift', 'проплывать, парить, на "d"'],
    ['disgruntle', 'недовольство'],
    ['carriage', 'вагон'],
    ['compartment', 'отсек, камера, купе'],
    ['to shove', 'совать, толкать, пихать'],
    ['to chorus', 'говорить хором'],
    ['badge', 'значок'],
    ['prefect', 'староста'],
    ['fondly', 'нежно, ласково'],
    ['to goggle', 'выпучивать глаза, пялиться'],
    ['to blurt', 'выпаливать (речь), на "b"'],
    ['load', 'груз, поклажа'],
    ['to voice', 'выпаливать, озвучивать, на "v"'],
    ['clatter', 'топот'],
    ['dimpled', 'с ямочками на щеках'],
    ['pastie', 'пирожок'],
    ['corned', 'соленый, засоленный'],
    ['to flow', 'течь, струиться'],
    ['to consider', 'считать, учитывать, рассматривать (на должность)'],
    ['currently', 'в настоящий момент'],
    ['circumcision', 'обрезание'],
    ['curtains', 'шторы'],
    ['range', 'диапазон'],
    ['suitable', 'подходящий, на "s"'],
    ['maiden name', 'девичья фамилия'],
    ['urgent', 'срочный, неотложный'],
    ['aftermath', 'последствия'],
    ['to injure', 'ранить, на "i"'],
    ['jaw', 'челюсть'],
    ['to vouch on', 'поручиться за…'],
    ['foreman', 'мастер цеха, бригадир'],
    ['warranty', 'гарантия'],
    ['to chicken out', 'струсить'],
    ['to grumble', 'ворчать, на "gru"'],
    ['slayer', 'убийца, истребитель'],
    ['schedule', 'график, расписание, на "s"'],
    ['flouncy', 'волнистый'], 
    ['posse', 'отряд, на "p"'],
    ['first aid kit', 'аптечка первой помощи'],
    ['to forward', 'пересылать, рассылать'],
    ['defence', 'защита; оборона'], 
    ['to foul', 'нарушать правила'],
    ['foul', 'нарушение'],
    ['flagrant', 'вопиющий, чудовищный, на "f"'],
    ['to prevent', 'предотвращать, на "p"'],
    ['affirmative', 'утвердительный (ответ)'],
    ['incentive', 'стимулирующий'],
    ['to reward', 'награждать'],
    ['outstanding', 'выдающийся'], 
    ['torture', 'пытка'],
    ['vendor', 'продавец'],
    ['to infiltrate', 'просачиваться, проникать, на "i"'],
    ['henhouse', 'курятник, на "h"'],
    ['lass', 'девушка'],
    ['decisiveness', 'решительность, на "dec"'],
    ['to hesitate', 'колебаться, медлить'],
    ['addict', 'пристрастие'],
    ['to interact', 'взаимодействовать'],
    ['origin', 'происхождение'],
    ['bead', 'бусина'],
    ['sequins', 'блестки'],
    ['fallback', 'отступление, на "f"'],
    ['divine', 'святой, божественный, на "d"'],
    ['to guzzle', 'жадно пить/есть'],
    ['to bust', 'обанкротиться, разориться'],
    ['to pry', 'любопытствовать, выведывать'],
    ['to tempt', 'искушать, соблазнять, на "t"'],
    ['nearby', 'поблизости'],
    ['inferior', 'подчиненный, на "i"'],
    ['favour', 'одолжение, благосклонность'],
    ['festive', 'праздничный, торжественный'],
    ['in order', 'в порядке, по порядку'],
    ['imperative', 'обязательный, на "i"'],
    ['to head back', 'возвращаться'],
    ['to grab a coffee', 'захватить кофе (с собой)'],
    ['accidentally', 'случайно'],
    ['annual', 'ежгодный'],
    ['award', 'награда'],
    ['recognition', 'признание (всеобщее), узнавание'],
    ['wreck', 'авария, катастрофа'],
    ['cocky', 'самоуверенный, дерзкий'],
    ['bling', 'боеск, на "b"'],
    ['skillet', 'сковорода, на "s"'],
    ['stage', 'этап'],
    ['footage', 'отснятый материал'],
    ['camcorder', 'видеокамера'],
    ['to tape', 'снимать на камеру'],
    ['defacement', 'порча (имущества)'],
    ['highness', 'величество, высочество'],
    ['to descend', 'спускаться, сходить'],
    ['serf', 'крепостной (раб)'],
    ['validation', 'подтверждение, одобрение'],
    ['loosely', 'свободно, вольно'],
    ['to come across', 'столкнуться (буквально)'],
    ['to ban', 'запрещать, на "b"'],
    ['repercussion', 'отголосок (последствия)'],
    ['announcement', 'объявление'],
    ['cord', 'шнур, провод'],
    ['host', 'хозяин'],
    ['to spill', 'пролить'],
    ['beaver', 'бобер'],
    ['horny', 'возбужденный'],
    ['concern', 'беспокойство'],
    ['stickler', 'приверженец, сторонник'],
    ['bower', 'игрок'],
    ['stink', 'вонь, на "sti"'],
    ['seizure', 'приступ, припадок'],
    ['apparently', 'вероятно'],
    ['concussion', 'сотрясение мозга'],
    ['harassment', 'издевательство, оскорбление'],
    ['priest', 'священник, жрец'],
    ['forward', 'рассылка'],
    ['queer', 'странный, необычный, на "q"'],
    ['to resign', 'уходить в отставку'],
    ['breathalyser', 'алкотестер'],
    ['suspense', 'неизвестность, неопределенность'],
    ['trait', 'черта характера'],
    ['to scrutinize', 'тщательно изучать'],
    ['to interrupt', 'прерывать, на "interr"'],
    ['to insist', 'настаивать, на "i"'],
    ['mutiny', 'бунт'],
    ['intent', 'намерение, умысел'],
    ['irrelevant', 'неуместный, неважный, на "ir"'],
    ['albeit', 'хотя, на "alb"'],
    ['to avoid', 'избегать'],
    ['to disclose', 'раскрывать, на "d"'],
    ['to settle a bet', 'заключить пари'],
    ['hypocrite', 'лицемер'],
    ['thong', 'ремень, на "t"'],
    ['to agitate', 'агитировать'],
    ['to associate', 'связывать, ассоциировать'],
    ['witty', 'остроумный'],
    ['attorney', 'адвокат'],
    ['boner', 'стояк'],
    ['to stay put', 'оставаться на месте, на "sta"'],
    ['bogey', 'пугало, приведение'],
    ['sprout', 'росток'],
    ['to nibble', 'грызть, обгрызать'],
    ['tearful', 'заплаканный'],
    ['to poke out', 'высовываться, на "p"'],
    ['taken aback', 'застанный врасплох, на "t"'],
    ['daisy', 'маргаритка'],
    ['mellow', 'мягкий, сочный'],
    ['by heart', 'наизусть'],
    ['stunned', 'ошеломленный, на "s", 7 букв'],
    ['to stun', 'оглушать, ошеломлять'],
    ['daze', 'изумление, ошеломление, на "d"'],
    ['dud', 'подделка, недействительный'],
    ['to settle', 'обосноваться, уладить'],
    ['whiskers', 'усы'],
    ['dumbfound', 'ошарашенный, на "d"'],
    ['finer point', 'нюанс, тонкость'],
    ['thickset', 'коренастый'],
    ['coolly', 'невозмутимо, хладнокровно'],
    ['tinge', 'оттенок'],
    ['riff-ruff', 'сброд'],
    ['to lurk', 'скрываться, прятаться'],
    ['to scowl', 'хмуриться, на "s"'],
    ['sniffy', 'презрительно'],
    ['to race', 'мчаться, бегать, на "r"'],
    ['trainers', 'кроссовки'],
    ['to echo', 'вторить, повторять'],
    ['to cram', 'втискивать, напихивать, на "c"'],
    ['throng', 'толпиться'],
    ['path', 'тропа'],
    ['starry', 'звездный'],
    ['turret', 'башня'],
    ['fleet', 'флот'],
    ['to glide', 'скользить, на "g"'],
    ['cliff', 'утес, скала'],
    ['pebble', 'галька'],
    ['oak', 'дуб'],
    ['blissfully', 'блаженно, облегченно, на "b"'],
    ['to fit', 'помещаться'],
    ['staircase', 'парадная лестница'],
    ['to flag', 'помечать'],
    ['to drone', 'гудеть, бубнить, на "d"'],
    ['shortly', 'вскоре'],
    ['within', 'внутри, в течение'],
    ['dormitory', 'общежитие, спальный корпус'],
    ['to smarten', 'прихорошиться'],
    ['to linger', 'задерживать (взгляд), на "l"'],
    ['to smudge', 'пачкаться'],
    ['jolt', 'толчок'],
    ['doom', 'погибель'],
    ['to stream', 'литься, проноситься'],
    ['transparent', 'прозрачный'],
    ['to glide', 'скользить. на "g"'],
    ['monk', 'монах, старец'],
    ['tights', 'трико, колготы'],
    ['splendid', 'великолепно, на "sp"'],
    ['to lay table', 'накрыть на стол'],
    ['goblet', 'кубок (посуда)'],
    ['to come to a halt', 'остановиться'],
    ['lantern', 'фонарь'],
    ['to dot', 'усеивать'],
    ['among', 'среди, на "amo"'],
    ['mainly', 'в основном, на "m"'],
    ['upwards', 'вверх'],
    ['stool', 'табуретка'],
    ['four-legged', 'четвероногий'],
    ['patch', 'заплатка, клочок'],
    ['to fray', 'износить'],
    ['brim', 'край, на "b"'],
    ['rip', 'разрыв, буквальный'],
    ['bowler', 'котелок, на "b"'],
    ['sleek', 'гладкий. элегантный'],
    ['to dwell', 'обитать, жить'],
    ['daring', 'отважный, смелый, на "d"'],
    ['nerve', 'смелость, наглость, на "n"'],
    ['chivalry', 'рыцарство'],
    ['to toil', 'усиленно трудиться'],
    ['wit', 'остроумие, смекалка'],
    ['to join', 'присодиниться'],
    ['to jog', 'бегать трусцой'],
    ['amid', 'среди, на "ami"'],
    ['gale', 'шторм, буря'],
    ['to swagger', 'важно расхаживать'],
    ['plenty', 'множество, масса'],
    ['properly', 'надлежащим образом'],
    ['recognise', 'узнавать'],
    ['pompously', 'напыщенно'],
    ['scroll', 'свиток'],
    ['uncertainly', 'неуверенно'],
    ['chop', 'отбивная'],
    ['gravy', 'подливка'],
    ['peas', 'горох'],
    ['miffed', 'обиженный'],
    ['in a row', 'подряд (словосочетание)'],
    ['unbearable', 'невыносимый'],
    ['rural', 'сельский, деревенский'],
    ['compassionate', 'сострадательный'],
    ['assertive', 'настойчивый, убедительный, на "a"'],
    ['affectionate', 'проявляющий привязанность'],
    ['possessive', 'собственнический'],
    ['posses', 'обладать, иметь'],
    ['considerate', 'внимательный к кому-то, на "c"'],
    ['reliable', 'надежный (человек)'],
    ['affordable', 'доступный (по деньгам)'],
    ['spacious', 'просторный'],
    ['attic', 'чердак'],
    ['desirable', 'желанный, желательный'],
    ['turquoise', 'бирюзовый'],
    ['navy', 'морской (цвет)'],
    ['to take a nap', 'вздремнуть (словосочетание)'],
    ['stock', 'склад, запас, на "s"'],
    ['to humiliate', 'унижать, оскорблять, на "h"'],
    ['to revive', 'возрождать'],
    ['paper clip', 'скрепка'],
    ['representative', 'представитель'],
    ['to rely on', 'полагаться на, на "r"'],
    ['arrangement', 'расположение, размещение'],
    ['courtesy', 'вежливость, учтивость'],
    ['honorable', 'почетный'],
    ['whiner', 'нытик'],
    ['sanctuary', 'храм, святилище'],
    ['eternal', 'вечный'],
    ['arrow', 'стрела, стрелка'],
    ['mortgage', 'ипотека'],
    ['coffin', 'гроб'],
    ['essentially', 'по существу'],
    ['blank', 'пустой, незаполненный'],
    ['development', 'развитие'],
    ['commitment', 'обязательство'],
    ['armoire', 'большой шкаф'],
    ['to revoke', 'отменять, аннулировать (на "r")'],
    ['crossbow', 'арбалет'],
    ['range', 'ассортимент'],
    ['porch', 'крыльцо'],
    ['anthem', 'гимн'],
    ['dove', 'голубь'],*/
      ]