export const words2 = [

["kěyǐ","可以","можно (разрешение), могу\n如果你想早点走，现在就可以离开","可以"],
["kěnéng","可能","может быть\n他可能已经到机场了，我们再等等吧","可能"],
["bùguò","不过","но (нейтральное)\n这件衣服很漂亮，不过价格有点贵","不过"],
["kěshì","可是","но (к сожалению, возможно)\n我想去爬山，可是天气不太好","可是"],
["dànshì","但是","но зато (после 虽然)\n虽然很累，但是我还是坚持完成了工作","但是"],
["wèizhì","位置","местоположение (место + ставить)\n你能告诉我图书馆的具体位置吗","位置"],
["yīnwéi","因为","поскольку, так как (перед 所以)\n因为下雨，所以我们取消了户外活动","因为"],
["suǒyǐ","所以","поэтому (после 因为)\n他生病了，所以今天没来上课","所以"],
["xuéxí","学习","учиться\n学习中文需要每天练习听说读写","学习"],
["tīng","听","слушать\n老师讲课的时候，你要认真听讲","听"],
["shíhou","时候","промежуток времени\n小时候，我常常和爷爷去公园散步","时候"],
["dú","读","читать\n他每天早晨都读半小时的英语课文","读"],
["fànguǎn","饭馆","ресторан\n那家饭馆的菜很地道，价格也不贵","饭馆"],
["méiguānxì","没关系","ничего страшного, пустяки\n你迟到了没关系，我们还没开始","没关系"],
["qǐng","请","вежливое предложение (для вопроса 请问)\n请把窗户打开，让新鲜空气进来","请"],
["zǒu","走","идти\n时间不早了，我们该走了","走"],
["chūshēng","出生","рождаться\n他出生在上海，现在住在北京","出生"],
["chéngshì","城市","город\n北京是一个很大的城市","城市"],
["zìjǐde","自己的","свой, собственный\n你要有自己的想法","自己的"],
["yǔyán","语言","язык (речь)\n学习外语需要多练习","语言"],
["lǔyóu","旅游","путешествовать\n我计划明年去中国旅游","旅游"],
["qiānbǐ","铅笔","карандаш\n请用铅笔写答案","铅笔"],
["gāo","高","высокий\n这座山很高，爬上去要两个小时","高"],
["cháng","长","длинный, долгий\n这条河很长，有几千公里","长"],
["duǎn","短","короткий\n今天的时间很短，我们得快一点","短"],
["ǎi","矮","низкий, невысокий\n他个子虽然矮，但跑得很快","矮"],
["bǐ","比","по сравнению\n今天比昨天热得多","比"],
["wèiyú","位于","находиться\n学校位于市中心，交通很方便","位于"],
["háishì","还是","или\n你想喝茶还是咖啡","还是"],
["běifāng","北方","север\n中国北方的冬天很冷","北方"],
["nánfāng","南方","юг\n南方夏天经常下雨","南方"],
["kuàilè","快乐","счастливый\n和家人在一起是最快乐的","快乐"],
["shuāyá","刷牙","чистить зубы\n每天早晚要刷牙","刷牙"],
["dè","得","частица перед оценкой\n他说得很快，我跟不上","得"],
["gǎnxiè","感谢","благодарить\n感谢你的帮助，我很感动","感谢"],
["sànbù","散步","гулять\n晚饭后我喜欢去公园散步","散步"],
["shàngkè","上课","занятия, учеба\n他每天早上八点上课","上课"],
["tóu","头","голова\n他摇了摇头，表示不同意","头"],
["biānyuán","边缘","граница, край\n杯子放在桌子边缘，小心掉下来","边缘"],
["miànjí","面积","площадь\n这个房间的面积很大，有三十平方米","面积"],
["miàntiáo","面条","лапша\n他喜欢吃面条，尤其是牛肉面","面条"],
["miànbāo","面包","хлеб\n我早餐一般吃面包和牛奶","面包"],
["miànbǐng","面饼","лепешка\n这种面饼很好吃，脆脆的","面饼"],
["miànfěn","面粉","мука\n做蛋糕需要面粉、鸡蛋和糖","面粉"],
["là","辣","острый\n四川菜很辣，我有点受不了","辣"],
["jīngcháng","经常","часто\n他经常去图书馆学习","经常"],
["chángcháng","常常","обычно, часто\n我常常在周末去爬山","常常"],
["yǒushíhou","有时候","иногда\n有时候我会去朋友家玩","有时候"],
["cóngbu","从不","никогда\n他从不迟到，总是准时到","从不"],
["yèxiāo","夜宵","ночной перекус\n吃太多夜宵对身体不好","夜宵"],
["xuéyè","学业","учеба (школьная)\n他的学业很忙，没有时间出去玩","学业"],
["zhīhou","之后","после (времени)\n放学之后，我去操场跑步","之后"],
["fānyì","翻译","перевод, переводить\n请把这段话翻译成中文","翻译"],
["yuǎn","远","далекий\n火车站离这里很远，打车要半小时","远"],
["měi","每","каждый\n他每天都坚持跑步","每"],
["shàngbān","上班","ходить на работу\n我每天早上九点上班","上班"],
["xiǎoshí","小时","час\n从家到公司需要一小时","小时"],
["gōnggòngqìchē","公共汽车","автобус\n我坐公共汽车去学校","公共汽车"],
["dìtiě","地铁","метро\n坐地铁比坐公共汽车快","地铁"],
["mén","门","дверь\n请把门关上，外面有风","门"],
["qǐchuáng","起床","вставать, просыпаться\n他每天六点起床","起床"],
["yòng","用","использовать\n你可以用我的手机打电话","用"],
["pǔtōng","普通","обычный\n他只是一个普通人，没什么特别的","普通"],
["wèntí","问题","вопрос, проблема\n这个问题很难，我需要时间思考","问题"],
["xuě","雪","снег\n今年冬天下了很多雪","雪"],
["kè","课","урок\n今天有语文课和数学课","课"],
["huídá","回答","ответ\n请回答我的问题","回答"],
["yánsè","颜色","цвет\n你喜欢什么颜色","颜色"],

["jiéshù","结束","конец, окончание\n电影还有十分钟就结束了","结束"],
["wàimiàn","外面","снаружи, не дома\n外面下雨了，你带伞了吗","外面"],
["wénzhāng","文章","текст, статья\n他写的这篇文章非常有意思","文章"],
["fàngxué","放学","после школы\n放学后我们去操场踢球吧","放学"],
["lǐxiǎng","理想","идеальный, мечта\n他的理想是当一名医生","理想"],
["bùcuò","不错","без ошибки\n这家餐厅的菜不错","不错"],
["bùyòng","不用","не нужно, не надо\n不用着急，时间还很多","不用"],
["dǎlánqiú","打篮球","играть в баскетбол\n他每天下午都打篮球","打篮球"],
["túshūguǎn","图书馆","библиотека\n图书馆里有很多人在看书","图书馆"],
["yīqǐ","一起","вместе\n我们一起去看电影吧","一起"],
["chànggē","唱歌","петь песню\n她唱歌很好听","唱歌"],
["liáotiān"," 聊天","болтать, беседовать\n我们经常在微信上聊天","聊天"],
["zài","再","снова\n下次再来我家玩吧","再"],
["gàosù","告诉","сказать\n请告诉我你的电话号码","告诉"],
["lóuxià","楼下","внизу, на нижнем этаже\n我在楼下等你","楼下"],
["huā","花","цветы\n这些花真漂亮","花"],
["rènzhēn","认真","серьезный\n他做事很认真","认真"],
["jiǎozi","饺子","пельмени\n我喜欢吃饺子","饺子"],
["yuè","越","чем (жарче), тем (неприятней)\n你越努力，进步越快","越"],
["zhīshí","知识","знание\n学习知识很重要","知识"],
["yǒuyòng","有用","полезный\n电脑对学习很有用","有用"],
["dìfāng","地方","место\n这个地方很安静","地方"],
["shàngwǎng","上网","сидеть в интернете\n他每天上网看新闻","上网"],
["bāng","帮","помогать\n你能帮我拿一下这个包吗","帮"],
["yǒumíng","有名","известный, популярный\n北京有很多有名的景点","有名"],
["qìchē","汽车","автобус\n我坐汽车去上班","汽车"],
["kāiwánxiào","开玩笑","шутить\n别开玩笑，我说真的","开玩笑"],
["yītiān","一天","однажды\n一天，他遇到了一位老朋友","一天"],
["zhōumò","周末","выходные\n周末我们去爬山吧","周末"],
["zhǎo","找","искать\n我在找我的钥匙","找"],
["xiào","笑","смеяться\n他讲了一个笑话，大家都笑了","笑"],
["gěi","给","давать\n请给我一杯水","给"],
["xiàtiān","夏天","лето\n夏天我喜欢游泳","夏天"],
["háizi","孩子","дети\n孩子们在公园里玩耍","孩子"],
["xiūxi","休息","отдыхать\n你累了，休息一下吧","休息"],
["zhēn","真","действительно\n这部电影真好看","真"],
["shǒujī","手机","мобильный телефон\n我手机没电了","手机"],
["niúnǎi","牛奶","молоко\n他每天喝一杯牛奶","牛奶"],
["nàbiān","那边","там\n书店在那边","那边"],
["bāozi","包子","паровые булочки\n这家包子很好吃","包子"],
["shì","事","дела\n今天有很多事要处理","事"],
["diànyǐngyuàn","电影院","кинотеатр\n我们晚上去电影院吧","电影院"],
["fángjiān","房间","комната\n我的房间很整洁","房间"],
["zhī","只","счетное слово для животных\n他有一只猫","只"],
["duì","对","верно\n这个答案对吗","对"],
["bìngrén","病人","пациент, больной\n医生正在给病人看病","病人"],
["kāishǐ","开始","начинаться\n会议什么时候开始","开始"],
["huǒchē","火车","поезд\n我坐火车去上海","火车"],
["zìyóude","自由的","свободный (время)\n周末我有自由的时间","自由的"],
["wán","玩","играть\n孩子们在花园里玩","玩"],
["piányi","便宜","дешевый\n这件衣服很便宜","便宜"],
["chuān","穿","одеваться, носить\n今天穿什么衣服好呢","穿"],
["guì","贵","дорогой, дорого\n这条裤子太贵了","贵"],
["jiàn","件","штука, предмет\n我买了一件新外套","件"],
["zhèngzài","正在","в процессе\n他正在写作业","正在"],
["juéde","觉得","чувствовать\n我觉得这个办法不错","觉得"],
["shēngbìng","生病","заболеть\n他生病了，没来上课","生病"],
["kànbìng","看病","показаться врачу\n妈妈去医院看病了","看病"],
["yào","药","лекарства\n你吃过药了吗","药"],
["mài","卖","продавать\n这家店卖水果","卖"],
["yīxià","一下","как-нибудь, однажды (после глагола)\n你等一下，我马上来","一下"],
["nín","您","вы\n您先请，我马上就来","您"],
["fúwùyuán","服务员","официант\n服务员，麻烦您再拿一双筷子","服务员"],
["nǔshì","女士","леди, мадам\n那位女士是我的新邻居，人很热情","女士"],
["jīn","斤","дзинь (0,6 кг)\n我买了一斤苹果，花了十块钱","斤"],
["bǎi","百","сто\n这本书有三百多页，我还没看完","百"],
["yǒuxiē","有些","некоторые (люди), 有的\n有些问题需要慢慢解决，不能着急","有些"],
["hǎowánr","好玩儿","забавный, интересный\n这个游戏特别好玩儿，你也来试试吧","好玩儿"],
["zhàngfu","丈夫","муж\n她的丈夫在一家医院工作，每天很忙","丈夫"],
["xiāngjiāo","香蕉","банан\n香蕉不仅好吃，而且对身体很有好处","香蕉"],
["yú","鱼","рыба\n那条鱼很大，我们三个人都吃不完","鱼"],
["yángròu","羊肉","баранина\n羊肉串是我最喜欢的小吃之一","羊肉"],
["língchén","凌晨","ночь\n他凌晨两点才睡觉，早上起不来","凌晨"],
["jiéhūn","结婚","быть замужем\n他们结婚已经五年了，感情还是很好","结婚"],
["lǎogōng","老公","муж\n我老公每天下班后会去接孩子","老公"],
["yīnyuè","音乐","музыка\n听音乐能让人放松心情，忘记烦恼","音乐"],
["qíngtiān","晴天","солнечно\n明天是晴天，我们一起去爬山吧","晴天"],
["zhēnbàng","真棒","молодец\n你这么快就完成了作业，真棒","真棒"],
["huǒchēzhàn","火车站","вокзал\n火车站旁边有一家很大的超市","火车站"],
["qìchēzhàn","汽车站","остановка автомобильная\n汽车站离我家很近，走路五分钟","汽车站"],
["gōngjiāochē","公交车","автобус\n坐公交车比坐地铁便宜，但更慢","公交车"],
["wúguǐdiànchē","无轨电车","троллейбус\n无轨电车在这个城市已经不常见了","无轨电车"],
["yǒuguǐdiànchē","有轨电车","трамвай\n有轨电车沿着海边行驶，风景很美","有轨电车"],
["huángsè","黄色","желтый цвет\n她穿了一件黄色的裙子，很显眼","黄色"],
["lùsè","绿色","зеленый цвет (лю)\n绿色代表生命和希望，我喜欢这个颜色","绿色"],
["zǐsè","紫色","фиолетовый цвет\n紫色的葡萄看起来特别诱人","紫色"],
["zōngsè","棕色","коричневый цвет\n他有一双棕色的皮鞋，穿了好几年","棕色"],
["hēisè","黑色","чёрный цвет\n黑色的衣服比较耐脏，也容易搭配","黑色"],
["huīsè","灰色","серый цвет\n今天天空是灰色的，可能要下雨","灰色"],
["lánsè","蓝色","синий цвет\n他最喜欢的颜色是蓝色，因为像大海","蓝色"],
["dòngwù","动物","животные\n动物园里有很多动物，孩子们都很开心","动物"],
["guān","关","выключать, закрывать\n离开房间时请关好窗户和灯","关"],
["yòngcānyúkuài","用餐愉快","приятного аппетита\n祝您用餐愉快，需要什么随时叫我","用餐愉快"],
  /*
  
  ['gleefully', 'ликующе', "‘Storm forecast for tonight!’ said Uncle Vernon gleefully, clapping his hands together", "gleefully"],
  ['below', 'ниже', "A toothless old man pointed at an old rowing boat bobbing in the iron-grey water below them", "below"],
  ['to amble up', 'подниматься неторопливой походкой', "A toothless old man came ambling up to them, pointing at an old rowing boat", "ambling up"],
  ['wicked', 'злой, на "w"', "A toothless old man pointed, with a rather wicked grin, at an old rowing boat", "wicked"],
  ['to row', 'грести', "'I can still row and you will throw the net'", "row"],
  ['to whip', 'стегать, хлестать', "Icy sea spray and rain crept down their necks and a chilly wind whipped their faces", "whipped"],
  ['seaweed', 'водоросли', "The inside was horrible; it smelled strongly of seaweed, the wind whistled through the gaps in the wooden walls", "seaweed"],
  ['ration', 'рацион, пища', "'I’ve already got us some rations,' said Uncle Vernon, 'so all aboard!'", "rations"],
  ['to shrivel', 'съеживаться, на "s"', "He tried to start a fire but the empty crisp packets just smoked and shrivelled up", "shrivelled"],
  ['cheerful', 'жизнерадостный', "'Could do with some of those letters now, eh?' he said cheerfully", "cheerfully"],
  ['filthy', 'грязный', "Fierce wind rattled the filthy windows", "filthy"],
  ['to splatter', 'плескаться, брызгаться', "Spray from the high waves splattered the walls of the hut", "splattered"],
  ['hut', 'хижина, на "h"', "Spray from the high waves splattered the walls of the hut", "hut"],
  ['fierce', 'свирепый, неистовый, на "fi"'],
  ['mouldy', 'заплесневелый', "Aunt Petunia found a few mouldy blankets in the second room and made up a bed for Dudley", "mouldy"],
  ['to curl up', 'свернуться калачиком', "Harry was left to curl up under the thinnest blanket", "curl up"],
  ['lumpy', 'бугристый, на "l"', "She and Uncle Vernon went off to the lumpy bed next door", "lumpy"],
  ['ferocious', 'свирепый, на "fe"', "The storm raged more and more ferociously as the night went on", "ferociously"],
  ['to shiver', 'дрожать, на "s"', "He shivered and turned over, trying to get comfortable, his stomach rumbling with hunger", "shivered"],
  ['to drown', 'тонуть', "Dudley’s snores were drowned by the low rolls of thunder that started near midnight", "drowned"],
  ['dial', 'циферблат', "The lighted dial of Dudley’s watch told Harry he’d be eleven in ten minutes’ time", "dial"],
  ['to creak', 'скрипеть', "Harry heard something creak outside. He hoped the roof wasn’t going to fall in", "creak"],
  ['to crumble', 'крошиться, разрушаться', "Was the rock crumbling into the sea?", "crumbling"],
  ['cannon', 'пушка', "‘Where’s the cannon?’ he said stupidly", "cannon"],
  ['to skid', 'заносить (на поворотах), скользить', "There was a crash behind them and Uncle Vernon came skidding into the room", "skidding"],
  ['to warn', 'предупреждать', "‘Who’s there?’ he shouted. ‘I warn you – I’m armed!’", "warn"],
  ['to arm', 'вооружать', "‘Who’s there?’ he shouted. ‘I warn you – I’m armed!’", "armed"],
  ['force', 'сила', "The door was hit with such force that it swung clean off its hinges", "force"],
  ['hinge', 'дверная петля', "The door was hit with such force that it swung clean off its hinges", "hinges"],
  ['to glint', 'сверкать, на "gl"', "But you could make out his eyes, glinting like black beetles under all the hair", "glinting"],
  ['mane', 'грива', "His face was almost completely hidden by a long, shaggy mane of hair", "mane"],
  ['shaggy', 'лохматый', "His face was almost completely hidden by a long, shaggy mane of hair", "shaggy"],
  ['to stoop', 'сутулиться, на "st"', "The giant squeezed his way into the hut, stooping so that his head just brushed the ceiling", "stooping"],
  ['astride', 'верхом', "If the motorbike was huge, it was nothing to the man sitting astride it", "astride"],
  ['to budge up', 'подвинуться', "‘Budge up, yeh great lump,’ said the stranger", "Budge up"],
  ['lump', 'кусок, глыба, шишка от удара', "A troll even larger than the one they had tackled, out cold with a bloody lump on its head", "lump"],
  ['to crouch', 'скорчиться, прегнуться', "He ran to hide behind his mother, who was crouching, terrified, behind Uncle Vernon", "crouching"],
  ['rasp', 'скрежет, на "r"', "You can’t see a door on stage but you hear the rasp of a key in a lock", "rasp"],
  ['knot', 'узел', "He bent gun into a knot as easily as if it had been made of rubber", "knot"],
  ['summat', 'кое-что', "I've got summat for you here – I mighta sat on it at some point, but it’ll taste all right", "summat"],
  ['sligh', 'незначтельный, на "s"', "From an inside pocket of his black overcoat he pulled a slightly squashed box", "slightly"],
  ['to squash', 'раздавить', "From an inside pocket of his black overcoat he pulled a slightly squashed box", "squashed"],
  ['to rub', 'тереть', "'What about that tea then, eh?' he said, rubbing his hands together", "rubbing"],
  ['to bend down', 'наклониться вниз', "He bent down over the fireplace", "bent down"],
  ['flicker', 'вспышка, мерцание', "It filled the whole damp hut with flickering light", "flickering"],
  ['to sink', 'погрузиться (в воду), тонуть, провисать', "Said Hagrid, sitting back down on the sofa, which groaned and sank even lower", "sank"],
  ['stat', 'статистика', "'We're basing this decision on a stat'", "stat"],
  ['sacred', 'священный, на "s"', "The thoughts of historical spirits suddenly made Rachel realize what a sacred place this room was", "sacred"],
  ['to provide', 'обеспечивать', "These permanent holes in the ice provide seafood throughout the winter for birds", "provide"],
  ['directly', 'непосредственно, напрямую', "The alarms connect directly to the police station", "directly"],
  ['in a way', 'в некотором смысле', "I lacked humility, in a way I aspired to be God", "humility"],
  ['acupuncture', 'иглоукалывание', "'She's going to see if acupuncture will improve the circulation to my dad's brain'", "acupuncture"],
  ['assignment', 'назначение, распределение, инструкции на "as"', "Because I've got an important assignment for you", "assignment"],
  ['tough', 'жесткий, сильный, на "t"', "They could usually shoot well, knew the value of obeying an order, and they were tough", "tough"],
  ['temporary', 'временный', "He suffered temporary full-body paralysis and full movement was never restored", "temporary"],
  ['strike', 'удар, на "s"', "He came to sitting on the ground and waited for the knife to strike him", "strike"],
  ['to groom', 'холить, ухаживать', "'Why would any man dress well, groom himself and lift weights just to sleep with other men?'", "groom"],
  ['to slash', 'хлестать, рубить, на "s"', "'I slashed wildly at any part of the filthy body that presented itself'", "slashed"],
  ['benefit', 'выгода, превилегия', "Was it a mistake or are we friends with benefits?", "benefits"],
  ['unless', 'до тех пор, пока; если не', "'I wouldn't murder you tonight; unless, perhaps, I set the house on fire: but that's as my fancy goes'", "unless"],
  ['harsh', 'суровый, на "h"', "he had been slapped by his mother for the first time and had heard her voice raised at him in harsh words", "harsh"],
  ['to coddle', 'няньчиться, баловать', "'I should be ashamed to coddle myself as you do!'", "coddle"],
  ['to deduct', 'вычитать', "You pay a certain percentage, which you deduct from your trading account", "deduct"],
  ['to swamp', 'заливать, затопить', "Though bay completely swamped, the boat was nearly unharmed", "swamped"],
  ['memo', 'памятка, заметка', "'She's even send a memo telling us not to speak with the reporters'", "memo"],
  ['superior', 'начальник, вышестоящий'],
  ['to be in charge in', 'быть ответственным за'],
  ['to pick', 'выбирать'],
  ['inappropriate', 'неподходящий, неуместный, на "in"'],
  ['fortune', 'состояние (деньги)'],
  ['to decrease', 'сокращаться, уменьшаться (численно)'],
  ['specific', 'конкретный'],
  ['pathetic', 'жалкий, убогий, на "p"'],
  ['knob', 'дверная ручка'],
  ['pile', 'куча, стопка, на "p"'],
  ['to invent', 'изобретать, выдумывать'],
  ['troop', 'отряд, на "t"'],
  ['shaft', 'шахта'],
  ['to thrive', 'процветать'],
  ['felon', 'преступник, на "f"'],
  ['to forge', 'подделывать'],
  ['to accuse', 'обвинять, на "a"'],
  ['to perpetrate', 'совершать, на "p"'],
  ['carefully', 'внимательно'],
  ['entirely', 'полностью'],
  ['for cristes sake', 'ради Бога'],
  ['option', 'вариант'],
  ['to submit', 'предоставлять (информацию)'],
  ['to forfeit', 'утратить'],
  ['to refer', 'ссылаться (на что-то), обращаться к кому-то, направлять'],
  ['terrific', 'потрясающе, на "t"'],
  ['to expire', 'истекать (срок годности)'],
  ['judgemental', 'склонный к осуждению'],
  ['to sag', 'провисать, обвисать'],
  ['kettle', 'чайник (для кипячения)'],
  ['teapot', 'чайник (для завариваия)'],
  ['mug', 'кружка'],
  ['to chip', 'откалывать, отколоть'],
  ['amber', 'янтарь, янтарный'],
  ['swig', 'глоток, на "s"'],
  ['to sizzle', 'шипеть, шкварчать'],
  ['poker', 'кочерга, шампур'],
  ['to fitjet', 'ёрзать, на "f"'],
  ['gulp', 'глоток, на "g"'],
  ['to cower', 'съёжиться, на "c"'],
  ['to growl', 'рычать, на "g"'],
  ['pale', 'бледный'],
  ['to bewilder', 'недоумевать, сбивать с толку'],
  ['syllable', 'слог'],
  ['to quail', 'дрогнуть, испугаться'],
  ['deputy', 'заместитель'],
  ['to stammer', 'заикаться, на "sta"'],
  ['quill', 'перо, игла животного, на "q"'],
  ['to scribble', 'нацарапать, начеркать'],
  ['beak', 'клюв'],
  ['to clamp', 'зажимать, зажать, на "clam"'],
  ['ash', 'пепел'],
  ['indeed', 'действительно, в самом деле, на "i"'],
  ['dratted', 'проклятый, на "d"'],
  ['to shriek', 'вопить, кричать на "s"'],
  ['spawn', 'потомство'],
  ['to rant', 'разглогольствовать, говорить с особой важностью'],
  ['to draw', 'втянуть, вытащить, привлекать'],
  ['to scuttle', 'удирать'],
  ['to get lend', 'получить взаймы'],
  ['outrage', 'безобразие'],
  ['urgently', 'срочно, неотложно'],
  ['to fade', 'увядать'],
  ['foghorn', 'сирена, горн'],
  ['curse', 'проклятие'],
  ['fosh', 'ерунда, на "f"'],
  ['to glare', 'свирепо смотреть (1 слово)'],
  ['to clench', 'сжимать, на "cle"'],
  ['sword', 'меч'],
  ['to flatten', 'сгладить, выравнивать, на "f"'],
  ['to spear', 'пронзать, нанизывать'],
  ['codswallop', 'ерунда, на "c"'],
  ['to bide', 'выжидать'],
  ['to reckon', 'рассчитывать на что-то, считать (думать) 1 слово'],
  ['to blaze', 'сверкать, сиять, на "bl"'],
  ['to be clouted', 'быть затмённым'],
  ['toad', 'жаба'],
  ['wart', 'бородавка'],
  ['sorcerer', 'колдун'],
  ['to dread', 'опасаться'],
  ['to beam', 'сиять, на "be"'],
  ['crackpot', 'чокнутый'],
  ['to whirl', 'кружить, вертеть, на "w"'],
  ['firecracker', 'фейерверк, петарда'],
  ['squeal', 'визг'],
  ['spot', 'место'],
  ['to clasp', 'сцепить, сжать, на "clas"'],
  ['temper', 'характер'],
  ['to keen', 'сильно желать, увлекаться'],
  ['to expel', 'выгонять, исключать'],
  ['gamekeeper', 'егерь, лесник'],
  ['to wriggle', 'извиваться'],
  ['claw', 'коготь'],
  ['to scramble', 'карабкаться, на "s"'],
  ['to carry on', 'продолжать'],
  ['savage', 'свирепый, жестокий, на "s"'],
  ['bunch', 'кучка, связка (ключей)'],
  ['pellet', 'гранула'],
  ['pouch', 'сумка, мешок'],
  ['to tie', 'привязывать, завязывать'],
  ['to puncture', 'проколоть, на "pu"'],
  ['to mess with', 'возиться. связываться с кем-то'],
  ['to gleam', 'блестеть, на "gle"'],
  ['to settle down', 'расположиться'],
  ['enchantment', 'очарование, магия'],
  ['vault', 'подвал, погреб, на "v"'],
  ['prophet', 'пророк, прорицатель'],
  ['bungler', 'растяпа, плохой работник'],
  ['blimey', 'вот это да'],
  ['harbor', 'бухта'],
  ['to fold up', 'свернуть (газету)'],
  ['to clamber', 'карабкаться, на "c"'],
  ['to pant', 'запыхаться, тяжело дышать'],
  ['stitch', 'шов, стяжок'],
  ['to require', 'требоваться, нуждаться'],
  ['pointed', 'остроконечный, заостренный, 7 букв'],
  ['hide', 'шкура'],
  ['fastening', 'крепление'],
  ['fungi', 'грибы'],
  ['draft', 'проект'],
  ['cauldron', 'котел'],
  ['pewter', 'оловянный, на "p"'],
  ['to get stuck', 'застрять, словосочетание'],
  ['bustling', 'шумный, суетливый, на "b"'],
  ['halt', 'остановка'],
  ['leaky', 'дырявый'],
  ['grubby', 'неряшливый, неопрятный, на "g"'],
  ['shabby', 'обшарпанный, на "s"'],
  ['sherry', 'херес'],
  ['walnut', 'грецкий орех'],
  ['to buzz', 'жужжать'],
  ['chatter', 'болтовня, на "c"'],
  ['to buckle', 'согнуться, пристегнуть на "bu"'],
  ['honour', 'честь, честный человек'],
  ['to puff', 'пыхтеть, затягиваться (сигаретой)'],
  ['scraping', 'скрежет, на "s"'],
  ['to delight', 'восхищаться, на "d"'],
  ['to grasp', 'схватить, на "g", 5 букв'],
  ['babble', 'лепет, бормотание на "b"'],
  ['cemetery', 'кладбище'],
  ['odd', 'странность'],
  ['to bump', 'врезаться, ударяться'],
  ['certain', 'определенный'],
  ['battlefield', 'поле боля'],
  ['to desert', 'покидать, на "d"'],
  ['hostage', 'заложник'],
  ['loss', 'потеря'],
  ['vomit', 'тошнота'],
  ['despite', 'несмотря на'],
  ['minor', 'незначительный, на "m"'],
  ['percentage', 'процент, доля'],
  ['inning', 'подача (спорт)'],
  ['bulge', 'выпуклость'],
  ['to rebound', 'восстанавливаться'],
  ['evidence', 'доказательства'],
  ['disposable', 'одноразовый'],
  ['hitter', 'нападающий (спорт)'],
  ['snag', 'загвоздка'],
  ['authenticity', 'подлинность'],
  ['succinct', 'кратко'],
  ['guilty', 'виновный'],
  ['to arch', 'выгнуть, прогнуться'],
  ['to strike out', 'вычеркнуть'],
  ['bothering', 'надоедающий'],
  ['to accomplish', 'выполнять, совершать, достигать на "a"'],
  ['cab', 'такси'],
  ['to fall apart', 'разваливаться'],
  ['to rescue', 'спасать'],
  ['catchphrase', 'ключевая фраза (лозунг)'],
  ['disadvantage', 'недостаток'],
  ['maintenance', 'обсоуживание, ремонт'],
  ['scuttlebutt', 'слухи, сплетни'],
  ['stroke of genius', 'гениальный ход'],
  ['streamer', 'плакат'],
  ['whorish', 'развратный'],
  ['to gamble', 'рисковать'],
  ['to flip a coin', 'бросить монетку'],
  ['vulnerable', 'уязвимый'],
  ['to giggle', 'хихикать, на "g"'],
  ['to appreciate', 'ценить, оценивать, на "a"'],
  ['to condone', 'оправдывать, на "c"'],
  ['fraud', 'обман, мошенничество, на "f"'],
  ['accountant', 'бухгалтер'],
  ['chummy', 'дружелюбный, обаятельный'],
  ['tension', 'напряжение'],
  ['therefore', 'следовательно'],
  ['cerebral palsy', 'церебральный паралич'],
  ['generous', 'щедрый'],
  ['convalescence', 'выздоровление, восстановление'],
  ['issue', 'вопрос, проблема'],
  ['warehouse', 'склад, на "w"'],
  ['downer', 'зануда'],
  ['effort', 'усилие'],
  ['to flaunt', 'щеголять, выставлять напоказ'],
  ['sizeable', 'значительный'],
  ['to betray', 'предавать'],
  ['valuable', 'ценный, 8 букв'],
  ['weed', 'сорняк'],
  ['bloke', 'парень. тип'],
  ['hag', 'ведьма'],
  ['above', 'выше'],
  ['cobble', 'булыжник (для мощения дороги)'],
  ['to twist', 'крутить, закручиваться, на "t"'],
  ['instantly', 'немедленно'],
  ['to hang', 'висеть'],
  ['plump', 'пухлый, упитанный'],
  ['hooting', 'уханье (крик совы)'],
  ['emporium', 'магазин'],
  ['barn', 'сарай, амбар'],
  ['to stack', 'складывать, на "s"'],
  ['barrel', 'бочка, на "b"'],
  ['spleen', 'селезенка'],
  ['eel', 'угорь'],
  ['to totter', 'шататься'],
  ['to tower', 'возвышаться'],
  ['scarlet', 'алый'],
  ['to burnish', 'полировать'],
  ['swartly', 'смуглый'],
  ['to engrave', 'выгравировать'],
  ['to heed', 'внимать, учитывать'],
  ['greed', 'жадность'],
  ['dearly', 'дорого'],
  ['ledger', 'бухгалтерская книга'],
  ['to scatter', 'рассыпать'],
  ['torch', 'факел'],
  ['steep', 'крутой (склон)'],
  ['railway track', 'рельсовая дорога'],
  ['to hurtle', 'мчаться, на "h"'],
  ['maze', 'лабиринт'],
  ['to sting', 'жалить'],
  ['to plunge', 'броситься, окунаться, на "p"'],
  ['to lean', 'опираться'],
  ['passage', 'коридор, проход'],
  ['to billow', 'вздыматься (дым)'],
  ['mound', 'насыпь, холм'],
    ['heap', 'куча, груда, на "h"'],
    ['to pile', 'сложить, нагромоздить, на "p"'],
    ['ravine', 'овраг'],
    ['to trap', 'застять (в ловушке), поймать в ловушку'],
    ['squat', 'приземистый, коренастый'],
    ['mauve', 'лиловый, сиреневый'],
    ['to pin up', 'подкалывать (одежду при примерке)'],
    ['to drowl', 'растягивать (слова)'],
    ['mean', 'подлый, злой'],
    ['generally', 'обычно'],
    ['feather', 'перо, на f"'],
    ['do you mind if', 'ты не будешь против, если...'],
    ['agreement', 'соглашение'],
    ['grumpy', 'угрюмый, сердитый, на "g"'],
    ['to taunt', 'дразнить, насмехаться, на "ta"'],
    ['spose', 'супруг'],
    ['toreplay', 'предварительные ласки'],
    ['seduction', 'соблазнение, искушение'],
    ['merely', 'просто, только, лишь'],
    ['cranky', 'капризный, эксцентричный'],
    ['circumstances', 'обстоятельства'],
    ['to chase out', 'выгонять'],
    ['to loom', 'виднеться, маячить'],
    ['mutually', 'взаимно'],
    ['delusion', 'заблуждение'],
    ['discourse', 'рассуждение'],
    ['to reciprocate', 'отвечать взаимностью'],
    ['overly', 'чрезмерно'],
    ['exeedingly', 'чрезвычайно, крайне, на "e"'],
    ['verbal', 'словестный, устный'],
    ['to stump', 'озадачить, поставить в тупик, ковылять'],
    ['adjective', 'прилагательное'],
    ['boundaries', 'границы'],
    ['properiety', 'правильность'],
    ['misplace', 'терять'],
    ['utter', 'полнейший, абсолютный'],
    ['flood', 'наводнение, потоп'],
    ['once', 'однажды'],
    ['pity', 'жалость'],
    ['to owe', 'быть должным'],
    ['gut', 'кишка'],
    ['unconditional', 'безусловный'],
    ['specimen', 'экземпляр, образец'],
    ['to long', 'тосковать'],
    ['to throb', 'пульсировать'],
    ['inconsistent', 'несоответствующий'],
    ['to unsettle', 'расстраивать, тревожить'],
    ['gesture', 'жест'],
    ['to reconsider', 'пересмотреть, на "rec"'],
    ['purse', 'кошелек'],
    ['vague', 'смутный, туманный'],
    ['to condemn', 'осуждать, порицать, на "cond"'],
    ['valid', 'актуальный, действительный'],
    ['thoughtful', 'заботливый, внимательный, на "t"'],
    ['to arrange', 'организовывать, расставлять, упорядочить'],
    ['to diminish', 'снижать, уменьшать'],
    ['rough', 'грубый, на "ro"'],
    ['rug', 'коврик'],
    ['ally', 'союзник'],
    ['bellybutton', 'пупок'],
    ['to compound', 'составлять (смесь)'],
    ['to rid', 'избавляться'],
    ['crotch', 'пах, ширинка, на "c"'],
    ['to smuggle', 'провозить контрабандой'],
    ['to bully', 'запугивать, задирать'],
    ['servant', 'прислуга'],
    ['savage', 'дикарь'],
    ['to excuse', 'оправдываться'],
    ['to cheer up', 'развеселиться, взбодриться'],
    ['duffer', 'простофиля'],
    ['paving stones', 'брусчастка (словосочетание)'],
    ['postage stamp', 'марка'],
    ['to drag away', 'оттащить'],
    ['to bewitch', 'околдовать'],
    ['to befuddle', 'одурманить'],
    ['revenge', 'месть'],
    ['collapsible', 'складной, разборный'],
    ['to rot', 'гнить'],
    ['slimy', 'склизский, липкий'],
    ['to line', 'выстраивать (в линию)'],
    ['fang', 'клык'],
    ['snarled', 'запутанный'],
    ['horn', 'рог'],
    ['minuscule', 'крошечный'],
    ['to sneeze', 'чихать'],
    ['rustling', 'шелест, шуршание, на "r"'],
    ['to peel', 'облезть, облупиться'],
    ['depth', 'глубина'],
    ['finkle', 'звон'],
    ['to occur', 'случаться, возникать, на "o"'],
    ['to prickle', 'покалывать'],
    ['gloom', 'мрак, темнота'],
    ['awkwardly', 'неловко'],
    ['willow', 'ива'],
    ['mahogany', 'красное дерево'],
    ['pliable', 'гибкий, пластичный, на "p"'],
    ['to reflect', 'отражаться'],
    ['armpit', 'подмышка'],
    ['core', 'ядро'],
    ['nostril', 'ноздря'],
    ['to flit', 'порхать'],
    ['to crumple', 'смять, скомкать, на "cru"'],
    ['beechwood', 'бук'],
    ['maple', 'клен'],
    ['whippy', 'гибкий, на "w"'],
    ['springy', 'упругий'],
    ['customer', 'покупатель'],
    ['to whoop', 'выкрикнуть'],
    ['to destine', 'предназначать (судьбой)'],
    ['to gawp', 'глазеть, на gaw"'],
    ['laden', 'нагруженный (чем-то тяжелым)'],
    ['mistress', 'любовница'],
    ['improvement', 'улучшение'],
    [' a while', 'через некоторое время'],
    ['to hoover', 'пылесосить'],
    ['to pin', 'приколоть'],
    ['quiz', 'викторина'],
    ['howling', 'вопиющий, на "h"'],
    ['to dump', 'сваливать (в кучу)'],
    ['to wheel', 'катить'],
    ['term', 'срок, период'],
    ['to strand', 'застрять, на "s"'],
    ['to swing around', 'развернуться, словосочетание'],
    ['to hammer', 'стучать, долбить'],
    ['divide', 'деление, разделение'],
    ['rucksack', 'рюкзак'],
    ['briskly', 'бодро, резво'],
    ['gangling', 'неуклюжий, нескладный'],
    ['to jostle', 'толкать, на "j"'],
    ['to drift', 'проплывать, парить, на "d"'],
    ['disgruntle', 'недовольство'],
    ['carriage', 'вагон'],
    ['compartment', 'отсек, камера, купе'],
    ['to shove', 'совать, толкать, пихать'],
    ['to chorus', 'говорить хором'],
    ['badge', 'значок'],
    ['prefect', 'староста'],
    ['fondly', 'нежно, ласково'],
    ['to goggle', 'выпучивать глаза, пялиться'],
    ['to blurt', 'выпаливать (речь), на "b"'],
    ['load', 'груз, поклажа'],
    ['to voice', 'выпаливать, озвучивать, на "v"'],
    ['clatter', 'топот'],
    ['dimpled', 'с ямочками на щеках'],
    ['pastie', 'пирожок'],
    ['corned', 'соленый, засоленный'],
    ['to flow', 'течь, струиться'],
    ['to consider', 'считать, учитывать, рассматривать (на должность)'],
    ['currently', 'в настоящий момент'],
    ['circumcision', 'обрезание'],
    ['curtains', 'шторы'],
    ['range', 'диапазон'],
    ['suitable', 'подходящий, на "s"'],
    ['maiden name', 'девичья фамилия'],
    ['urgent', 'срочный, неотложный'],
    ['aftermath', 'последствия'],
    ['to injure', 'ранить, на "i"'],
    ['jaw', 'челюсть'],
    ['to vouch on', 'поручиться за…'],
    ['foreman', 'мастер цеха, бригадир'],
    ['warranty', 'гарантия'],
    ['to chicken out', 'струсить'],
    ['to grumble', 'ворчать, на "gru"'],
    ['slayer', 'убийца, истребитель'],
    ['schedule', 'график, расписание, на "s"'],
    ['flouncy', 'волнистый'], 
    ['posse', 'отряд, на "p"'],
    ['first aid kit', 'аптечка первой помощи'],
    ['to forward', 'пересылать, рассылать'],
    ['defence', 'защита; оборона'], 
    ['to foul', 'нарушать правила'],
    ['foul', 'нарушение'],
    ['flagrant', 'вопиющий, чудовищный, на "f"'],
    ['to prevent', 'предотвращать, на "p"'],
    ['affirmative', 'утвердительный (ответ)'],
    ['incentive', 'стимулирующий'],
    ['to reward', 'награждать'],
    ['outstanding', 'выдающийся'], 
    ['torture', 'пытка'],
    ['vendor', 'продавец'],
    ['to infiltrate', 'просачиваться, проникать, на "i"'],
    ['henhouse', 'курятник, на "h"'],
    ['lass', 'девушка'],
    ['decisiveness', 'решительность, на "dec"'],
    ['to hesitate', 'колебаться, медлить'],
    ['addict', 'пристрастие'],
    ['to interact', 'взаимодействовать'],
    ['origin', 'происхождение'],
    ['bead', 'бусина'],
    ['sequins', 'блестки'],
    ['fallback', 'отступление, на "f"'],
    ['divine', 'святой, божественный, на "d"'],
    ['to guzzle', 'жадно пить/есть'],
    ['to bust', 'обанкротиться, разориться'],
    ['to pry', 'любопытствовать, выведывать'],
    ['to tempt', 'искушать, соблазнять, на "t"'],
    ['nearby', 'поблизости'],
    ['inferior', 'подчиненный, на "i"'],
    ['favour', 'одолжение, благосклонность'],
    ['festive', 'праздничный, торжественный'],
    ['in order', 'в порядке, по порядку'],
    ['imperative', 'обязательный, на "i"'],
    ['to head back', 'возвращаться'],
    ['to grab a coffee', 'захватить кофе (с собой)'],
    ['accidentally', 'случайно'],
    ['annual', 'ежгодный'],
    ['award', 'награда'],
    ['recognition', 'признание (всеобщее), узнавание'],
    ['wreck', 'авария, катастрофа'],
    ['cocky', 'самоуверенный, дерзкий'],
    ['bling', 'боеск, на "b"'],
    ['skillet', 'сковорода, на "s"'],
    ['stage', 'этап'],
    ['footage', 'отснятый материал'],
    ['camcorder', 'видеокамера'],
    ['to tape', 'снимать на камеру'],
    ['defacement', 'порча (имущества)'],
    ['highness', 'величество, высочество'],
    ['to descend', 'спускаться, сходить'],
    ['serf', 'крепостной (раб)'],
    ['validation', 'подтверждение, одобрение'],
    ['loosely', 'свободно, вольно'],
    ['to come across', 'столкнуться (буквально)'],
    ['to ban', 'запрещать, на "b"'],
    ['repercussion', 'отголосок (последствия)'],
    ['announcement', 'объявление'],
    ['cord', 'шнур, провод'],
    ['host', 'хозяин'],
    ['to spill', 'пролить'],
    ['beaver', 'бобер'],
    ['horny', 'возбужденный'],
    ['concern', 'беспокойство'],
    ['stickler', 'приверженец, сторонник'],
    ['bower', 'игрок'],
    ['stink', 'вонь, на "sti"'],
    ['seizure', 'приступ, припадок'],
    ['apparently', 'вероятно'],
    ['concussion', 'сотрясение мозга'],
    ['harassment', 'издевательство, оскорбление'],
    ['priest', 'священник, жрец'],
    ['forward', 'рассылка'],
    ['queer', 'странный, необычный, на "q"'],
    ['to resign', 'уходить в отставку'],
    ['breathalyser', 'алкотестер'],
    ['suspense', 'неизвестность, неопределенность'],
    ['trait', 'черта характера'],
    ['to scrutinize', 'тщательно изучать'],
    ['to interrupt', 'прерывать, на "interr"'],
    ['to insist', 'настаивать, на "i"'],
    ['mutiny', 'бунт'],
    ['intent', 'намерение, умысел'],
    ['irrelevant', 'неуместный, неважный, на "ir"'],
    ['albeit', 'хотя, на "alb"'],
    ['to avoid', 'избегать'],
    ['to disclose', 'раскрывать, на "d"'],
    ['to settle a bet', 'заключить пари'],
    ['hypocrite', 'лицемер'],
    ['thong', 'ремень, на "t"'],
    ['to agitate', 'агитировать'],
    ['to associate', 'связывать, ассоциировать'],
    ['witty', 'остроумный'],
    ['attorney', 'адвокат'],
    ['boner', 'стояк'],
    ['to stay put', 'оставаться на месте, на "sta"'],
    ['bogey', 'пугало, приведение'],
    ['sprout', 'росток'],
    ['to nibble', 'грызть, обгрызать'],
    ['tearful', 'заплаканный'],
    ['to poke out', 'высовываться, на "p"'],
    ['taken aback', 'застанный врасплох, на "t"'],
    ['daisy', 'маргаритка'],
    ['mellow', 'мягкий, сочный'],
    ['by heart', 'наизусть'],
    ['stunned', 'ошеломленный, на "s", 7 букв'],
    ['to stun', 'оглушать, ошеломлять'],
    ['daze', 'изумление, ошеломление, на "d"'],
    ['dud', 'подделка, недействительный'],
    ['to settle', 'обосноваться, уладить'],
    ['whiskers', 'усы'],
    ['dumbfound', 'ошарашенный, на "d"'],
    ['finer point', 'нюанс, тонкость'],
    ['thickset', 'коренастый'],
    ['coolly', 'невозмутимо, хладнокровно'],
    ['tinge', 'оттенок'],
    ['riff-ruff', 'сброд'],
    ['to lurk', 'скрываться, прятаться'],
    ['to scowl', 'хмуриться, на "s"'],
    ['sniffy', 'презрительно'],
    ['to race', 'мчаться, бегать, на "r"'],
    ['trainers', 'кроссовки'],
    ['to echo', 'вторить, повторять'],
    ['to cram', 'втискивать, напихивать, на "c"'],
    ['throng', 'толпиться'],
    ['path', 'тропа'],
    ['starry', 'звездный'],
    ['turret', 'башня'],
    ['fleet', 'флот'],
    ['to glide', 'скользить, на "g"'],
    ['cliff', 'утес, скала'],
    ['pebble', 'галька'],
    ['oak', 'дуб'],
    ['blissfully', 'блаженно, облегченно, на "b"'],
    ['to fit', 'помещаться'],
    ['staircase', 'парадная лестница'],
    ['to flag', 'помечать'],
    ['to drone', 'гудеть, бубнить, на "d"'],
    ['shortly', 'вскоре'],
    ['within', 'внутри, в течение'],
    ['dormitory', 'общежитие, спальный корпус'],
    ['to smarten', 'прихорошиться'],
    ['to linger', 'задерживать (взгляд), на "l"'],
    ['to smudge', 'пачкаться'],
    ['jolt', 'толчок'],
    ['doom', 'погибель'],
    ['to stream', 'литься, проноситься'],
    ['transparent', 'прозрачный'],
    ['to glide', 'скользить. на "g"'],
    ['monk', 'монах, старец'],
    ['tights', 'трико, колготы'],
    ['splendid', 'великолепно, на "sp"'],
    ['to lay table', 'накрыть на стол'],
    ['goblet', 'кубок (посуда)'],
    ['to come to a halt', 'остановиться'],
    ['lantern', 'фонарь'],
    ['to dot', 'усеивать'],
    ['among', 'среди, на "amo"'],
    ['mainly', 'в основном, на "m"'],
    ['upwards', 'вверх'],
    ['stool', 'табуретка'],
    ['four-legged', 'четвероногий'],
    ['patch', 'заплатка, клочок'],
    ['to fray', 'износить'],
    ['brim', 'край, на "b"'],
    ['rip', 'разрыв, буквальный'],
    ['bowler', 'котелок, на "b"'],
    ['sleek', 'гладкий. элегантный'],
    ['to dwell', 'обитать, жить'],
    ['daring', 'отважный, смелый, на "d"'],
    ['nerve', 'смелость, наглость, на "n"'],
    ['chivalry', 'рыцарство'],
    ['to toil', 'усиленно трудиться'],
    ['wit', 'остроумие, смекалка'],
    ['to join', 'присодиниться'],
    ['to jog', 'бегать трусцой'],
    ['amid', 'среди, на "ami"'],
    ['gale', 'шторм, буря'],
    ['to swagger', 'важно расхаживать'],
    ['plenty', 'множество, масса'],
    ['properly', 'надлежащим образом'],
    ['recognise', 'узнавать'],
    ['pompously', 'напыщенно'],
    ['scroll', 'свиток'],
    ['uncertainly', 'неуверенно'],
    ['chop', 'отбивная'],
    ['gravy', 'подливка'],
    ['peas', 'горох'],
    ['miffed', 'обиженный'],
    ['in a row', 'подряд (словосочетание)'],
    ['unbearable', 'невыносимый'],
    ['rural', 'сельский, деревенский'],
    ['compassionate', 'сострадательный'],
    ['assertive', 'настойчивый, убедительный, на "a"'],
    ['affectionate', 'проявляющий привязанность'],
    ['possessive', 'собственнический'],
    ['posses', 'обладать, иметь'],
    ['considerate', 'внимательный к кому-то, на "c"'],
    ['reliable', 'надежный (человек)'],
    ['affordable', 'доступный (по деньгам)'],
    ['spacious', 'просторный'],
    ['attic', 'чердак'],
    ['desirable', 'желанный, желательный'],
    ['turquoise', 'бирюзовый'],
    ['navy', 'морской (цвет)'],
    ['to take a nap', 'вздремнуть (словосочетание)'],
    ['stock', 'склад, запас, на "s"'],
    ['to humiliate', 'унижать, оскорблять, на "h"'],
    ['to revive', 'возрождать'],
    ['paper clip', 'скрепка'],
    ['representative', 'представитель'],
    ['to rely on', 'полагаться на, на "r"'],
    ['arrangement', 'расположение, размещение'],
    ['courtesy', 'вежливость, учтивость'],
    ['honorable', 'почетный'],
    ['whiner', 'нытик'],
    ['sanctuary', 'храм, святилище'],
    ['eternal', 'вечный'],
    ['arrow', 'стрела, стрелка'],
    ['mortgage', 'ипотека'],
    ['coffin', 'гроб'],
    ['essentially', 'по существу'],
    ['blank', 'пустой, незаполненный'],
    ['development', 'развитие'],
    ['commitment', 'обязательство'],
    ['armoire', 'большой шкаф'],
    ['to revoke', 'отменять, аннулировать (на "r")'],
    ['crossbow', 'арбалет'],
    ['range', 'ассортимент'],
    ['porch', 'крыльцо'],
    ['anthem', 'гимн'],
    ['dove', 'голубь'],*/
      ]