export const words4 = [


  ["jǐnzhāng","紧张","напрягать(ся); напряжение; взволнованность\n我明天要参加面试，现在心里很紧张","紧张"],
  ["miànshì","面试","интервью, устный экзамен\n明天的面试对我来说很重要，我需要好好准备","面试"],
  ["lùshī","律师","адвокат (лю)\n我的哥哥是一名律师，他帮助很多人解决法律问题","律师"],
  ["tōngzhī","通知","сообщать; извещать; уведомлять\n学校通知我们下周要考试，请大家做好准备","通知"],
  ["yìngpìn","应聘","устраиваться на работу, принять оффер\n我最近应聘了几家公司，希望能找到一份好工作","应聘"],
  ["tǐng","挺","весьма; чрезвычайно, исключительно\n这个城市挺大的，我需要一张地图才能找到路","挺"],
  ["xìnxīn","信心","уверенность; чувство уверенности; вера\n我对这次考试很有信心，因为我已经复习了很多遍","信心"],
  ["nénglì","能力","способность; сила\n他的工作能力很强，老板非常喜欢他","能力"],
  ["zhāopìn","招聘","приглашать; нанимать (на работу)\n我们公司正在招聘新员工，如果你有兴趣可以来试试","招聘"],
  ["tígōng","提供","предоставлять; поставлять; снабжать\n这家酒店提供免费早餐和无线网络","提供"],
  ["fùzé","负责","нести ответственность; отвечать за что-либо; ответственный\n这个项目由王经理负责，你可以直接问他","负责"],
  ["běnlái","本来","первоначальный; истинный; вообще говоря, собственно говоря\n我本来想今天去超市，但是突然下雨了","本来"],
  ["cáiliào","材料","материал\n写论文之前，需要收集很多相关资料","材料"],
  ["fúhé","符合","соответствовать; совпадать; отвечать чему-либо\n你的条件符合我们的要求，欢迎加入我们","符合"],
  ["lìngwài","另外","кроме того, сверх того\n我今天买了一件衣服，另外还买了一双鞋","另外"],
  ["zánmen","咱们","мы (включая собеседника)\n咱们一起去看电影吧，我听说这部片子很不错","咱们"],
  ["shǒuxiān","首先","сначала, сперва; в первую очередь; во-первых\n首先，我想感谢大家的到来；其次，我想说一下今天的安排","首先"],
  ["zhèngshì","正式","официальный; официально\n下周一我们将正式签订合同","正式"],
  ["liú","留","покинуть\n老师留了很多作业，我今晚得熬夜做完","留"],
  ["qícì","其次","затем; потом; далее; следующий; во-вторых\n其次，我们要注意安全问题","其次"],
  ["chéngshí","诚实","честный, правдивый; честно, правдиво\n做人要诚实，不能说谎","诚实"],
  ["gǎibiàn","改变","изменять, переменять; преобразовывать\n这个城市在最近几年改变了很多","改变"],
  ["pànduàn","判断","судить, оценивать; определять, решать; определение, решение; полагать, считать\n根据这些数据，我们可以判断明年的市场趋势","判断"],
  ["zhǔnshí","准时","вовремя; в установленное время\n他每天上班都很准时，从不迟到","准时"],
  ["bùguǎn","不管","несмотря на (то, что); независимо от того; как бы ни; будь то; кто бы ни\n不管天气怎么样，我们明天都会去爬山","不管"],
  ["yǔ","与","и; с; к\n请你与王老师联系一下，确认会议时间","与"],
  ["zuòshēngyi","做生意","вести торговлю; торговать\n他在上海做生意，已经好几年了","做生意"],
  ["zhīshi","知识","знания; познания\n学习知识不仅为了考试，更是为了将来","知识"],
  ["ànshí","按时","вовремя; своевременно\n请按时完成作业，不要拖延","按时"],
  ["zhuànqián","赚钱","зарабатывать деньги\n现在很多年轻人想通过互联网赚钱","赚钱"],
  ["luàn","乱","беспорядочный, хаотичный; хаотично, беспорядочно; как попало\n他的房间很乱，他应该收拾一下","乱"],
  ["tí","提","упоминать\n在会议上，他提到了一个新的计划","提"],
  ["yǐwéi","以为","думать, верить\n我以为是他的错，后来才发现是我弄错了","以为"],
  ["wánquán","完全","полный; целый; совершенный; законченный\n我完全同意你的看法","完全"],
  ["diàochá","调查","обследовать; обследование\n警察正在调查这起事故的原因","调查"],
  ["yuánlái","原来","с самого начала; первоначально; первоначальный\n原来是你啊，我差点没认出来","原来"],
  ["tíqián","提前","досрочно; раньше установленного срока\n我们提前十分钟到达了车站","提前"],
  ["bǎozhèng","保证","гарантировать; ручаться; обязываться; гарантия; залог; обязательство\n我保证明天一定把书还给你","保证"],
  ["tíxǐng","提醒","напоминать; подсказывать\n请提醒我明天早上八点开会","提醒"],
  ["jīlěi","积累","накапливать, копить, скапливать\n他通过多年的积累，终于有了丰富的经验","积累"],
  ["shùnlì","顺利","гладко; успешно; благоприятно\n这次旅行非常顺利，我们玩得很开心","顺利"],
  ["xiāoxi","消息","известия; новости; сообщения; сведения\n你听到那个好消息了吗？我们公司获得了第一名","消息"],
  ["jiǎngjīn","奖金","денежная награда; премия; премиальные\n由于表现优秀，他年底得到了一笔丰厚的奖金","奖金"],
  ["fāngfǎ","方法","метод, способ; средство; приём\n学习外语最好的方法是多听多说","方法"],
  ["bùdébù","不得不","быть вынужденным\n因为下雨，我们不得不取消户外活动","不得不"],
  ["shènzhì","甚至","вплоть до того; что; даже; а то и (даже)\n他工作非常努力，甚至周末也在加班","甚至"],
  ["zérèn","责任","ответственность; обязанность; долг\n作为老师，我们有责任关心每个学生","责任"]



   //hp chapter 12
/*
   ['to smirk', 'ухмыляться', "Malfoy, Crabbe and Goyle pushed roughly past the tree, scattering needles everywhere and smirking", "smirking"],
   ['spectacular', 'впечатляюще', "The Hall looked spectacular. Festoons of holly and mistletoe hung all around the walls", "spectacular"],
   ['festoon', 'гирлянда', "The Hall looked spectacular. Festoons of holly and mistletoe hung all around the walls", "Festoons"],
   ['mistletoe', 'омела', "The Hall looked spectacular. Festoons of holly and mistletoe hung all around the walls", "mistletoe"],
   ['to blossom', 'расцветать', "Said Ron tearing his eyes away from Professor Flitwick, who had golden bubbles blossoming out of his wand", "blossoming"],
   ['to trail', 'свисать, подвешивать, тащить, на "t"', "He was trailing golden bubbles over the branches of the new tree", "trailing"],
   ['hint', 'подсказка, намек, на "h"', "'We can’t find him anywhere – just give us a hint'", "hint"],
   ['to let it slip', 'проговориться о чем-то', "They had indeed been searching books for Flamel’s name ever since Hagrid had let it slip", "let it slip"],
   ['sheer size', 'огромный размер', "There was the sheer size of the library", "sheer size"],
   ['to restrict', 'ограничивать, запрещать, на "r"', "'You needed a specially signed note from one of the teachers to look in any of the restricted books'", "restricted"],
   ['to brandish', 'размахивать, выставлять напоказ, на "b"', "Madam Pince the librarian brandished a feather duster at him", "brandished"],
   ['fortnight', 'две недели', "They had been looking for a fortnight, but they’d found nothing", "fortnight"],
   ['fork', 'вилка', "They sat by the hour eating anything they could spear on a toasting fork – bread, crumpets, marshmallows", "fork"],
   ['to plot', 'замышлять, строить козни', "They plotting ways of getting Malfoy expelled", "plotting"],
   ['battered', 'потрепанный, избитый', "Ron’s chess set was very old and battered", "battered"],
   ['drawback', 'недлостаток, изъян, на "d"', "However, old chessmen weren’t a drawback at all", "drawback"],
   ['chessmen', 'шахматная фигура', "They were standing on the edge of a huge chessboard, behind the black chessmen", "chessmen"],
   ['turnip', 'репа', "'What did you expect, turnips?' said Ron", "turnips"],
   ['to whittle', 'строгать, вырезать из дерева', "Hagrid had obviously whittled wooden flute himself", "whittled"],
   ['fascinated', 'очарованный, восхищенный, на "f"', "Ron was fascinated by the fifty pence", "fascinated"],
   ['fudge', 'помадка', "Harry had torn open the parcel to find a large box of home-made fudge", "fudge"],
   ['fold', 'складка, на "f"', "Something fluid and silvery grey went slithering to the floor, where it lay in gleaming folds", "folds"],
   ['awe', 'страх, трепет, изумление', "'It’s an Invisibility Cloak' said Ron, a look of awe on his face", "awe"],
   ['to suspend', 'приостановить, подвесить, на "s"', "His head suspended in mid-air, his body completely invisible", "suspended"],
   ['possession', 'владение, обладание', "Your father left this in my possession before he died", "possession"],
   ['half-heartedly', 'нерешительно, в полсилы, без энтузиазма', "'I hate maroon' Ron moaned half-heartedly as he pulled sweater over his head", "half-heartedly"],
   ['to observe', 'наблюдать, заметить, на "o"', "'You haven’t got a letter on your sweater' George observed", "observed"],
   ['disapproving', 'неодобрительный', "Percy Weasley stuck his head through the door, looking disapproving", "disapproving"],
   ['feeble', 'хилый, немощный, на "f"', "These fantastic crackers were nothing like the feeble Muggle ones", "feeble"],
   ['flimsy', 'хрупкий', "With their little plastic toys and their flimsy paper hats", "flimsy"],
   ['to engulf', 'поглощать, охватывать, на "en"', "It went off with a blast like a cannon and engulfed them all in a cloud of blue smoke", "engulfed"],
   ['bonnet', 'капот, шляпа, на "b"', "Dumbledore had swapped his pointed wizard’s hat for a flowered bonnet", "bonnet"],
   ['flaming', 'пылающий', "Flaming Christmas puddings followed the turkey.", "Flaming"],
   ['to embed', 'встроить, внедрить', "Percy nearly broke his teeth on a silver Sickle embedded in his slice", "embedded"],
   ['lop-sided', 'кривобокий', "He finally kissing Professor McGonagall on the cheek blushed, her top hat lop-sided", "lop-sided"],
   ['to nag', 'пилить, ныть', "Yet something had been nagging at the back of his mind all day", "nagging"],
   ['to squawk', 'кудахтать, орать, на "s"', "'Who’s there?' squawked the Fat Lady", "squawked"],
   ['eerie', 'зловещий, мрачный, на "e"', "The library was pitch black and very eerie", "eerie"],
   ['sight', 'вид, зрелище', "Light suddenly flooded the room to reveal an astonishing sight", "sight"],
   ['to curdle', 'застыть', "A piercing, blood-curdling shriek split the silence – the book was screaming!", "-curdling"],
   ['to pay attention', 'обратить внимание', "'Lucky you pay attention in Herbology, Hermione' said Harry", "pay attention"],
   ['to drain', 'истощать, осушать', "'Here I come' he said and he drained the little bottle in one gulp", ""],
   ['short cut', 'короткий путь', "Wherever he was, Filch must know a short cut", "short cut"],
   ['disused', 'заброшенный, вышедший из употребления', "It looked like a disused classroom", "disused"],
   ['to prop', 'подпирать, прислонить, на "p"', "Propped mirror against the wall", "Propped"],
   ['to carve', 'разделывать, прорезать (резать предмет), на "c"', "There was an inscription carved around the top", "carved"],
   ['flat', 'плоскость, поверхность', "And every few yards they expected to see Paddy appear over the far flat horizon", "flat"],
   ['ache', 'боль', "He had a powerful kind of ache inside him", "ache"],
   ['distant', 'отдаленный', "A distant noise brought him back to his senses", "distant"],
   ['route', 'маршрут', "They tried retracing Harry’s route from the library", "route"],
   ['to transfix', 'приковать', "Ron, though, was staring transfixed at his image", "transfixed"],
   ['entranced', 'зачарованный', "'Men have wasted away before it, entranced by what they have seen, or been driven mad'", "entranced"],
   //office s3e2
   ['convention', 'соглашение (между сторонами)', "He continues to ignore our convention and the law", "convention"],
   ['to romp', 'возиться', "Three others were romping with a young bear, one pulling him by the chain", "romping"],
   ['to broadcast', 'транслировать', "'Your trial was broadcast to a single office on the other side of town'", "broadcast"],
   ['traitor', 'предатель', "'Remember, his brother in his eyes may not loom as a traitor but as a patriot'", "traitor"],
   ['petty', 'мелкий, незначительный, на "p"', "Everybody knew their place and was prepared to die defending their petty rights", "petty"],
   ['crooked', 'кривой, на "c"', "Her eyes were pale, her face sallow, and her teeth crooked", "crooked"],
   ['alias', 'псевдоним, кличка', "'Why does any thief use an alias?'", "alias"],
   ['to take into account', 'принимать к сведению, учитывать'],
   ['feller', 'парень, на "f"', "'You seem a respectable young feller'", "feller"],
   ['to defect', 'переметнуться (предать, дезертировать)', "'I guess there are only two ways to retire from this place... die or defect'", "defect"],
   ['phooey', 'тьфу', "'Phooey, we gotta wait all that time?'", "Phooey"],
   ['to estimate', 'оценивать, на "es"', "They estimate the work to be about an hour, which means they'll be done in June", "estimate"],
   ['hooker', 'проститутка', "There is a hooker in his room", "hooker"],
   ['to come up with', 'придумывать (что-то)', "'We don't have time to come up with another escape plan'", "come up with"],
   ['edgy', 'острый, раздражительный, на "e"', "'And see, I have this edgy sense of humor which sometimes crosses the line like right now, for instance'", "edgy"],
   ['to put it all on the line', 'поставить все на кон', "'We should put it all on the line to help him?'", "put it all on the line"],
   ['picky', 'разборчивый', "'You get picky about what you put in the tank, your engine is going to die'", "picky"],





   //office s3e3
   ['coup', 'переворот (государственный), удачный ход'],
   ['blues', 'хандра'],
   ['various', 'разнообразный'],
   ['to whine', 'ныть, на "w"'],
   ['to sack', 'увольнять, выгонять'],
   ['to peeve', 'раздражать, на "p"'],
   ['virtuous', 'добродетяльный, праведный'],
   ['camisole', 'лифчик'],
   ['to undermine', 'подрывать (на мине)'],
   ['to slaughter', 'зарезать, убить, на "s"'],
   ['stuffed', 'набитый, заполненный, сытый'],
   ['bonding', 'соединение, скрепление, на "b"'],
   ['floss', 'зубная нить'],
   ['to stab', 'колоть, пронзать, ранить, на "s"'],
   ['ferocity', 'свирепость, жестокость, на "f"'],
   ['savings', 'сбережения (средства)'],
   ['mileage', 'пробег'],
   ['laundry', 'прачечная, стирка'],
   //office s3e4
   ['grief', 'горе, несчастье'],
   ['counselling', 'консультирование, рекомендация, наставничество'],
   ['to decapitate', 'обезглавить, на "d"'],
   ['skunk', 'скунс, вонючка, гад'],
   ['instant', 'моментальный, мгновенный'],
   ['to peg', 'привязать'],
   ['quitter', 'лодырь'],
   ['to bargain', 'торговаться, договариваться, на "b"'],
   ['bargaining', 'торг, переговоры'],
   ['bucket', 'ведро'],
   ['sledgehammer', 'кувалда'],
   ['fetus', 'зародыш, плод'],
   ['to toss', 'бросать (жребий, предмет), на "to"'],
   ['to trample', 'топтать, затоптать, на "tra"'],
   ['wildebeest', 'антилопа'],
   ['goner', 'мертвец'],
   ['to flush', 'промывать'],
   ['to inconvenience', 'беспокоить, причинять неудобство, на "i"'],
   ['to confirm', 'подтверждать'],
   ['drum', 'бочка, на "d"'],
   ['to confine', 'ограничивать, на "c"'],
   ['baloney', 'чушь, вздор'],
   //office s3e5
   ['teaser', 'головоломка'],
   ['dime', 'десять центов'],
   ['log', 'журнал (конспект)'],
   ['complimentary', 'приветственный, бесплатный'],
   ['tenant', 'квартиросъемщик'],
   ['to cut in line', 'втиснуться в очередь'],
   ['to kneel', 'стоять на коленях'],
   ['manure', 'навоз'],
   ['resourceful', 'находчивый'],
   ['proportionate', 'соразмерный'],
   ['to authorise', 'разрешать, уполномачивать, на "a"'],
   ['to screw up', 'испортить что-либо, на "sc"'],
   ['determination', 'решительность, на "det"'],
   ['frat', 'братство'],
   ['to drizzle', 'моросить'],
   ['hallowed', 'священный, на "h"'],
   ['consolidation', 'объединение, слияние, на "c"'],
   ['undergo', 'подвергаться, испытывать'],
   ['to vanquish', 'побеждать, покорять, на "v"'],
   ['efficiency', 'эффективность'],
   ['accountability', 'отчетность, ответственность, на "a"'],
   ['fad', 'прихоть'],
   ['average', 'среднестатистический'],
   ['to confuse', 'спутать, запутаться, на "c"'],
   //office s3e6
['put on by', 'организованный (кем-то)'],
['appalled', 'потрясен, шокирован, на "a"'],
['without further adieu', 'без дальнейших отлагательств (вводная фраза)'],
['busty', 'грудастая'],
['to subject', 'подвергать, подчиняться, на "s"'],
['explicit', 'откровнный, явный, на "e"'],
['competitive', 'конкурентный (з/п)'],
['outgoing', 'общительный'],
['fountain', 'фантан'],
['alike', 'похожий'],
['inflatable', 'надувной'],
['jolly', 'веселый, радостный, на "j"'],
//office s3e7
['cordially', 'сердечно, искренне, на "c"'],
['heartly', 'искренне, на "h"'],
['board', 'правление, комитет'],
['to relish', 'получать удовольствие, наслаждаться'],
['crawl with', 'кишеть, наполнен чем-то, на "c"'],
['to sprout', 'расти, давать ростки'],
['ripe', 'спелый, созревший, на "r"'],
['to pluck', 'срывать, выщипывать'],
['particular', 'конкретный, отдельный, на "p"'],
['blessing', 'благословение'],
['to confront', 'противостоять, на "con"'],
['to pollute', 'загрязнять, осквернять'],
['revisit', 'пересмотреть, на "r", 7 букв'],
['replenish', 'пополнять'],
['overall', 'в целом'],
['haze', 'туман, дымка, на "h"'],
['extinguisher', 'огнетушитель'],
['foam', 'пена'],
//hp chapter 13
['to roam', 'бродить, нп "r"'],
['to skim through', 'бегло просматривать'],
['to dampen', 'ослабить, отсыреть'],
['apart from', 'помимо, кроме, на "a"'],
['to divebomb', 'пикировать, 8 букв'],
['to mess around', 'валять дурака'],
['excuse', 'повод, отговорка, оправдание'],
['to pick on', 'приставать, обращаться плохо'],
['sinister', 'зловещий, жуткий, на "s"'],
['to stick together', 'склеиваться, слипаться вместе'],
['to urge', 'призывать, настаивать, на "u"'],
['to mystify', 'заинтриговать'],
['astonishing', 'удивительный, поразительный, на "a"'],
['noted', 'известный, знаменитый'],
['no wonder', 'неудивительно'],
['biased', 'предвзятый, необъективный'],
['pep talk', 'ободряющая речь'],
['grim', 'мрачный, на "gr"'],
['to capture', 'захватить, поймать'],
['to favour', 'благоволить, поддерживать'],
['somersault', 'сальто, кувырок'],
['broad', 'широкий, на "b"'],
['scuffle', 'драка, потасовка, шарканье'],
['whirl', 'вихрь, водоворот'],
['to erupt', 'извергаться, разразиться'],
['to brood', 'размышлять, вынашивать мысль'],
['blur', 'пятно, размытость'],
['hood', 'капюшон, капот, на "h"'],
['to prowl', 'слоняться, красться, на "p"'],
['to brush', 'задевать'],
['to thump', 'ударять, бить, на "t"'],
//office s3e8
['to merge', 'поглощать, соединять, на "m"'],
['merger', 'слияние, объединение, на "m"'],
['to keep cards close to the vest', 'держать планы/намерения в секрете'],
['vest', 'жилет'],
['to cross', 'противостоять (кому-то), на "cr"'],
['to outrun', 'обогнать, на "ou"'],
['ahead', 'впереди'],
['noon', 'полдень'],
['abode', 'местопребывание, жилище, на "a"'],
['as far as', 'поскольку'],
['carpenter', 'плотник, столяр'],
['nifty', 'изящный, стильный, на "n"'],
['to presume', 'предполагать, полагать, на "p"'],
['scale', 'масштаб, размер'],
['to report', 'докладывать, отчитываться'],
['drumroll', 'барабанная дробь'],
['dope', 'наркотик, дурь, на "d"'],
['unconvincing', 'неубедительно'],
['to marginalise', 'оттеснить, изолировать'],
['to lay on', 'положиться на, на "l"'],
['pine', 'сосна'],
['to evolve', 'развиваться, меняться, на "e"'],
['heresy', 'ересь'],
['accurate', 'точный, на "a"'],
['estimate', 'оценка'],
['windshield', 'лобовое стекло'],
['egregious', 'вопиющий, на "e"'],
['to avert', 'предотвращать, на "a"'],
['crisis', 'кризис'],
['aplomb', 'уверенность, на "a"'],
['grocery', 'бакалея, продуктовый'],
['corkscrew', 'штопор'],
['staples', 'скобы, скрепки, на "s"'],
['interchange', 'обмен, на "i"'],
//office s3e9
['convict', 'заключенный, осужденный'],
['to convict', 'осуждать, обвинять, на "conv"'],
['rebate', 'скидка, вычет'],
['to intervene', 'вмешиваться, вступиться'],
['ill-lit', 'плохоосвещенный'],
['sack', 'мешок'],
['halfsie', 'наполовину (полукровка)'],
['to institute', 'учредить, возбудить'],
['bulk', 'основная часть (основная масса/объем)'],
['to sic', 'натравливать'],
['to malign', 'клеветать'],
['to slur', 'опорочить'],
['to claim', 'заявлять, утверждать, на "c"'],
['claim', 'претензия, заявлние, на "c"'],
['randsome', 'случайный человек'],
['rap sheet', 'судимость, список криминального прошлого'],
['gruel', 'жидкая каша, размазня'],
['to redeem', 'выкупать, искупать, освобождать'],
['to relive', 'заново пережить'],
['nutcase', 'псих'],
['nuisance', 'неприятность, помеха, на "n"'],
//office s3e10
['to run over', 'задавить, сбить на машине'],
['molten', 'растопленный'],
['can', 'банка'],
['knickknack', 'безделушка, вещица'],
['worn', 'изношенный, потертый'],
['bold move', 'смелый шаг'],
['bold', 'отважный, на "b"'],
['proposal', 'предложение (чего-то)'],
['skimpy', 'скудный, откровенный (одежда)'],
['to start over', 'начать сначала'],
['to split up', 'расстаться'],
['amicable', 'дружеский, мирный'],
['foreign', 'чужой'],
['raffle', 'лотырея, розыгрыш призов'],
['nutcracker', 'щелкунчик'],
['riddle with', 'изрешечено чем-то (как пулями)'],
['riddle', 'загадка'],
['mold', 'плесень'],
['adage', 'изречение, пословица'],
['to stand up for', 'поддерживать, защищать (идею)'],
['to host', 'проводить, оганизовывать'],
['to desist', 'воздерживаться, на "d"'],
['crease', 'складка, залом, на "c"'],
['to crease', 'мять, сминать, на "cre"'],
['paraphernalia', 'принадлежности, атрибуты'],
['validity', 'допустимость, обоснованность'],
['to deny', 'отклонять, отказывать, отрицать, на "d"'],
['goose bumps', 'мурашки'],
['disagreement', 'разногласие'],
['innards', 'внутренности'],
['walkie-talkie', 'портативная радиация'],
['to disband', 'расформировать'],
['to embrace', 'обнимать, охватывать, на "em"'],
['possum', 'опоссум'],
['distraction', 'развлечение'],
//office s3e11
['to chop', 'рубить, нарезать, крошить'],
['payroll', 'расчетная ведомость по зарплате'],
['impoverished', 'бедный, неимущий'],
['to postpone', 'откладывать, переносить'],
['skeevy', 'отвратительный, мерзкий'],
['suckling', 'молочный, грудной'],
['he bought it', 'он купился на это'],
['ridiculous', 'до смешного нелепо'],
['identity theft', 'кража личных данных'],
['tendency', 'тенденция, склонность'],
['to indulge', 'баловать'],
['to redefine', 'переопределить'],
['to lower', 'снижать, опускать'],
//office s3e12
['tardy', 'запоздалый, поздний, медленный'],
['gracious', 'любезно, мило'],
['marine', 'морской, моряк'],
['to wear down', 'разрушить, стереть (словосочетание)'],
['to assemble', 'собирать, созывать'],
['rear', 'тыл, задний, хвостовой'],
['nest', 'гнездо'],
['crow', 'ворона'],
['decency', 'порядочность, приличие, на "d"'],
['log cabin', 'изба'],
['to wary', 'опасаться, на "w"'],
['irreversible', 'необратимый'],
['belongings', 'принадлежности, мелкое имущество'],
['to shatter', 'разрушить, раздробить, на "s"'],

//hp chapter 14
['to sweep about', 'расхаживать, словосочетание'],
['to tell off for', 'упрекать, отчитывать за'],
['timetable', 'расписание, график, на "t"'],
['to revise', 'пересматривать, на "r", 6 букв'],
['along the same lines', 'в том же духе'],
['longingly', 'с тоской'],
['moleskin', 'тяжелая хлопчатобумажная ткань'],
['shifty', 'хитрый, изворотливый, на "s"'],
['matter of fact', 'на самом деле'],
['to hush up', 'заставить замолчать, заткнуть'],
['stiflingly', 'удушающе'],
['stifle', 'душить, на "sti"'],
['grate', 'решетка, очаг'],
['to blaze', 'сверкать, гореть, на "bl"'],
['bush', 'куст'],
['to fiddle', 'играть (теребить) чем-то'],
['to hatch', 'высиживать, вылупляться'],
['to stoke', 'топить, разжигать'],
['trowel', 'мастерок, шпатель, тяпка'],
['to usher', 'сопровождать, вводить'],
['with bated breath', 'затаив дыхание'],
['spiny', 'колючий, на "sp"'],
['stub', 'огрызок, окурок, обрубок'],
['to bolt', 'удирать, броситься, на "b"'],
['to reason with', 'обсуждать с'],
['to drag by', 'тянуться'],
['to chime', 'звенеть, отбивать (часы)'],
['hitch', 'заминка'],
['to soothe', 'утешать, успокаивать'],
['to sit bolt upright', 'сесть прямо'],
['hoarse', 'хриплый'],
['to heave', 'поднимать, тянуть, на "he"'],
['to grapple', 'бороться, сцепиться, на "g"'],
['tartan', 'клетчатая (шотландка)'],
['detention', 'задержание, арест'],
['to thrash', 'молотить, бить, метаться, на "tr"'],
['harness', 'упряжь, снаряжение'],
//hp chapter 15
['likely', 'вероятно, возможно, на "l"'],
['to consider', 'рассматривать, считаться'],
['slippers', 'тапочки'],
['cock-and-bull story', 'очень преувеличенная история или не реальное оправдание'],
['to blunder', 'споткнуться, оплошать, на "b"'],
['sense', 'разум, рассудок'],
['to make up for', 'компенсировать, искуплять'],
['to owe one', 'быть в долгу у кого-то'],
['to admit', 'признавать, допускать'],
['to meddle', 'вмешиваться, влезать, на "m"'],
['to draw attention', 'привлекать внимание'],
['rebellion', 'восстание, бунт'],
['to kindle', 'зажигать, разжигать'],
['to poke around', 'исследовать местность вокруг'],
['to leer', 'ухмыляться, на "l"'],
['off you go', 'ступай, выдвигайся'],
['to scud', 'нестись'],
['in one piece', 'в целости и сохранности'],
['quiver', 'дрожь, колчан для стрел'],
['to bob', 'подпрыгивать, качаться, на "b"'],
['trail', 'след, тропа'],
['to stagger', 'шататься, на "s"'],
['coward', 'трус'],
['mossy', 'покрытый мхом'],
['to wind', 'наматывать, обматывать'],
['winding', 'извилистый'],
['to fade away', 'угасать'],
['sorrow', 'печаль'],
['skyward', 'ввысь, к небу'],
['hoof', 'копыто'],
['bend', 'изгиб, поворот'],
['slender', 'тонкий, стройный'],
['to stalk', 'подкрадываться, преследовать, на "s"'],
['to dribble', 'капать, сочиться'],
['flank', 'бок (тела)'],
['to foretell', 'предсказывать, на "f"'],
['to predict', 'предсказывать, на "p"'],
['hind', 'лань'],
['canter', 'галоп'],
['as well', 'также'],
['imprecise', 'неточный'],
['sore', 'язва, болячка'],
['just in case', 'на всякий случай'],
//hp chapter 16
['in years to come', 'в последующее время'],
['swelteringly', 'душно'],
['to drip', 'капать'],
['to fret', 'беспокоиться, на "f"'],
['to be up to', 'быть вовлеченным во что-то'],
['batty', 'сумасшедший, на "b"'],
['flock', 'стадо, стая'],
['to flock', 'стечься, устремиться, на "f"'],
['to bask', 'нежиться, греться'],
['shallow', 'отмель, на "sha"'],
['to throw caution to the wind', 'отбросить осторожность'],
['caution', 'осторожность'],
['to tumble', 'упасть, рухнуть, на "t"'],
['to splutter', 'брызгать слюной, лепетать'],
['rest assured', 'будьте уверены'],
['to pocket', 'положить в карман'],
['bid', 'заявка, претензия, на "b"'],
['to steel myself to', 'заставлять себя решиться на что-то'],
['to jam', 'заклинивать'],
['to bind', 'связывать, привязывать, на "b"'],
['omen', 'знамение, знак'],
['to skulk', 'прятаться, скрываться, на "s"'],
['to scoot', 'удирать'],
['harp', 'арфа'],
['to droop', 'увядать, сникать, на "d"'],
['tune', 'мелодия'],
['to draw breath', 'перевести дыхание'],
['to cease', 'прекращать'],
['to approach', 'подходить, приближаться, на "a"'],
['to grit teeth', 'стиснуть зубы'],
['fingertips', 'кончики пальцев'],
['to sprawl', 'растянуться, распластаться'],
['tendrils', 'усики, завитки (у растений)'],
['creeper', 'вьющееся растние, плющ'],
['snare', 'ловушка'],
['to wring', 'скручивать, выжимать, на "w"'],
['to cringe', 'съежиться, на "cr"'],
['to unravel', 'распутать'],
['to trickle', 'течь струйкой'],
['vicious', 'злой, жестокий, на "v"'],
['midst', 'посреди'],
['not for nothing', 'не зря'],
['knack', 'умение, сноровка'],
['to ram', 'таранить, трамбовать'],
['bishop', 'епископ, священник, слон (шахматы)'],
['pawn', 'пешка'],
['to pounce', 'внезапно атаковать'],
['threshold', 'порог'],
['to brace', 'готовиться, бодриться'],
//hp chapter 17
['treble', 'тройной'],
['nosy', 'любопытный (черта характера)'],
['to head off', 'препятствовать, словосочетание'],
['idly', 'лениво, пассивно'],
['all along', 'все это время'],
['to loathe', 'ненавидеть'],
['faith', 'вера'],
['faithfully', 'верно (служить)'],
['to tail', 'затихать'],
['to curse under breath', 'бормотать ругательства'],
['pace', 'шаг'],
['to surge', 'хлынуть'],
['in vain', 'напрасно'],
['to sear', 'прижигать'],
['to lessen', 'уменьшиться, на "l"'],
['blister', 'волдырь'],
['lunge', 'ринуться, на "l"'],
['palm', 'ладонь'],
['grasp', 'захват'],
['token', 'знак, на "t"'],
['lavatory', 'уборная, туалет'],
['to amuse', 'развлекать, забавлять'],
['precisely', 'точно, четко, на "p"'],
['nevertheless', 'тем не менее'],
['hatred', 'ненависть'],
['window-sill', 'подоконник'],
['to detest', 'презирать, испытывать неприязнь'],
['to plead', 'умолять, упрашивать, на "p"'],
['to be off rocker', 'сойти с ума'],
['to straighten', 'распрямлять'],
['remorse', 'раскаяние'],
['fuss', 'суетиться'],
['serpent', 'змея'],
['waffle', 'болтовня, на "w"'],
['to stamp', 'топать, на "sta"'],
['to dish out', 'распределить (баллы между участниками)'],
['radish', 'редис'],
['din', 'шум, гвалт, на "d"'],
['to add up', 'суммировать'],
['gradually', 'постепенно'],
['to nudge', 'подтолкнуть'],
['abysmal', 'бездонный'],
['to scrape through', 'едва ли перейти минимальный порог'],
['in a manner of speaking', 'можно и так сказать'],
['uncertainty', 'неуверенность, неопределенность'],
//office s3e13
['trivia', 'викторина, пустяки, мелочи'],
['jackhammer', 'отбойный молоток'],
['insatiable', 'неутолимый, ненасытный'],
['merciless', 'беспощадный'],
['subtraction', 'вычитание, на "s"'],
['pleasing', 'приятный, отрадный'],
['night crew', 'ночная смена'],
['bejesus', 'потроха'],
['self-awareness', 'самосознание'],
['preference', 'предпочтение, пристрастие'],
['to align', 'выравнивать, на "a"'],
['rod', 'стержень, удочка'],
['sportscaster', 'спортивный комметатор'],
['exceptional', 'исключительный'],
['competitor', 'конкурент'],
['same old', '(дела) все также'],
['to misjudge', 'неверно оценить, недооценить, на "m"'],
['to suck up to', 'подлизываться к, на "s"'],
['genuinely', 'искренне, подлинно, на "g"'],
//office s3e14
['gunk', 'дрянь, грязь'],
['socket', 'розетка'],
['epiphany', 'прозрение'],
['to ensure', 'убедиться, гарантировать'],
['ragamuffin', 'оборванец'],
['to deflower', 'лишить девственности'],
['spinster', 'старая дева, незамужняя'],
['rough patch', 'период неприятностей'],
['to eavesdrop', 'подслушивать, на "e"'],
['coed', 'студентка'],
['supplies', 'припасы'],
['to spank', 'шлепать'],
['kite', 'воздушный змей'],
['saucy', 'дерзкий, нахальный, на "s"'],
['impersonator', 'самозванец, подражатель'],
['groom', 'жених, на "g"'],
['sleazebag', 'подонок'],
['to acquire', 'приобретать, покупать, на "a"'],
['near-sighted', 'близорукий'],
['delicacy', 'деликатес'],
['far-sighted', 'дальновидный'],
//hp chapter1
["foul","грязный,отвратительный (на «f»)"],
["to break out","разразиться, вспыхнуть (словосочетание)"],
["belch","отрыжка"],
["to droop","свисать, на «dr»"],
["temple","висок, храм"],
["to tolerate","терпеть ,переносить"],
["cabin","хижина, изба (на «c»)"],
["log","бревно, брус"],
["padlock","висячий замок"],
["to look nothing like","быть совсем не похожим на"],
["porky","жирный, на «p»"],
["to bring up","воспитывать"],
["let alone","не даже говоря о"],
["lounge","гостиная, холл"],
["rapturously","восторженно, на «r»"],
["to aim","нацеливаться"],
["forcefully","решительно, на «f»"],
["hedge","изгородь, ограда"],
["dung","навоз, на «d»"],
["to tear up","покинуть место в большой спешке"],
["appeal","привлекательность"],

["archenemy","заклятый враг"],

["cunning","хитрый","коварный, на «c»"],

["livid","мертвенно бледный"],

["absentmindedly","рассеянно"],

["to jeer","насмехаться, глумиться, на «j»"],

["to hitch up","подтянуть (штаны)"],

["to set on fire","поджечь"],

["to chuck out","избавиться от чего-либо"],

["blow","удар, на «bl»"],

["to loll around","валяться без дела"],

["to mow","косить"],

["flowerbed","клумба"],

["to prune","подрезать"],

["bait","приманка, наживка"],

["to collapse","рухнуть (на кровать)"],
//офис куча серий
["to immortalize","увековечить"],

["backup","резервный, запасной"],

["solution","раствор, на «s»"],

["zing and pep","задор и бодрость духа"],

["to josh around","обмениваться добродушными шутками"],

["wagon","вагончик, тележка"],

["to tow","буксировать, тащить"],

["to diss","оскорблять, на «d»"],

["explanatory","пояснительный, объясняющий"],

["to sass","дерзить"],

["humility","смирение, покорность"],

["clash","столкновение, битва"],

["to pick on","обращаться плохо с кем-то"],

["to carol","воспевать, колядовать"],

["probation","испытательный срок, стажировка"],

["consequences","последствия"],

["jug","кувшин"],

["cashier","кассир"],

["canvas","холст"],

["booth","будка, стенд (на выставке)"],

["to lure","завлекать, заманивать"],

["application","заявление (на работу)"],
["imposter","самозванец"],

["deceiver","обманщик"],

["prejudice","предубеждения, на «prej»"],

["bias","предубеждение, на «b»"],

["to adjust","настраивать, регулировать, на «а»"],

["lumbar","поясничный"],

["curvy","изогнутый, соблазнительный"],

["anticipation","предвкушение, ожидание"],

["forthcoming","предстоящий, грядущий"],

["ferris wheel","колесо обозрения"],

["racoon","енот"],

["rabid","бешеный"],

["presence","присутствие"],
["shelter","укрытие, убежище"],

["brief","краткий, лаконичный"],

["seagull","чайка"],

["tacky","липкий, вульгарный, на «t»"],

["lodge","сторожка, охотничий домик"],

["sirloin","вырезка, филейная часть"],

["contemplative","созерцательный"],

["to terminate","завершать, прекращать"],

["vigilant","бдительный"],
["paddle","весло, лопатка, ракетка (настольный теннис)"],

["asylum","убежище, приют"],

["bench","скамейка"],

["reliable","надежный"],

["hump","горб, бугор"],

["to simmer down","остыть, не быть таким напряженным"],

["to resemble","походить, напоминать, на «r»"],

["serenity","безмятежность, спокойствие"],

["to brag","хвататься, на «b»"],

["to press charge","выдвинуть обвинение"],

["to renovate","ремонтировать"],

["satellite","спутник"],

["junkyard","свалка"],

["witness","свидетель, очевидец"],

["mesh","сетчатый"],

["implicitly","неявно, косвенно"],

["sassy","дерзкий, на «sa»"],

["to get laid","переспать"],

["eligible","приемлемый, допустимый, на «е»"],

["slob","неряха, разгильдяй"],

["orphanage","детский дом"],

["orphan","сирота"],

["mortal","смертный, смертельный"],

["dandruff","перхоть"],

["to crave","жаждать, желать, на «с»"],

["renowded","известный, знаменитый, на «r»"],

["observation","наблюдение"],

["predator","хищник"],

["election","выборы, голосовние"],

["to molest","приставать, домогаться"],

["hazard","угроза, риск, опасность"],

["poverty","бедность, нищета"],

["spare","запасной"],

["to resemble","походить, напоминать"],

["bladder","мочевой пузырь"],

["tribe","племя, клан"],

["inevitable","неизбежный, неминуемый"],

["to elaborate","разрабатывать, вырабатывать"],

["wire","провод, кабель, на «w»"],

["skid","занос (когда не справился с управлением)"],

["emeritus","заслуженный, почечный (на «e»)"],

["enterprise","предприятие, компания"],

["emerging","возникающий, появляющийся"],

["dignity","достоинство"],

["to proceed","продолжать"],

["bizarre","странный, причудливый, на «b»"],

["germ","зачаток, бактерия, на «g»"],

["to distribute","распространять, распределять, на «d»"],

["crucifix","крест (религиозный)"],

["nationwide chain","многонациональный мир"],

["to decline","снижаться, на «dec»"],

["to obsolete","устареть"],

["mercury","ртуть"],

["annex","приложение, пристройка"],

["peasant","крестьянин"],

["prophecy","пророчество"],

["shindig","вечеринка"],

["obligation","обязанность"],

["feces","экскрименты"],

["to cater","обслуживать, угождать"],

["nausea","тошнота"],

["banisters","перила"],

["where to begin","с чего бы начать"],

["to pay off","расплатиться"],
["consternation","ужас, испуг, на «c»"],

["to negotiate","договариваться, вести переговоры"],

["regard","уважение, на «reg»"],

["jade","нефрит"],

["modest","скромный, на «m»"],

["inevitably","неизбежно"],

["mere","простой"],
["to shun","избегать, на «s»"],

["zoppity","масштабность"],

["circulation","кровообращение"],

["to get drafty","простыть (из-за сквозняка)"],

["fatigue","утомление"],

["irritability","раздражительность"],

["to contribute","способствовать"],
["rug","ковер"],

["to escort","сопровождать, провожать, на «е»"],

["straightforward","обычный, незамысловатый, на «s»"],

["accomplice","сообщник, соучастник"],

["hemp","конопля"],

["hotshot","крутой парень"],

["former","бывший, прежний, тогдашний"],

["jokester","шутник"],

["minor","несовершеннолетний"],

["to repulse","отбивать, отражать (атаку)"],

["against the will","против воли"],

["to take a chance on","дать шанс (кому-то)"],

//hp chapter 2
["to desecrate","осквернять"],

["to blackmail","шантажировать, вымогать"],

["commodity","товар"],

["improbable","невероятный, неправдоподобный"],

["royal","королевский"],*/
]
